// NeetCode All — wave 9a (arrays-hashing, two-pointers, sliding-window, stack, binary-search). Java.
// Same deep-teaching shape as wave8a: statement, examples, constraints, recognize,
// figureItOut (genuine from-scratch reasoning), approaches (with walkthrough on the optimal one),
// edgeCases, twists, related. All code is clean compilable Java assuming `import java.util.*;`.
export const WAVE9A = [
  // ───────────────────────────── ARRAYS & HASHING ─────────────────────────────
  {
    slug: "find-the-difference",
    title: "Find the Difference",
    difficulty: "Easy",
    pattern: "arrays-hashing",
    leetcode: 389,
    statement:
      "You are given two strings `s` and `t`. `t` is generated by shuffling `s` and then adding **one extra letter** at a random position. Return the extra letter that was added.",
    examples: [
      { in: 's = "abcd", t = "abcde"', out: '"e"', note: "e is the inserted letter" },
      { in: 's = "", t = "y"', out: '"y"' },
      { in: 's = "a", t = "aa"', out: '"a"', note: "the duplicate is the extra one" },
    ],
    constraints: ["0 ≤ s.length ≤ 1000", "t.length == s.length + 1", "lowercase English letters"],
    recognize:
      "Every letter of `s` appears in `t` an equal number of times, except one letter that appears **once more**. 'Two near-identical multisets, find the odd one out' → **frequency counting**, or even slicker, **XOR cancellation**.",
    figureItOut: [
      "Brute force temptation: for each char of t, check if removing it from s leaves them equal. That is O(n^2) and fiddly. Look for a counting structure.",
      "Count letters. Tally every character of t with +1 and every character of s with -1 into a 26-slot array. Each shared occurrence cancels to 0; the one extra occurrence in t leaves exactly one slot at +1.",
      "Now sharpen it. The relationship is 'one value appears an odd number of times across s+t combined' — that is the single-number pattern, solvable with XOR. XOR-ing a value with itself gives 0, so all matched chars cancel and only the extra survives.",
      "XOR every char code of both strings together. Matched chars pair up and vanish; the leftover bits spell the extra character. O(1) extra space, one pass.",
    ],
    approaches: [
      {
        name: "Frequency counting",
        intuition: "Add t's letters, subtract s's letters; the slot left positive is the answer.",
        time: "O(n)",
        timeWhy: "Two linear passes over strings of length about n.",
        space: "O(1)",
        spaceWhy: "A fixed 26-slot array.",
        code: `char findTheDifference(String s, String t) {
    int[] count = new int[26];
    for (char c : t.toCharArray()) count[c - 'a']++;
    for (char c : s.toCharArray()) count[c - 'a']--;
    for (int i = 0; i < 26; i++) {
        if (count[i] > 0) return (char) ('a' + i);
    }
    return ' '; // unreachable given the constraints
}`,
      },
      {
        name: "XOR cancellation (optimal)",
        intuition: "XOR all char codes of both strings; matched pairs cancel, the extra letter remains.",
        time: "O(n)",
        timeWhy: "One pass over each string.",
        space: "O(1)",
        spaceWhy: "A single accumulator integer.",
        code: `char findTheDifference(String s, String t) {
    int x = 0;
    for (char c : s.toCharArray()) x ^= c;
    for (char c : t.toCharArray()) x ^= c;
    return (char) x;
}`,
        walkthrough: [
          's=\"abcd\", t=\"abcde\". Start x=0. XOR a,b,c,d (from s).',
          "Then XOR a,b,c,d,e (from t). The a^a, b^b, c^c, d^d pairs all cancel to 0.",
          "Only e's bits remain → x = 'e' → return 'e'.",
        ],
      },
    ],
    edgeCases: [
      "s empty → t is a single char → that char is the answer.",
      "The extra letter equals an existing one (s=\"a\", t=\"aa\") → counting/XOR still isolates the odd occurrence.",
      "XOR avoids any overflow worry — char codes are small and XOR never grows the magnitude unboundedly.",
    ],
    twists: [
      "**Single Number** (LeetCode 136) → same XOR-cancellation idea on an int array.",
      "**Two extra letters added** → XOR no longer isolates a single value; fall back to frequency counting.",
      "**Find the extra letter's index in t** → counting tells you which letter; then scan t for it.",
    ],
    related: ["single-number", "valid-anagram"],
  },

  {
    slug: "intersection-of-two-arrays",
    title: "Intersection of Two Arrays",
    difficulty: "Easy",
    pattern: "arrays-hashing",
    leetcode: 349,
    statement:
      "Given two integer arrays `nums1` and `nums2`, return an array of their **intersection**. Each element in the result must be **unique**, and you may return the result in any order.",
    examples: [
      { in: "nums1 = [1,2,2,1], nums2 = [2,2]", out: "[2]" },
      { in: "nums1 = [4,9,5], nums2 = [9,4,9,8,4]", out: "[9,4]", note: "[4,9] is equally valid" },
    ],
    constraints: ["1 ≤ nums1.length, nums2.length ≤ 1000", "0 ≤ nums1[i], nums2[i] ≤ 1000"],
    recognize:
      "'Which values appear in **both** arrays, each only once' → put one array's values in a **hash set** and probe with the other. Sets give O(1) membership and automatic de-duplication.",
    figureItOut: [
      "Brute force: for each value in nums1, scan nums2 for a match → O(n*m), plus you must dedupe the output. Wasteful re-scanning.",
      "Membership 'is x in this collection?' answered in O(1) is exactly what a hash set is for. Drop all of nums1 into a set called seen.",
      "Walk nums2. If a value is in seen, it belongs to the intersection — add it to a result set (a set so each value lands at most once). Remove it from seen afterward to avoid re-adding, or just rely on the result set's uniqueness.",
      "Both arrays are visited once; set operations are O(1) average → O(n+m). Convert the result set to an array at the end.",
    ],
    approaches: [
      {
        name: "Two hash sets (optimal)",
        intuition: "Set of nums1's values; probe with nums2; collect hits in a result set.",
        time: "O(n + m)",
        timeWhy: "Build the set in O(n), probe in O(m), each op O(1) average.",
        space: "O(n)",
        spaceWhy: "The set holds up to n distinct values from nums1.",
        code: `int[] intersection(int[] nums1, int[] nums2) {
    Set<Integer> seen = new HashSet<>();
    for (int x : nums1) seen.add(x);
    Set<Integer> result = new HashSet<>();
    for (int x : nums2) {
        if (seen.contains(x)) result.add(x);
    }
    int[] out = new int[result.size()];
    int i = 0;
    for (int x : result) out[i++] = x;
    return out;
}`,
        walkthrough: [
          "nums1=[1,2,2,1] → seen={1,2}. nums2=[2,2].",
          "x=2 in seen → result={2}. second 2 already in result (set dedupes).",
          "result={2} → return [2].",
        ],
      },
      {
        name: "Sort + two pointers",
        intuition: "Sort both, walk in lockstep; on a match, record and skip duplicates.",
        time: "O(n log n + m log m)",
        timeWhy: "Dominated by sorting both arrays; the merge walk is linear.",
        space: "O(1)",
        spaceWhy: "Ignoring output, just the two pointers (sort may use its own).",
        code: `int[] intersection(int[] nums1, int[] nums2) {
    Arrays.sort(nums1);
    Arrays.sort(nums2);
    List<Integer> res = new ArrayList<>();
    int i = 0, j = 0;
    while (i < nums1.length && j < nums2.length) {
        if (nums1[i] < nums2[j]) i++;
        else if (nums1[i] > nums2[j]) j++;
        else {
            if (res.isEmpty() || res.get(res.size() - 1) != nums1[i]) res.add(nums1[i]);
            i++; j++;
        }
    }
    int[] out = new int[res.size()];
    for (int k = 0; k < out.length; k++) out[k] = res.get(k);
    return out;
}`,
      },
    ],
    edgeCases: [
      "No common values → empty array.",
      "Heavy duplicates in either input → the result set / dedupe step keeps each value once.",
      "Identical arrays → result is the set of their distinct values.",
    ],
    twists: [
      "**Intersection of Two Arrays II** (LeetCode 350) → keep multiplicity; use a frequency map instead of a set.",
      "**Values in a known small range** → swap the set for a boolean array indexed by value.",
      "**Streamed / huge inputs** → sort externally and two-pointer to bound memory.",
    ],
    related: ["contains-duplicate", "two-sum"],
  },

  {
    slug: "degree-of-an-array",
    title: "Degree of an Array",
    difficulty: "Easy",
    pattern: "arrays-hashing",
    leetcode: 697,
    statement:
      "The **degree** of an array is the maximum frequency of any one of its elements. Given a non-empty array `nums`, return the **smallest length** of a contiguous subarray that has the **same degree** as `nums`.",
    examples: [
      { in: "nums = [1,2,2,3,1]", out: "2", note: "degree is 2 (the two 2s); shortest spanning subarray is [2,2]" },
      { in: "nums = [1,2,2,3,1,4,2]", out: "6", note: "2 has degree 3; its span runs from index 1 to 6" },
    ],
    constraints: ["1 ≤ nums.length ≤ 5·10⁴", "0 ≤ nums[i] ≤ 10⁴"],
    recognize:
      "The answer is governed by the **most frequent value(s)**. For each value you need its count plus the **distance between its first and last occurrence**. 'First seen, last seen, and count per value' → three hash maps in one pass.",
    figureItOut: [
      "First, what does the answer depend on? Only values that hit the maximum frequency (the degree) matter — any winning subarray must contain all copies of at least one such value.",
      "For a value with the top frequency, the shortest subarray covering all its copies stretches from its FIRST occurrence to its LAST occurrence: length = last - first + 1.",
      "So in one pass record three things per value: how many times it appears (count), the index it first appeared (first), and the index it last appeared (last).",
      "After the pass, find the maximum count (the degree). Among all values whose count equals the degree, take the minimum of (last - first + 1). That is the answer.",
      "One linear pass to build the maps, one pass over distinct values to combine — O(n) overall.",
    ],
    approaches: [
      {
        name: "First/last/count maps in one pass (optimal)",
        intuition: "Track count, first index, last index per value; the answer is the tightest span among top-frequency values.",
        time: "O(n)",
        timeWhy: "One pass to fill the maps, one pass over distinct keys.",
        space: "O(n)",
        spaceWhy: "Up to n distinct values stored across the maps.",
        code: `int findShortestSubArray(int[] nums) {
    Map<Integer, Integer> count = new HashMap<>();
    Map<Integer, Integer> first = new HashMap<>();
    Map<Integer, Integer> last = new HashMap<>();
    for (int i = 0; i < nums.length; i++) {
        int v = nums[i];
        if (!first.containsKey(v)) first.put(v, i);
        last.put(v, i);
        count.merge(v, 1, Integer::sum);
    }
    int degree = 0;
    for (int c : count.values()) degree = Math.max(degree, c);
    int best = nums.length;
    for (int v : count.keySet()) {
        if (count.get(v) == degree) {
            best = Math.min(best, last.get(v) - first.get(v) + 1);
        }
    }
    return best;
}`,
        walkthrough: [
          "nums=[1,2,2,3,1,4,2]. count{1:2,2:3,3:1,4:1}, first{1:0,2:1,...}, last{1:4,2:6,...}.",
          "degree = 3 (value 2). Only value 2 hits the degree.",
          "span = last(2) - first(2) + 1 = 6 - 1 + 1 = 6 → return 6.",
        ],
      },
    ],
    edgeCases: [
      "All distinct → degree 1 → shortest spanning subarray for any value is length 1.",
      "Single element → degree 1, answer 1.",
      "Ties for the degree → take the value with the smallest span, not the first one found.",
    ],
    twists: [
      "**Return the subarray itself** → also record which value won, then slice [first..last].",
      "**Degree as the k-th highest frequency** → sort frequencies; otherwise identical span logic.",
      "**Longest subarray with the given degree** → that's just the whole array if it already has that degree.",
    ],
    related: ["majority-element", "top-k-frequent-elements"],
  },

  // ───────────────────────────── TWO POINTERS ─────────────────────────────
  {
    slug: "reverse-string",
    title: "Reverse String",
    difficulty: "Easy",
    pattern: "two-pointers",
    leetcode: 344,
    statement:
      "Write a function that reverses a string, given as a character array `s`. You must do it **in place** with O(1) extra memory.",
    examples: [
      { in: 's = ["h","e","l","l","o"]', out: '["o","l","l","e","h"]' },
      { in: 's = ["H","a","n","n","a","h"]', out: '["h","a","n","n","a","H"]' },
    ],
    constraints: ["1 ≤ s.length ≤ 10⁵", "s[i] is a printable ASCII character"],
    recognize:
      "Reversing **in place** means swapping the ends inward — the canonical **two-pointer** move. One pointer at the start, one at the end, swap and converge.",
    figureItOut: [
      "The obvious version builds a new reversed array, but that violates the O(1)-memory rule. We must rearrange the existing array.",
      "Reversal pairs up position 0 with the last, position 1 with second-last, and so on. That symmetric 'ends toward the middle' structure is two pointers.",
      "Put l at index 0 and r at the last index. Swap s[l] and s[r], then step l forward and r backward.",
      "Stop when l and r meet or cross — every element has been swapped exactly once, so the work is O(n) with no extra array.",
    ],
    approaches: [
      {
        name: "Two pointers, swap inward (optimal)",
        intuition: "Swap the outermost pair, then move both pointers toward the center.",
        time: "O(n)",
        timeWhy: "Each element is touched once in a single converging sweep.",
        space: "O(1)",
        spaceWhy: "Only two index variables and a temp for the swap.",
        code: `void reverseString(char[] s) {
    int l = 0, r = s.length - 1;
    while (l < r) {
        char tmp = s[l];
        s[l] = s[r];
        s[r] = tmp;
        l++;
        r--;
    }
}`,
        walkthrough: [
          's=[h,e,l,l,o]. l=0(h), r=4(o) → swap → [o,e,l,l,h], l=1, r=3.',
          "l=1(e), r=3(l) → swap → [o,l,l,e,h], l=2, r=2 → l not < r, stop.",
          "Result [o,l,l,e,h].",
        ],
      },
    ],
    edgeCases: [
      "Single character → l == r immediately, no swap, unchanged.",
      "Even length → pointers cross between the two middle elements; all pairs swapped.",
      "Odd length → the exact middle element stays put (l == r), correctly left alone.",
    ],
    twists: [
      "**Reverse words in a string** (already in the library) → reverse the whole thing, then reverse each word.",
      "**Reverse only vowels** → two pointers but only swap when both ends are vowels (LeetCode 345).",
      "**Recursive reverse** → swap ends and recurse inward; uses O(n) stack, breaking the O(1) rule.",
    ],
    related: ["valid-palindrome", "reverse-words-in-a-string"],
  },

  {
    slug: "merge-sorted-array",
    title: "Merge Sorted Array",
    difficulty: "Easy",
    pattern: "two-pointers",
    leetcode: 88,
    statement:
      "You are given two sorted integer arrays `nums1` and `nums2`, with `m` and `n` real elements. `nums1` has length `m + n`, where the trailing `n` slots are 0 placeholders. **Merge** nums2 into nums1 so nums1 becomes one sorted array, in place.",
    examples: [
      { in: "nums1 = [1,2,3,0,0,0], m = 3, nums2 = [2,5,6], n = 3", out: "[1,2,3,5,6]?", note: "result [1,2,2,3,5,6]" },
      { in: "nums1 = [1], m = 1, nums2 = [], n = 0", out: "[1]" },
      { in: "nums1 = [0], m = 0, nums2 = [1], n = 1", out: "[1]" },
    ],
    constraints: ["nums1.length == m + n", "0 ≤ m, n ≤ 200", "−10⁹ ≤ values ≤ 10⁹"],
    recognize:
      "Two sorted arrays to combine in place, with spare room at the **end** of nums1 → fill **back to front** with two pointers. Writing into the largest free slot first avoids overwriting unread data.",
    figureItOut: [
      "The trap: merging front-to-front would overwrite nums1's own unprocessed elements, because the write head would collide with the read head. The empty space is at the back, so write from the back.",
      "Place three pointers: i at the last real element of nums1 (m-1), j at the last of nums2 (n-1), and a write pointer k at the very end (m+n-1).",
      "At each step compare nums1[i] and nums2[j]; place the LARGER at position k, then move that source pointer and k backward. The largest remaining value always lands in the largest free slot.",
      "When nums2 runs out (j < 0) you're done — any leftover nums1 elements are already in place. When nums1 runs out first (i < 0), copy the rest of nums2 down.",
      "Each value is written once → O(m+n), no extra array needed.",
    ],
    approaches: [
      {
        name: "Naive — copy then sort",
        intuition: "Drop nums2 into the tail of nums1, then sort the whole thing.",
        time: "O((m+n) log (m+n))",
        timeWhy: "Dominated by sorting the combined array.",
        space: "O(1)",
        spaceWhy: "In place, but throws away the pre-sortedness.",
        code: `void merge(int[] nums1, int m, int[] nums2, int n) {
    for (int j = 0; j < n; j++) nums1[m + j] = nums2[j];
    Arrays.sort(nums1);
}`,
      },
      {
        name: "Two pointers from the back (optimal)",
        intuition: "Compare tails; write the larger into the rightmost open slot; move inward.",
        time: "O(m + n)",
        timeWhy: "Each element placed exactly once in a single backward sweep.",
        space: "O(1)",
        spaceWhy: "Three index variables, no extra storage.",
        code: `void merge(int[] nums1, int m, int[] nums2, int n) {
    int i = m - 1, j = n - 1, k = m + n - 1;
    while (j >= 0) {
        if (i >= 0 && nums1[i] > nums2[j]) {
            nums1[k--] = nums1[i--];
        } else {
            nums1[k--] = nums2[j--];
        }
    }
}`,
        walkthrough: [
          "nums1=[1,2,3,0,0,0] m=3, nums2=[2,5,6] n=3. i=2(3),j=2(6),k=5.",
          "6>3 → nums1[5]=6, j=1,k=4. 5>3 → nums1[4]=5, j=0,k=3. 2<3 → nums1[3]=3, i=1,k=2.",
          "i=1(2),j=0(2): not (2>2) → take nums2 → nums1[2]=2,j=-1 → stop → [1,2,2,3,5,6].",
        ],
      },
    ],
    edgeCases: [
      "n == 0 → nums2 empty, the while loop never runs, nums1 unchanged.",
      "m == 0 → all of nums2 copied down (the i>=0 guard prevents reading nums1).",
      "All of nums2 larger than all of nums1 → nums2 fills the tail, nums1's elements never move.",
    ],
    twists: [
      "**Merge two sorted lists** (linked lists) → same merge logic with node splicing instead of indices.",
      "**Squares of a sorted array** → a back-to-front two-pointer fill of a different kind.",
      "**k sorted arrays** → generalize to a heap-based k-way merge.",
    ],
    related: ["merge-two-sorted-lists", "squares-of-a-sorted-array"],
  },

  {
    slug: "backspace-string-compare",
    title: "Backspace String Compare",
    difficulty: "Easy",
    pattern: "two-pointers",
    leetcode: 844,
    statement:
      "Given two strings `s` and `t`, return `true` if they are equal when both are typed into empty text editors. The character `#` means a **backspace** (deletes the previous character; on empty text it does nothing).",
    examples: [
      { in: 's = "ab#c", t = "ad#c"', out: "true", note: 'both become "ac"' },
      { in: 's = "ab##", t = "c#d#"', out: "true", note: 'both become ""' },
      { in: 's = "a#c", t = "b"', out: "false", note: '"c" vs "b"' },
    ],
    constraints: ["1 ≤ s.length, t.length ≤ 200", "lowercase letters and '#'"],
    recognize:
      "Backspace deletes the **most recent** kept char → a **stack** builds each final string. But the O(1)-space version reads both strings **from the right with two pointers**, since a char's survival depends only on backspaces to its right.",
    figureItOut: [
      "The easy mental model is a stack: scan left to right, push letters, and on '#' pop the top. Build both final strings and compare. That is O(n) time but O(n) space.",
      "To reach O(1) space, flip direction. Reading right-to-left, you encounter backspaces BEFORE the characters they delete. So a counter of pending skips tells you whether the next real char survives.",
      "Walk each string from the end with its own pointer. On '#', increment that string's skip count. On a letter, if skip > 0 consume one skip and move on; otherwise this letter is a genuine surviving character — pause here.",
      "Advance both pointers to their next surviving characters and compare them. If one survivor differs from the other, return false; if one string runs out of survivors before the other, they differ.",
      "When both pointers fall off the left end simultaneously with all survivors matched, the strings are equal.",
    ],
    approaches: [
      {
        name: "Build with a stack",
        intuition: "Replay the typing into a StringBuilder; '#' pops the last char.",
        time: "O(n + m)",
        timeWhy: "One pass per string to build, one to compare.",
        space: "O(n + m)",
        spaceWhy: "Each rebuilt final string can be linear in size.",
        code: `boolean backspaceCompare(String s, String t) {
    return build(s).equals(build(t));
}

private String build(String str) {
    StringBuilder sb = new StringBuilder();
    for (char c : str.toCharArray()) {
        if (c == '#') {
            if (sb.length() > 0) sb.deleteCharAt(sb.length() - 1);
        } else {
            sb.append(c);
        }
    }
    return sb.toString();
}`,
      },
      {
        name: "Two pointers from the right (optimal)",
        intuition: "Scan both backwards; pending '#' counts skip upcoming letters; compare surviving chars.",
        time: "O(n + m)",
        timeWhy: "Each character is visited at most once per string.",
        space: "O(1)",
        spaceWhy: "Only pointers and two skip counters.",
        code: `boolean backspaceCompare(String s, String t) {
    int i = s.length() - 1, j = t.length() - 1;
    int skipS = 0, skipT = 0;
    while (i >= 0 || j >= 0) {
        while (i >= 0) {
            if (s.charAt(i) == '#') { skipS++; i--; }
            else if (skipS > 0) { skipS--; i--; }
            else break;
        }
        while (j >= 0) {
            if (t.charAt(j) == '#') { skipT++; j--; }
            else if (skipT > 0) { skipT--; j--; }
            else break;
        }
        if (i >= 0 && j >= 0) {
            if (s.charAt(i) != t.charAt(j)) return false;
        } else if (i >= 0 || j >= 0) {
            return false; // one has a surviving char, the other is exhausted
        }
        i--; j--;
    }
    return true;
}`,
        walkthrough: [
          's=\"ab#c\", t=\"ad#c\". i finds c (no skips), j finds c → equal, step in.',
          'Next survivor in s: c was index3; index2=#, so b at index1 is skipped → survivor a (index0). Same in t → a.',
          "Both reach a, compare equal, then both pointers fall off → return true.",
        ],
      },
    ],
    edgeCases: [
      "Backspace on empty text does nothing (skip count just stays, no underflow).",
      "Both reduce to the empty string → true.",
      "Equal lengths but different survivors → caught at the first mismatched surviving char.",
    ],
    twists: [
      "**Removing Stars From a String** (LeetCode 2390) → '*' is the backspace; the stack version is identical.",
      "**Report the final typed string** → the stack approach already yields it.",
      "**Multiple backspace chars / different delete keys** → same skip-count logic, just match more delete symbols.",
    ],
    related: ["removing-stars-from-a-string", "valid-palindrome-ii"],
  },

  // ───────────────────────────── SLIDING WINDOW ─────────────────────────────
  {
    slug: "longest-subarray-of-1s-after-deleting-one-element",
    title: "Longest Subarray of 1's After Deleting One Element",
    difficulty: "Medium",
    pattern: "sliding-window",
    leetcode: 1493,
    statement:
      "Given a binary array `nums`, you must **delete exactly one element**. Return the size of the **longest non-empty subarray of all 1's** in the resulting array.",
    examples: [
      { in: "nums = [1,1,0,1]", out: "3", note: "delete the 0 → [1,1,1]" },
      { in: "nums = [0,1,1,1,0,1,1,0,1]", out: "5", note: "delete index 4 → [0,1,1,1,1,1,0,1]" },
      { in: "nums = [1,1,1]", out: "2", note: "must delete one, leaving two 1's" },
    ],
    constraints: ["1 ≤ nums.length ≤ 10⁵", "nums[i] is 0 or 1"],
    recognize:
      "'Longest run of 1's if we may drop one element' is the same as 'longest window containing **at most one 0**' — minus that mandatory one deletion. Classic **variable-size sliding window** bounding the count of zeros.",
    figureItOut: [
      "Reframe the deletion. Deleting one element to maximize a run of 1's is most useful when you delete a single 0 sitting between two blocks of 1's, stitching them together.",
      "So the quantity to maximize is the longest window that contains AT MOST ONE zero — those are the 1's plus the single deletable 0.",
      "Slide a window [l..r], counting zeros inside. Extend r; if the window ever holds more than one 0, shrink from the left until it holds at most one again.",
      "Within such a window of length (r - l + 1), one slot is the deleted element. The number of 1's that survive is (window length - 1). Track the max of that.",
      "The '-1' also handles the all-ones case correctly: a window of all 1's still spends its mandatory deletion, so the answer is length - 1 rather than length.",
    ],
    approaches: [
      {
        name: "Sliding window, at most one zero (optimal)",
        intuition: "Grow a window allowing one zero; the answer is the largest window length minus one (the deleted slot).",
        time: "O(n)",
        timeWhy: "l and r each advance at most n times.",
        space: "O(1)",
        spaceWhy: "A zero counter and two indices.",
        code: `int longestSubarray(int[] nums) {
    int l = 0, zeros = 0, best = 0;
    for (int r = 0; r < nums.length; r++) {
        if (nums[r] == 0) zeros++;
        while (zeros > 1) {
            if (nums[l] == 0) zeros--;
            l++;
        }
        best = Math.max(best, r - l); // window length minus the one deleted element
    }
    return best;
}`,
        walkthrough: [
          "nums=[1,1,0,1]. r=0 win[0,0] zeros0 best=0. r=1 win[0,1] best=1.",
          "r=2 (0) zeros1 win[0,2] best=max(1, 2-0)=2. r=3 win[0,3] zeros1 best=max(2, 3-0)=3.",
          "Answer 3 (delete the single 0).",
        ],
      },
    ],
    edgeCases: [
      "All 1's (e.g. [1,1,1]) → window never exceeds one zero; best = length - 1 = 2.",
      "All 0's → best stays 0 (no 1's survive).",
      "Single element → must delete it, answer 0; `r - l` correctly yields 0.",
    ],
    twists: [
      "**Max Consecutive Ones III** (LeetCode 1004, in the library) → allow flipping K zeros; use `r - l + 1` and bound zeros by K.",
      "**Delete at most one (not exactly one)** → take max(answer, count of longest pure-1 run).",
      "**Longest run of a target value with one deletion** → same window, compare against the target instead of 1.",
    ],
    related: ["max-consecutive-ones-iii", "longest-repeating-character-replacement"],
  },

  {
    slug: "number-of-subarrays-with-bounded-maximum",
    title: "Number of Subarrays with Bounded Maximum",
    difficulty: "Medium",
    pattern: "sliding-window",
    leetcode: 795,
    statement:
      "Given an integer array `nums` and integers `left` and `right`, return the number of contiguous subarrays whose **maximum element** is in the range `[left, right]` (inclusive).",
    examples: [
      { in: "nums = [2,1,4,3], left = 2, right = 3", out: "3", note: "[2],[2,1],[3]" },
      { in: "nums = [2,9,2,5,6], left = 2, right = 8", out: "7" },
    ],
    constraints: ["1 ≤ nums.length ≤ 10⁵", "0 ≤ nums[i] ≤ 10⁹", "0 ≤ left ≤ right ≤ 10⁹"],
    recognize:
      "Counting subarrays whose max lies in a band → the **count-difference trick**: subarrays with max ≤ right, minus subarrays with max ≤ (left − 1). Each 'max ≤ bound' count is a simple linear scan tracking the last element that broke the bound.",
    figureItOut: [
      "Directly enforcing 'max is between left and right' is awkward because it is a two-sided constraint. Split it into two one-sided counts.",
      "Let f(bound) = number of subarrays whose maximum is ≤ bound. Then subarrays with max in [left, right] = f(right) - f(left - 1). The f(left-1) term removes subarrays whose max is too small.",
      "Computing f(bound): walk the array; a subarray is valid only if EVERY element is ≤ bound. Keep a counter `len` of the current run of elements all ≤ bound. Each new valid element extends the run and adds `len` new subarrays ending here.",
      "When you hit an element > bound, the run breaks: reset `len` to 0 (no subarray ending at or spanning this element can stay ≤ bound).",
      "Two linear passes (one for each bound) → O(n). No nested loops, no per-subarray max computation.",
    ],
    approaches: [
      {
        name: "Brute force — max of every subarray",
        intuition: "For each (l, r) track the running max and test the band.",
        time: "O(n²)",
        timeWhy: "n starts, each extended up to n with a running max.",
        space: "O(1)",
        spaceWhy: "A running max and a counter.",
        code: `int numSubarrayBoundedMax(int[] nums, int left, int right) {
    int count = 0;
    for (int l = 0; l < nums.length; l++) {
        int mx = Integer.MIN_VALUE;
        for (int r = l; r < nums.length; r++) {
            mx = Math.max(mx, nums[r]);
            if (mx >= left && mx <= right) count++;
        }
    }
    return count;
}`,
      },
      {
        name: "Count-difference, two linear scans (optimal)",
        intuition: "count(max ≤ right) − count(max ≤ left−1), each computed by a run-length scan.",
        time: "O(n)",
        timeWhy: "Two single passes over the array.",
        space: "O(1)",
        spaceWhy: "A couple of counters.",
        code: `int numSubarrayBoundedMax(int[] nums, int left, int right) {
    return countMaxAtMost(nums, right) - countMaxAtMost(nums, left - 1);
}

private int countMaxAtMost(int[] nums, int bound) {
    int count = 0, len = 0;
    for (int v : nums) {
        if (v <= bound) {
            len++;                 // current element extends the valid run
            count += len;          // new subarrays ending here
        } else {
            len = 0;               // run broken; nothing valid spans this element
        }
    }
    return count;
}`,
        walkthrough: [
          "nums=[2,1,4,3], left=2, right=3. countMaxAtMost(3): v=2 len1 c1; v=1 len2 c3; v=4 reset len0; v=3 len1 c4 → 4.",
          "countMaxAtMost(1): v=2 reset; v=1 len1 c1; v=4 reset; v=3 reset → 1.",
          "Answer = 4 - 1 = 3.",
        ],
      },
    ],
    edgeCases: [
      "left == 0 → count(max ≤ -1) is 0, so the answer is just count(max ≤ right).",
      "All elements > right → f(right) is 0 → answer 0.",
      "Using `len` reset to 0 on a too-large element is what excludes any subarray crossing it.",
    ],
    twists: [
      "**Max strictly less than a value** → use bound - 1 (or `< bound` in the test).",
      "**Subarrays with minimum in a range** → flip the comparison to count mins ≤ bound.",
      "**Sum/length in a range instead of max** → different technique (prefix sums or a different window).",
    ],
    related: ["subarray-product-less-than-k", "subarray-sum-equals-k"],
  },

  // ───────────────────────────── STACK ─────────────────────────────
  {
    slug: "minimum-add-to-make-parentheses-valid",
    title: "Minimum Add to Make Parentheses Valid",
    difficulty: "Medium",
    pattern: "stack",
    leetcode: 921,
    statement:
      "A parentheses string is valid if every `(` has a matching `)` and they nest properly. Given a string `s` of `(` and `)`, return the **minimum number of parentheses** you must insert (anywhere) to make `s` valid.",
    examples: [
      { in: 's = "())"', out: "1", note: 'add one "(" → "(())"' },
      { in: 's = "((("', out: "3", note: "three unmatched opens need three closes" },
      { in: 's = "()"', out: "0" },
    ],
    constraints: ["1 ≤ s.length ≤ 1000", "s consists of '(' and ')' only"],
    recognize:
      "Balancing parentheses → think **stack**, but here you only need the **count** of unmatched brackets, so the stack collapses into two counters: open brackets waiting and close brackets with no partner.",
    figureItOut: [
      "Imagine the stack solution: push each '(' ; on ')' pop a matching '('. Anything left on the stack at the end, plus every ')' that found nothing to pop, must be repaired.",
      "You never need the actual stack contents — only HOW MANY '(' are currently unmatched. Replace the stack with a counter `open`.",
      "Scan left to right. On '(' do open++. On ')', if open > 0 it pairs off (open--); otherwise this ')' is orphaned — increment an `insertions` counter, because we must add a '(' before it.",
      "At the end, `open` is the number of '(' still without a partner; each needs a ')' added. Total = insertions + open.",
      "One pass, two integers, O(1) space — the stack was overkill once you realized only counts matter.",
    ],
    approaches: [
      {
        name: "Two counters (collapsed stack, optimal)",
        intuition: "Track unmatched opens; orphaned closes are repaired immediately; leftover opens repaired at the end.",
        time: "O(n)",
        timeWhy: "Single pass over the string.",
        space: "O(1)",
        spaceWhy: "Two integer counters, no stack storage.",
        code: `int minAddToMakeValid(String s) {
    int open = 0;        // unmatched '(' so far
    int insertions = 0;  // '(' we must add for orphaned ')'
    for (char c : s.toCharArray()) {
        if (c == '(') {
            open++;
        } else { // ')'
            if (open > 0) open--;   // pairs with a waiting '('
            else insertions++;       // no partner → need to add a '('
        }
    }
    return insertions + open;        // plus a ')' for each leftover '('
}`,
        walkthrough: [
          's=\"())\". c=\'(\' open=1. c=\')\' open>0 → open=0. c=\')\' open==0 → insertions=1.',
          "End: insertions=1, open=0 → total 1.",
          'For \"(((\": three \'(\' → open=3, insertions=0 → total 3.',
        ],
      },
    ],
    edgeCases: [
      "Already valid → insertions and open both 0 → answer 0.",
      "All closes (\")))\") → every one is orphaned → answer equals the length.",
      "All opens (\"(((\") → no orphans, but open accumulates → answer equals the length.",
    ],
    twists: [
      "**Minimum Remove to Make Valid** (LeetCode 1249) → count is the same idea, but you must output the cleaned string (use a real stack of indices).",
      "**Brackets with a wildcard '*'** → Valid Parenthesis String; greedy range of possible open counts.",
      "**Multiple bracket types** → a genuine stack is required to match types, not just counts.",
    ],
    related: ["valid-parentheses", "valid-parenthesis-string"],
  },

  {
    slug: "remove-all-adjacent-duplicates-in-string",
    title: "Remove All Adjacent Duplicates In String",
    difficulty: "Easy",
    pattern: "stack",
    leetcode: 1047,
    statement:
      "Given a string `s` of lowercase letters, repeatedly remove **two adjacent equal letters**. Keep removing until no such pair remains, and return the final string. The result is guaranteed unique.",
    examples: [
      { in: 's = "abbaca"', out: '"ca"', note: '"bb" goes → "aaca", then "aa" goes → "ca"' },
      { in: 's = "azxxzy"', out: '"ay"', note: 'xx → "azzy", then zz → "ay"' },
    ],
    constraints: ["1 ≤ s.length ≤ 10⁵", "lowercase English letters"],
    recognize:
      "'Cancel a character against the **most recently kept** one if they match' → a **stack**. Each char either annihilates the top (equal) or gets pushed; the leftover stack is the answer.",
    figureItOut: [
      "Repeatedly rescanning the string for adjacent pairs is O(n^2) in the worst case (each removal can create a new adjacency earlier). We want a single pass.",
      "The deciding comparison for the current char is always against the char immediately to its left in the result-so-far — i.e. the LAST char we kept. 'Last kept' is the top of a stack.",
      "Scan left to right. If the stack's top equals the current char, they form an adjacent duplicate → pop the top (both vanish). Otherwise push the current char.",
      "Because a pop exposes the previous kept char, a newly created adjacency is checked on the very next step automatically — no rescanning.",
      "A StringBuilder doubles as the stack: its last char is the top; append to push, delete the last char to pop. Read it out at the end.",
    ],
    approaches: [
      {
        name: "Stack / StringBuilder (optimal)",
        intuition: "Push each char unless it equals the top, in which case pop instead.",
        time: "O(n)",
        timeWhy: "Each char is pushed once and popped at most once.",
        space: "O(n)",
        spaceWhy: "The stack can hold up to n surviving characters.",
        code: `String removeDuplicates(String s) {
    StringBuilder stack = new StringBuilder();
    for (char c : s.toCharArray()) {
        int len = stack.length();
        if (len > 0 && stack.charAt(len - 1) == c) {
            stack.deleteCharAt(len - 1);   // adjacent duplicate cancels
        } else {
            stack.append(c);                // keep it
        }
    }
    return stack.toString();
}`,
        walkthrough: [
          's=\"abbaca\". a → \"a\". b → \"ab\". b matches top b → pop → \"a\".',
          'a matches top a → pop → \"\". c → \"c\". a → \"ca\".',
          'No more adjacencies → \"ca\".',
        ],
      },
    ],
    edgeCases: [
      "No duplicates at all → the string is returned unchanged.",
      "Entire string cancels (e.g. \"aabb\") → empty result.",
      "A pop exposing an equal char beneath (e.g. \"aaa\" → pop leaves \"a\") is handled by checking the new top next iteration.",
    ],
    twists: [
      "**Remove all adjacent duplicates II** (LeetCode 1209) → remove runs of length k; store (char, count) on the stack.",
      "**Removing Stars From a String** (LeetCode 2390) → '*' pops unconditionally instead of on a match.",
      "**Keep going until stable with different rules** → the stack pattern generalizes to many 'cancel against the top' problems.",
    ],
    related: ["removing-stars-from-a-string", "valid-parentheses"],
  },

  // ───────────────────────────── BINARY SEARCH ─────────────────────────────
  {
    slug: "valid-perfect-square",
    title: "Valid Perfect Square",
    difficulty: "Easy",
    pattern: "binary-search",
    leetcode: 367,
    statement:
      "Given a positive integer `num`, return `true` if it is a **perfect square** (the square of an integer), otherwise `false`. Do not use any built-in square-root function.",
    examples: [
      { in: "num = 16", out: "true", note: "4 * 4 = 16" },
      { in: "num = 14", out: "false" },
      { in: "num = 1", out: "true" },
    ],
    constraints: ["1 ≤ num ≤ 2³¹ − 1"],
    recognize:
      "You are searching for an integer `r` with `r*r == num` over the sorted range 1..num. A **monotonic** quantity (r² increases with r) over a sorted range → **binary search** on the answer.",
    figureItOut: [
      "Without sqrt, the candidate roots 1, 2, 3, ... up to num form a sorted list, and their squares increase monotonically. That monotonicity is the green light for binary search.",
      "Binary-search r in [1, num]. Compute square = r*r. If it equals num, true. If it's too small, the root must be larger → move lo up. If too large → move hi down.",
      "Overflow is the real trap: r near 2^31 squared blows past int range. Use `long` for the product (or compare r against num/r).",
      "Shrink hi to num (the root can't exceed num, and for num ≥ 2 it can't exceed num/2, but num is a safe simple bound). Loop while lo ≤ hi; if you exit without an exact hit, it's not a perfect square.",
    ],
    approaches: [
      {
        name: "Linear / subtract odd numbers",
        intuition: "1+3+5+... = consecutive perfect squares; subtract odds until you hit 0 or go negative.",
        time: "O(√num)",
        timeWhy: "About √num odd numbers fit before exceeding num.",
        space: "O(1)",
        spaceWhy: "Just a running value.",
        code: `boolean isPerfectSquare(int num) {
    long odd = 1;
    long n = num;
    while (n > 0) {
        n -= odd;
        odd += 2;
    }
    return n == 0;
}`,
      },
      {
        name: "Binary search on the root (optimal)",
        intuition: "Search r in [1, num]; compare r*r against num and halve the range.",
        time: "O(log num)",
        timeWhy: "The candidate range halves each step.",
        space: "O(1)",
        spaceWhy: "A few long variables.",
        code: `boolean isPerfectSquare(int num) {
    long lo = 1, hi = num;
    while (lo <= hi) {
        long mid = lo + (hi - lo) / 2;
        long sq = mid * mid;
        if (sq == num) return true;
        else if (sq < num) lo = mid + 1;
        else hi = mid - 1;
    }
    return false;
}`,
        walkthrough: [
          "num=16. lo=1,hi=16,mid=8 → 64>16 → hi=7. mid=4 → 16==16 → true.",
          "num=14. ...mid=4 → 16>14 hi=3. mid=2 → 4<14 lo=3. mid=3 → 9<14 lo=4 → lo>hi → false.",
          "Using long for mid*mid avoids overflow at large num.",
        ],
      },
    ],
    edgeCases: [
      "num == 1 → mid=1, 1==1 → true.",
      "Largest inputs near 2³¹ → mid*mid must be `long` or it overflows and gives wrong comparisons.",
      "num == 2 → not a square → false (loop converges and exits).",
    ],
    twists: [
      "**Sqrt(x)** (LeetCode 69, in the library) → same search but return the floor of the root.",
      "**Check perfect cube** → search with mid*mid*mid (watch overflow even harder).",
      "**Newton's method** → faster convergence than binary search but trickier to reason about.",
    ],
    related: ["sqrtx", "binary-search"],
  },

  {
    slug: "arranging-coins",
    title: "Arranging Coins",
    difficulty: "Easy",
    pattern: "binary-search",
    leetcode: 441,
    statement:
      "You have `n` coins to build a staircase where the k-th row has exactly `k` coins. The last row may be incomplete. Return the number of **complete rows** you can build.",
    examples: [
      { in: "n = 5", out: "2", note: "rows of 1 and 2 use 3 coins; the 3rd row would need 3 but only 2 remain" },
      { in: "n = 8", out: "3", note: "1+2+3 = 6 complete; 2 coins left can't finish row 4" },
    ],
    constraints: ["1 ≤ n ≤ 2³¹ − 1"],
    recognize:
      "k complete rows use `k(k+1)/2` coins — a value that **increases monotonically** with k. 'Largest k with k(k+1)/2 ≤ n' over a sorted range → **binary search** (the closed-form quadratic also works).",
    figureItOut: [
      "Building k full rows costs 1+2+...+k = k(k+1)/2 coins. As k grows, this cost only grows — a monotonic relationship.",
      "The question becomes: what is the LARGEST k such that k(k+1)/2 ≤ n? Monotonic predicate over k = 1..n → binary search for the boundary.",
      "Binary-search k in [1, n]. Compute coins = k(k+1)/2 with `long` (k near 2^31 squared overflows int badly). If coins ≤ n, k rows fit, so record k and try larger; else try smaller.",
      "Track the best feasible k as you go; when lo passes hi, that recorded best is the answer.",
      "A purely arithmetic alternative: solve k(k+1)/2 ≤ n for k, giving k = floor((sqrt(8n+1) - 1) / 2) — but binary search avoids floating-point precision pitfalls at huge n.",
    ],
    approaches: [
      {
        name: "Subtract row by row",
        intuition: "Peel off rows 1, 2, 3, ... until the coins can't cover the next row.",
        time: "O(√n)",
        timeWhy: "About √n rows fit before the coins run out.",
        space: "O(1)",
        spaceWhy: "A running coin count and row index.",
        code: `int arrangeCoins(int n) {
    int row = 0;
    long remaining = n;
    while (remaining >= row + 1) {
        row++;
        remaining -= row;
    }
    return row;
}`,
      },
      {
        name: "Binary search on the row count (optimal)",
        intuition: "Find the largest k with k(k+1)/2 ≤ n by halving the range.",
        time: "O(log n)",
        timeWhy: "The candidate range for k halves each iteration.",
        space: "O(1)",
        spaceWhy: "A few long variables.",
        code: `int arrangeCoins(int n) {
    long lo = 1, hi = n, best = 0;
    while (lo <= hi) {
        long k = lo + (hi - lo) / 2;
        long coins = k * (k + 1) / 2;   // long to avoid overflow
        if (coins <= n) {
            best = k;                    // k rows fit; try for more
            lo = k + 1;
        } else {
            hi = k - 1;
        }
    }
    return (int) best;
}`,
        walkthrough: [
          "n=8. lo=1,hi=8,k=4 → 4*5/2=10>8 → hi=3. k=2 → 3≤8 → best=2, lo=3.",
          "k=3 → 6≤8 → best=3, lo=4 → lo>hi → stop.",
          "Return 3.",
        ],
      },
    ],
    edgeCases: [
      "n == 1 → exactly one complete row → 1.",
      "Huge n near 2³¹ → k*(k+1) overflows int; `long` is mandatory.",
      "n exactly triangular (e.g. 6 = 1+2+3) → all rows complete, return that k.",
    ],
    twists: [
      "**Closed-form** → k = floor((sqrt(8n+1) - 1)/2); fast but watch floating-point error at large n.",
      "**Rows grow by 2 each time** → adjust the cost formula, same monotonic search.",
      "**Return leftover coins too** → n - best(best+1)/2.",
    ],
    related: ["sqrtx", "valid-perfect-square"],
  },
];
