// Computer-science core: data structures & algorithms, explained for a curious beginner.
export const CS_CORE = {
  "data-structures-overview": {
    slug: "data-structures-overview",
    title: "Data structures, mapped",
    category: "Computer Science",
    color: "purple",
    tagline: "Same data, a dozen ways to arrange it — and the arrangement decides what's fast and what's painfully slow.",
    oneLiner: "A data structure is a chosen way to lay out information in memory so the operations you do most often are the ones that are fast.",
    what: [
      "A **data structure** is just a deliberate way of organising data inside the computer. The data itself — a list of orders, a set of usernames, a map of streets — is the same; the *arrangement* is the choice. And that choice quietly decides which actions are instant and which crawl.",
      "Here's the key idea a beginner should hold onto: there is **no single best structure**. Each one is brilliant at a few things and clumsy at the rest. An **array** finds the 500th item instantly but is slow to insert in the middle. A **hash table** looks things up by name in a blink but can't tell you what comes ‘next' in order. A **tree** keeps things sorted but is slower than a hash table for a plain lookup.",
      "So learning data structures isn't memorising shapes — it's learning to ask *‘what will I do to this data most often?'* and then reaching for the structure built for exactly that. That single question is most of the skill.",
    ],
    analogy: {
      title: "How you organise a kitchen",
      body: "You don't store everything one way. Spices go on a rack alphabetically so you grab one by name instantly (a hash table). Plates stack so you always take the top one (a stack). The queue of dirty dishes is handled oldest-first (a queue). A recipe's steps run in fixed order (an array). Same kitchen, different arrangements — each chosen because of how you *use* that thing. Data structures are exactly this, for information.",
    },
    insideTitle: "The family, at a glance",
    inside: [
      { name: "Arrays", desc: "Items in a numbered row. Instant access by position; slow to insert in the middle." },
      { name: "Linked lists", desc: "Items chained by pointers. Cheap to splice in/out; slow to jump to the Nth item." },
      { name: "Hash tables", desc: "Look up a value by a key (a name) in roughly one step. No natural order." },
      { name: "Trees & graphs", desc: "Branching shapes for hierarchy and ordered lookup; networks for ‘things connected to things'." },
      { name: "Stacks, queues & heaps", desc: "Lists with a rule about *which* item you take next — last, first, or smallest." },
    ],
    how: [
      "Under the hood, almost every structure is built from two raw ingredients the computer gives you: a **contiguous block** of memory (numbered slots in a row — that's an array) and a **pointer** (a value that holds the address of another piece of memory — that's how a linked list, tree, or graph chains things together). Everything fancier is a clever combination of those two.",
      "When you pick a structure, what you're really choosing is the **cost** of each operation — and we measure that cost with **Big-O notation** (how the time grows as the data grows). The whole art is matching the cheap operations of a structure to the operations your program does over and over.",
    ],
    why: [
      "Choosing well is the difference between a feature that feels instant and one that times out. Swap a slow lookup (scanning a list) for a fast one (a hash table) and a screen that took two seconds can render in two milliseconds — same data, same computer, just a better arrangement.",
      "The trade-off is always the same shape: making one operation fast usually makes another slower, or uses more memory. There is no free lunch — only the right lunch for *your* appetite.",
    ],
    alternatives: [
      { name: "Just use a list for everything", note: "Fine for tiny data. The moment you search or grow it a lot, the wrong structure becomes the bottleneck." },
      { name: "A database", note: "When data must outlive the program and be shared, you hand organising-and-finding to a database — which uses these same structures (indexes are trees!) internally." },
      { name: "A library's built-in collections", note: "Most languages ship `Map`, `Set`, `List`, etc. You rarely build these by hand — but you must know which to pick." },
    ],
    whoUses: "Every working programmer, every day — usually without naming it. Backend engineers pick a `Map` over a list to de-duplicate orders; mobile devs choose how to hold a cart in memory; anyone who has passed a coding interview at Google, Amazon, or a startup has been grilled on exactly these trade-offs. It is the most universally shared knowledge in software.",
    bigPicture: "This is the lens for everything that follows. The database's fast lookups are B-tree indexes; a router's URL matching is a tree; a cache is a hash table; a job system is a queue. Once you see data structures, you start seeing them *inside* every other technology you learn.",
    prereqs: ["variables-and-memory", "what-is-a-program"],
    projects: [
      "Take one screen in an app and write down, for each piece of data it holds, which structure fits and why.",
      "Implement the same ‘find a user by id' two ways — scanning a list vs a hash map — and time both as the data grows.",
    ],
    breaks: "Reach for the comfortable structure instead of the correct one and everything *works* in testing with ten rows — then grinds to a halt in production with ten thousand. The classic: scanning a list to check ‘have I seen this id?' inside a loop, turning a fast job into one that takes minutes. The data was never the problem; the arrangement was.",
    scale: "Tiny: any structure is fine, pick the simplest. Thousands of items: the right choice starts to matter for snappy screens. Millions: it's decisive — the wrong structure is the difference between a working feature and an outage. Planet-scale: the structures move *into* infrastructure — distributed hash tables, log-structured trees in databases — but the same trade-offs you learn here still govern them.",
    related: ["big-o-notation", "arrays-and-strings", "hash-tables", "trees-and-bsts", "sql"],
  },

  "arrays-and-strings": {
    slug: "arrays-and-strings",
    title: "Arrays & strings",
    category: "Computer Science",
    color: "blue",
    tagline: "Items lined up in numbered slots — the simplest structure, and the one you'll use most.",
    oneLiner: "An array is a fixed row of slots in memory you can read by number instantly; a string is just an array of characters.",
    what: [
      "An **array** is the most basic way to hold many values: a row of slots laid out **contiguously** in memory — meaning they sit right next to each other, in one unbroken block. Each slot has a number called its **index**, and (here's the magic) indexes start at **0**, so the first item is at index 0, the second at index 1, and so on.",
      "Because the slots are next to each other and all the same size, the computer can jump straight to any one with a single multiplication — ‘start address + index × slot size'. That's why reading `array[500]` takes the same tiny time as reading `array[0]`. We call that **O(1)**, or *constant time*: the cost doesn't grow with the size of the array.",
      "A **string** — a piece of text like `\"burger\"` — is, underneath, just an array where each slot holds one character. That's why you can ask for ‘the 3rd character' instantly, the same way you ask for the 3rd item of any array.",
    ],
    analogy: {
      title: "A row of numbered lockers",
      body: "An array is a corridor of identical lockers, numbered from 0. To open locker 47 you don't walk past the first 46 — you know exactly where it is and go straight there. But the lockers are bolted to the wall: to add a new one *in the middle*, you'd have to unbolt and shift every locker after it down by one. That's the array's deal — instant access, but painful inserts.",
    },
    insideTitle: "What an array gives and costs",
    inside: [
      { name: "Index access — O(1)", desc: "Read or write any slot by its number in one step. The array's superpower." },
      { name: "Insert/delete middle — O(n)", desc: "Everything after the spot must shift over. Slow when the array is big." },
      { name: "Search (unsorted) — O(n)", desc: "To find a value you don't know the position of, you must scan slot by slot." },
      { name: "Dynamic array", desc: "A growable array (`List`, `Vector`, `ArrayList`) that re-allocates a bigger block when full." },
    ],
    how: [
      "When you create an array, the computer reserves one solid block of memory big enough for all the slots. Knowing the block's start address and how big each slot is, it computes any item's location with arithmetic — no searching. That arithmetic is the whole reason index access is instant.",
      "Most real arrays you use are **dynamic arrays**: they start at some size, and when they fill up the language quietly allocates a new, bigger block (often double) and copies everything over. Appending is therefore *usually* O(1), with an occasional expensive copy — which averages out to cheap.",
    ],
    why: [
      "Arrays are the **workhorse** because they're the cheapest possible structure and the friendliest to the hardware. Modern CPUs love contiguous memory — they pull in nearby slots together (a ‘cache line'), so looping over an array is dramatically faster than chasing scattered pointers. For ‘a bunch of things I'll mostly read in order or by position', nothing beats an array.",
      "The trade-off is rigidity: inserting or deleting anywhere but the end is slow because of all the shifting, and a fixed array can't grow. When you need cheap middle-inserts, that's the signal to look at a **linked list** instead.",
    ],
    alternatives: [
      { name: "Linked list", note: "When you insert/remove in the middle a lot. Pays with slow Nth-item access and worse cache behaviour." },
      { name: "Hash table", note: "When you look things up by a key (a name), not a position. Gives up order and contiguity." },
      { name: "Rope / gap buffer", note: "Specialised string structures for huge, heavily-edited text (like a code editor) where plain string edits would be too slow." },
    ],
    whoUses: "Literally everyone, constantly — an array or list is the default container in every language. Game developers lean on them hardest because looping over contiguous memory is the fastest thing a CPU can do; data engineers process columns as giant arrays for the same reason.",
    bigPicture: "Arrays are the substrate other structures are built on: a hash table is an array of buckets, a heap is an array viewed as a tree, a string is an array of characters. Understand arrays and you've understood the foundation the rest stand on.",
    prereqs: ["variables-and-memory", "data-structures-overview"],
    projects: [
      "Reverse a string in place using two indexes walking toward the middle — no second array.",
      "Build a tiny dynamic array: track length vs capacity, and double the capacity (copying over) when it fills.",
    ],
    breaks: "The eternal bug: going one slot too far. An array of length 5 has indexes 0–4; ask for index 5 and you get a crash or garbage (an **off-by-one error**, the most common mistake in programming). The other trap is doing many middle-inserts on a huge array and wondering why it's slow — every insert is quietly shifting thousands of items.",
    scale: "Small arrays: free, use them everywhere. Large arrays (millions of items): still excellent for sequential work and lookups by index, but think twice before middle-inserting. Truly massive data: it moves out of one array and into chunked or columnar layouts (and eventually a database), but the contiguous-memory idea you learn here is exactly what makes those fast too.",
    related: ["data-structures-overview", "linked-lists", "big-o-notation", "sorting-and-searching", "hash-tables"],
  },

  "linked-lists": {
    slug: "linked-lists",
    title: "Linked lists",
    category: "Computer Science",
    color: "purple",
    tagline: "Beads on a string — each item points to the next, so splicing one in is effortless.",
    oneLiner: "A linked list stores items in separate nodes scattered in memory, each holding a value plus a pointer to the next node.",
    what: [
      "A **linked list** is a chain. Each link is called a **node**, and a node holds two things: the **value** you care about, and a **pointer** — the memory address of the next node. (A pointer is just a value that says ‘the next thing is over *there*'.) Follow the pointers from the **head** (the first node) and you walk the whole list.",
      "The crucial difference from an array: the nodes are **not** next to each other in memory. They can be scattered anywhere; the pointers are what hold the order. That single fact flips all the trade-offs. Inserting a new node is cheap — you just rewire two pointers, no shifting. But finding the 500th item is slow, because there's no arithmetic shortcut: you must start at the head and hop, node by node, 500 times.",
      "A **singly** linked list points only forward. A **doubly** linked list adds a pointer backward too, so you can walk either way and remove a node without first finding the one before it.",
    ],
    analogy: {
      title: "A treasure hunt with clues",
      body: "Each clue (a node) tells you a fact and where the *next* clue is hidden. To reach the tenth clue you must follow all nine before it — no skipping ahead. But adding a new clue between two others is trivial: you just rewrite one clue to point at your new one, and your new one to point where that clue used to. No re-hiding everything else. That's a linked list — slow to jump around, effortless to splice.",
    },
    insideTitle: "The pieces",
    inside: [
      { name: "Node", desc: "One link: a value plus a pointer to the next node (and maybe the previous one)." },
      { name: "Head", desc: "A pointer to the first node — your only handle on the whole list." },
      { name: "Insert/delete — O(1)", desc: "Given the spot, rewire a couple of pointers. No shifting. The list's superpower." },
      { name: "Access Nth item — O(n)", desc: "No shortcut: start at the head and walk. The list's weakness." },
    ],
    how: [
      "To insert a node between A and B, you make your new node point to B, then make A point to your new node. Two assignments, done — regardless of how long the list is. To delete a node, you make its predecessor point to its successor, skipping it. The scattered memory and pointers are exactly what make this cheap.",
      "The cost of that flexibility is twofold. First, **no random access** — reaching position N means N hops. Second, **poor cache behaviour**: because nodes are scattered, the CPU can't pull the next one in alongside the current one (the way it can with a contiguous array), so walking a linked list is often slower in practice than walking an array even though both are ‘O(n)'.",
    ],
    why: [
      "Linked lists exist for the case arrays are bad at: **frequent inserts and removals in the middle**, especially when you're already holding a pointer to the spot. They also never need to copy-and-grow the way a dynamic array does, and they're the natural backbone for other structures — stacks, queues, and the buckets inside hash tables are often linked lists.",
      "But for most everyday ‘hold a bunch of things' jobs, a dynamic array quietly wins — better cache behaviour, less memory per item (no pointers to store), and instant index access. Modern advice: reach for an array/list by default, and a linked list only when its specific strength matters.",
    ],
    alternatives: [
      { name: "Dynamic array", note: "The usual default. Better cache use and O(1) index access; pays with O(n) middle-inserts." },
      { name: "Doubly linked list", note: "Adds a backward pointer so you can delete a node and walk in reverse — at the cost of one more pointer per node." },
      { name: "Deque (built-in)", note: "Most languages ship a double-ended queue that gives O(1) push/pop at both ends without you wiring nodes by hand." },
    ],
    whoUses: "It's more often *inside* the tools you use than written by hand: operating-system schedulers chain tasks as linked lists, language runtimes link memory blocks this way, and `LinkedList`/`deque` classes ship in every standard library. Interviewers love it precisely because reversing or detecting a cycle in one proves you truly understand pointers.",
    bigPicture: "Linked lists are where ‘pointers' stop being abstract. Grasp how a node points to the next node and you've grasped the same mechanism that builds trees (nodes pointing to children) and graphs (nodes pointing to neighbours). It's the gateway to every branching structure.",
    prereqs: ["arrays-and-strings", "variables-and-memory"],
    projects: [
      "Build a singly linked list with add, remove, and print; then write a function that reverses it by flipping every pointer.",
      "Detect a loop: given a list that might point back on itself, find out using two pointers moving at different speeds (the ‘tortoise and hare').",
    ],
    breaks: "Pointer bugs are the nightmare. Forget to rewire one link during a delete and you either drop the rest of the list (everything after the deleted node becomes unreachable and is lost) or create a **cycle** where a node points back into the list, sending any loop over it spinning forever. And reaching for a linked list when you actually wanted fast `[i]` access quietly makes everything O(n).",
    scale: "Small: fine, but an array is usually simpler. Large with lots of middle edits: this is its moment. Very large: cache misses from scattered nodes hurt, so high-performance code prefers contiguous layouts or chunked lists. At infrastructure scale the *idea* lives on — linked structures thread through allocators, file systems, and queues everywhere.",
    related: ["arrays-and-strings", "stacks-and-queues", "data-structures-overview", "trees-and-bsts", "big-o-notation"],
  },

  "stacks-and-queues": {
    slug: "stacks-and-queues",
    title: "Stacks & queues",
    category: "Computer Science",
    color: "teal",
    tagline: "Two lists with one rule each about who's next — last-in or first-in — and that rule is everything.",
    oneLiner: "A stack hands back the most recently added item (last-in-first-out); a queue hands back the oldest (first-in-first-out).",
    what: [
      "A **stack** and a **queue** are both just lists of items — what makes them special is a strict rule about *which* item you're allowed to take next. That rule turns out to model an astonishing amount of real software.",
      "A **stack** is **LIFO** — *last in, first out*. You **push** items on the top and **pop** them off the top, so the last thing you added is the first thing you get back. Think of a stack of plates: you take the top one. A **queue** is **FIFO** — *first in, first out*. You **enqueue** at the back and **dequeue** from the front, so items are served in the order they arrived. Think of a checkout line: first to arrive, first to be served.",
      "You don't usually access the middle of either — you only ever touch the one end the rule allows. That restriction is the point: by giving up random access, you get a structure that perfectly captures ‘undo the most recent thing' (stack) or ‘handle things fairly in arrival order' (queue).",
    ],
    analogy: {
      title: "A stack of plates vs a line at the till",
      body: "Plates in a cupboard: you add to the top and take from the top, so the freshly washed plate gets used first (a stack — LIFO). The queue at the supermarket till: you join the back and the person at the front is served next, so whoever waited longest goes first (a queue — FIFO). Same idea — a line of things — but the opposite rule about who's next, and each rule fits a different kind of job.",
    },
    insideTitle: "The two rules and where they live",
    inside: [
      { name: "Stack — LIFO", desc: "Push/pop at one end. Models ‘most recent first': undo, back button, function calls." },
      { name: "Queue — FIFO", desc: "Enqueue at back, dequeue at front. Models ‘fair, in order': print jobs, task lines, requests." },
      { name: "The call stack", desc: "How your program tracks which function is running — a stack the language manages for you." },
      { name: "Deque", desc: "A double-ended queue: add/remove at *both* ends. A flexible superset of both." },
    ],
    how: [
      "Both can be built on an array or a linked list, and both keep every operation at **O(1)** — push, pop, enqueue, dequeue all touch just one end, so there's no shifting or searching. That speed plus simplicity is why they're everywhere.",
      "The most important stack you'll ever meet is the one you don't build: the **call stack**. Every time your code calls a function, the computer *pushes* a frame (that function's local variables and where to return) onto a stack; when the function finishes, it *pops* back to the caller. That's literally how a program remembers where it was — and it's the mechanism that makes **recursion** work.",
    ],
    why: [
      "These exist because order-of-handling is a real, recurring need, and these two rules cover most of it. ‘Undo' is a stack (reverse the most recent action). A web server's incoming requests are a queue (serve them fairly). A maze solver explores with a stack (depth-first) or a queue (breadth-first) — same maze, different rule, different search.",
      "The trade-off is deliberate poverty: you can't peek in the middle or grab an arbitrary item. If you need that, you've outgrown a stack/queue and want a different structure. Their *whole value* is the discipline of the single allowed end.",
    ],
    alternatives: [
      { name: "Priority queue (heap)", note: "When ‘who's next' isn't oldest or newest but *most important*. A queue that serves by priority, not arrival." },
      { name: "Deque", note: "When you need both ends. Built-in in most languages; can act as either a stack or a queue." },
      { name: "Plain array/list", note: "When you actually need to read the middle or jump around — then the stack/queue restriction is just in your way." },
    ],
    whoUses: "Compiler and language authors (the call stack, expression parsing), browser engineers (the back/forward history is two stacks), and backend teams everywhere (request queues, job queues). Any ‘undo' feature in any app is a stack; any ‘process these in order' system is a queue.",
    bigPicture: "Queues scale up into one of the biggest ideas in backend systems — the **message queue** — where slow work is handed to a line of background jobs so the user doesn't wait. And the call stack underpins recursion. So these two humble structures are the seed of both system architecture and a whole style of algorithm.",
    prereqs: ["arrays-and-strings", "linked-lists"],
    projects: [
      "Use a stack to check whether brackets in a string are balanced — `([])` is valid, `([)]` is not.",
      "Use a queue to simulate a print spooler: jobs arrive, are served oldest-first, and you log the order they print.",
    ],
    breaks: "Pop from an empty stack or dequeue an empty queue and you get a crash or nonsense if you didn't check first. The famous one is the **stack overflow**: a recursion that never stops keeps pushing call frames until the call stack runs out of room and the program dies — the call stack is finite, and forgetting that is a rite of passage.",
    scale: "In-memory: trivially fast at any size that fits in RAM. As a system grows, the *queue* idea graduates to durable, distributed message queues (Kafka, SQS) that hold millions of jobs across machines and survive crashes — but the FIFO promise you learn here is exactly what they're keeping. Stacks stay mostly a local, in-process tool.",
    related: ["linked-lists", "recursion-and-backtracking", "heaps-priority-queues", "message-queues", "graphs"],
  },

  "hash-tables": {
    slug: "hash-tables",
    title: "Hash tables & maps",
    category: "Computer Science",
    color: "amber",
    tagline: "Look something up by name in one step — the closest thing in computing to instant magic.",
    oneLiner: "A hash table stores key–value pairs and finds any value by its key in roughly one step, by turning the key into an array position with a hash function.",
    what: [
      "A **hash table** (you'll also hear **map**, **dictionary**, or **hash map** — same thing) stores pairs: a **key** and its **value**. Give it the key ‘`user_42`' and it hands back that user's record — *without searching*. That near-instant lookup-by-name is its whole reason to exist, and it's one of the most useful structures in all of computing.",
      "The trick is the **hash function**: a little routine that takes your key and scrambles it into a number — an index into an internal array of **buckets**. Store ‘`user_42` → record' and the hash function decides ‘that lives in bucket 9'. Later, to look it up, it runs the *same* key through the *same* hash function, gets bucket 9 again, and grabs the value. No scanning — it computed exactly where to look. That's **O(1) average** time: constant, no matter how many items you've stored.",
      "Sometimes two different keys hash to the *same* bucket — that's a **collision**. It's expected and handled: typically the bucket holds a tiny list, and the table checks the few keys there. Done well, collisions stay rare, so lookups stay effectively one step.",
    ],
    analogy: {
      title: "A coat check with a clever numbering rule",
      body: "At a coat check, instead of searching every hook for your coat, the attendant computes your hook number from your name using a fixed rule, and hangs it there. When you return, they run your name through the same rule, get the same number, and walk straight to your coat. If two names happen to map to the same hook (a collision), a couple of coats share it and they glance at the tags. That ‘compute the spot from the name' rule is a hash function.",
    },
    insideTitle: "The pieces",
    inside: [
      { name: "Key & value", desc: "You store and fetch the value *by* its key. The key is your handle on the data." },
      { name: "Hash function", desc: "Turns a key into a bucket number, fast and consistently. The heart of the structure." },
      { name: "Buckets", desc: "Slots in an internal array where pairs land. Ideally one or two items each." },
      { name: "Collision handling", desc: "What to do when two keys share a bucket — keep a small list there, or probe nearby." },
    ],
    how: [
      "On insert, the table hashes the key to a bucket and stores the pair there (appending to a short list if something's already in that bucket). On lookup, it hashes the same key, jumps to that bucket, and checks the handful of keys present to find the exact match. Because a good hash spreads keys evenly, buckets stay tiny and both operations stay near O(1).",
      "As the table fills, buckets start sharing too many keys and lookups slow down. So the table watches its **load factor** (items ÷ buckets) and, past a threshold, **resizes**: it allocates a bigger bucket array and re-hashes everything into it. That occasional resize is expensive, but it's rare, so the *average* cost per operation stays constant.",
    ],
    why: [
      "Hash tables are the go-to whenever you need ‘fetch the thing associated with *this* key, fast' — counting how many times each word appears, remembering which ids you've already seen, caching computed answers, or de-duplicating a list. They routinely turn an O(n) scan into an O(1) lookup, which is the single most common performance win a programmer reaches for.",
      "The cost of that speed: a hash table has **no order**. It can't tell you the smallest key, or everything between two keys, or what comes ‘next' — the hashing deliberately scatters keys. When you need order or range queries, that's exactly when you reach for a **tree** instead.",
    ],
    alternatives: [
      { name: "Balanced tree (BST)", note: "When you need keys kept in sorted order or range queries. O(log n) lookups instead of O(1), but ordered." },
      { name: "Array", note: "When your ‘key' is already a small integer position. Then a plain array *is* a perfect O(1) map." },
      { name: "Trie", note: "For string keys where you also want prefix search (autocomplete). Specialised, but powerful for text." },
    ],
    whoUses: "Everyone, everywhere — it's arguably the most-used non-trivial structure in software. Language runtimes use it for objects (a JavaScript object *is* a hash map); databases use it for in-memory indexes and joins; caches like Redis are giant hash tables; compilers track variable names in one. Interviewers expect you to *reach for it instinctively* the moment a problem says ‘seen before?' or ‘count each'.",
    bigPicture: "The hash table is the structure behind ‘instant lookup' everywhere you've felt it: a cache serving a page from memory, a database joining two tables, a session store finding who you are from a token. It also scales out — spread the buckets across machines and you get a **distributed hash table**, the backbone of systems like Cassandra and sharded databases.",
    prereqs: ["arrays-and-strings", "data-structures-overview", "big-o-notation"],
    projects: [
      "Count word frequencies in a paragraph using a map; print the top five.",
      "Build a toy hash table over a fixed array of buckets: write a simple hash function, handle collisions with a list per bucket, and support put/get.",
    ],
    breaks: "A bad hash function that piles most keys into a few buckets degrades the whole table to a linear scan — O(1) quietly becomes O(n) and nobody notices until it's slow. Worse, an attacker who knows your hash can *deliberately* cause collisions to grind your server to a halt (a real denial-of-service attack). And reaching for a hash table when you actually needed sorted order means re-sorting the keys every single time — the wrong tool fighting you.",
    scale: "In memory: superb up to whatever fits in RAM. Bigger: the table resizes itself; the only cost is the occasional rehash. Beyond one machine: keys are partitioned across servers by hash (a distributed hash table / consistent hashing), which is precisely how **sharding** decides which database holds which user. The same idea you learn here scales from a 10-line script to a planet-spanning store.",
    related: ["arrays-and-strings", "trees-and-bsts", "caching", "sharding", "big-o-notation"],
  },

  "trees-and-bsts": {
    slug: "trees-and-bsts",
    title: "Trees & binary search trees",
    category: "Computer Science",
    color: "teal",
    tagline: "Branching structures for anything with a hierarchy — and, kept sorted, for halving a search at every step.",
    oneLiner: "A tree links nodes in a parent-child hierarchy; a binary search tree keeps them ordered so you can find any value by repeatedly halving the search.",
    what: [
      "A **tree** is a structure of **nodes** connected in a hierarchy: one **root** node at the top, each node pointing to its **children** below, branching downward with no loops. A node with no children is a **leaf**. Trees are how computers model anything nested — a file system (folders inside folders), a web page (tags inside tags), a company org chart, a comment thread.",
      "A **binary search tree** (BST) is a special, *ordered* tree where each node has at most two children and obeys one rule: everything in the **left** subtree is smaller than the node, and everything in the **right** is larger. That single rule turns the tree into a searching machine. To find a value, you start at the root and compare: smaller? go left. Larger? go right. Each step throws away **half** the remaining tree.",
      "Halving at every step is what makes a BST fast: searching a million sorted items takes about 20 comparisons, not a million. That ‘halve each time' cost is called **O(log n)** — logarithmic time — and it's the sweet spot between the instant-but-unordered hash table and the slow linear scan.",
    ],
    analogy: {
      title: "Finding a word in a dictionary",
      body: "You don't read a dictionary page by page to find ‘mustard'. You open near the middle, see you're at ‘M' already, and narrow from there — each glance cuts the remaining pages roughly in half. A binary search tree works exactly like that: every comparison tells you which half to keep and which to discard, so even a huge collection is searched in a handful of steps. The ordering is what makes the shortcut possible.",
    },
    insideTitle: "The vocabulary",
    inside: [
      { name: "Root, child, leaf", desc: "Top node, the nodes hanging off it, and the nodes with nothing below them." },
      { name: "The BST rule", desc: "Left subtree < node < right subtree. This ordering is what enables fast search." },
      { name: "Height & balance", desc: "How many levels deep. A *balanced* tree stays shallow, which keeps search at O(log n)." },
      { name: "Self-balancing trees", desc: "Red-black & AVL trees re-shuffle on insert so the tree never degenerates into a slow line." },
    ],
    how: [
      "Search, insert, and delete all follow the same path: start at the root and go left or right by comparing, until you find the value or the spot for it. On a **balanced** tree — one that stays nice and bushy — that path is about log n steps, so all three operations are O(log n).",
      "The catch: a plain BST can go **lopsided**. Insert values that are already in order (1, 2, 3, 4…) and each one hangs off the last, so the ‘tree' degenerates into a straight line — really a linked list — and search slumps back to O(n). The fix is a **self-balancing** tree (red-black or AVL), which does a little extra rearranging on every insert to guarantee it stays shallow. The maps and sets in many languages are exactly these under the hood.",
    ],
    why: [
      "Trees exist for two big reasons. First, **hierarchy is everywhere** — folders, the DOM, menus, org charts — and a tree is its natural shape. Second, a balanced BST gives you something a hash table can't: **sorted order with fast lookup**. You can ask for the smallest key, everything between two values, or the next-largest — *range queries* — while still finding any single item in O(log n).",
      "The trade-off versus a hash table is one step slower for a plain lookup (log n vs constant), in exchange for keeping everything ordered. That ordering is so valuable that the most important tree of all — the **B-tree** — is what every database uses for its indexes, because ‘find this row fast' and ‘give me all rows between two dates' both fall out of it.",
    ],
    alternatives: [
      { name: "Hash table", note: "Faster for a single lookup (O(1)) but unordered. Pick the tree when you need sorting or ranges." },
      { name: "B-tree / B+ tree", note: "A wide, shallow tree tuned for disk — the structure behind virtually every database index." },
      { name: "Trie", note: "A tree keyed by the characters of strings — ideal for prefix search and autocomplete." },
    ],
    whoUses: "Database engineers (every index is a B-tree), browser and compiler authors (the page and your code are parsed into trees), and file-system designers. The moment a problem involves hierarchy or ‘keep it sorted while I keep inserting', a tree is the answer — which is why interview questions on tree traversal are unavoidable.",
    bigPicture: "Trees are the bridge between data structures and the systems you've already learned. The B-tree index is *why* a database can find one row among millions instantly; the DOM tree is what React diffs to update a page; a router matches URLs by walking a tree. Master tree traversal and a huge amount of ‘how does that work?' suddenly clicks.",
    prereqs: ["linked-lists", "recursion-and-backtracking", "big-o-notation"],
    projects: [
      "Build a BST with insert and search; then print every value in sorted order with an in-order traversal (left, self, right).",
      "Write a function that finds the height of a tree and tells you whether it's balanced — a great first taste of recursion on trees.",
    ],
    breaks: "Insert already-sorted data into a plain BST and it silently degenerates into a slow line — your O(log n) lookups become O(n) and you won't see why until it's slow at scale. That exact failure is the reason self-balancing trees exist. Traversal bugs bite too: get the recursion wrong and you visit nodes twice, skip a subtree, or loop forever.",
    scale: "Small: any tree works. Large in memory: use a self-balancing BST so it never degenerates. Data too big for memory: that's where **B-trees** shine — wide and shallow to minimise slow disk reads, which is exactly how databases index billions of rows. Planet-scale: those B-tree indexes get replicated and sharded, but the halving-the-search idea you learn here is still doing the work.",
    related: ["linked-lists", "hash-tables", "graphs", "recursion-and-backtracking", "sql"],
  },

  graphs: {
    slug: "graphs",
    title: "Graphs",
    category: "Computer Science",
    color: "purple",
    tagline: "Dots joined by lines — the structure for anything where ‘things are connected to things'.",
    oneLiner: "A graph is a set of nodes connected by edges; it models networks — friends, roads, dependencies — and you explore it with BFS or DFS.",
    what: [
      "A **graph** is the most general structure of all: a set of **nodes** (also called *vertices* — the dots) joined by **edges** (the lines between them). Unlike a tree, there's no root and no rule against loops — any node can connect to any other. That freedom is exactly what lets a graph model the messy, interconnected real world.",
      "Edges can be **undirected** (a two-way friendship: if A knows B, B knows A) or **directed** (a one-way link: A follows B, but not back). They can also be **weighted** — carrying a number like distance, cost, or time (the 12 km between two towns). Pick those options and a graph can represent a social network, a road map, the web's links, task dependencies, or which airports connect to which.",
      "Because a graph has no fixed starting point or shape, the fundamental operation is **traversal** — systematically visiting nodes by following edges. The two classic ways are **BFS** (breadth-first: explore everything one step away, then two steps, like ripples) and **DFS** (depth-first: charge as far down one path as you can, then back up and try another).",
    ],
    analogy: {
      title: "A map of cities and roads",
      body: "Cities are nodes; the roads between them are edges; the distance on each road is the weight. ‘Can I get from here to there?' is asking if a path exists. ‘What's the shortest drive?' is a weighted shortest-path question. Exploring all nearby cities before far ones is breadth-first (BFS); driving as far down one highway as you can before backtracking is depth-first (DFS). Every map app you've used is solving graph problems.",
    },
    insideTitle: "The pieces",
    inside: [
      { name: "Nodes & edges", desc: "The dots and the connections between them. The two raw ingredients." },
      { name: "Directed / weighted", desc: "Are links one-way or two-way? Do they carry a cost (distance, time)? These choices model reality." },
      { name: "BFS — breadth-first", desc: "Explore in rings, nearest first. Uses a queue. Finds the fewest-hops path." },
      { name: "DFS — depth-first", desc: "Follow one path to its end, then backtrack. Uses a stack (or recursion). Great for ‘is there a path?' and cycles." },
    ],
    how: [
      "A graph is usually stored one of two ways. An **adjacency list** keeps, for each node, a list of its neighbours — compact and ideal when edges are relatively few (most real networks). An **adjacency matrix** is a grid where cell [A][B] says whether A connects to B — simple, but uses space for every *possible* edge, so it's only good for small or dense graphs.",
      "**BFS** uses a **queue**: visit a node, add all its unvisited neighbours to the back of the line, repeat. Because it expands outward evenly, it finds the path with the fewest edges. **DFS** uses a **stack** (often via recursion): go to a neighbour, then *its* neighbour, plunging deep before backing up. Both keep a ‘visited' set so they don't loop forever on cycles. From these two, richer algorithms grow — like **Dijkstra's** for the cheapest weighted path (a BFS that always expands the lowest-cost frontier next, using a priority queue).",
    ],
    why: [
      "Graphs exist because *connection* is one of the most common things we model, and trees and lists are too rigid for it. Anything shaped like a network — friends, followers, roads, flights, web links, ‘which task must finish before which' — is a graph, and the questions you ask (is there a path? what's the shortest one? who's most central? is there a cycle?) are graph algorithms.",
      "The trade-off is that graphs are heavier to reason about than their simpler cousins. There's no neat ordering to exploit, traversals must guard against cycles, and the richest questions (shortest path, best matching) get genuinely intricate. You take on that complexity precisely when the problem really is a network and nothing simpler will capture it.",
    ],
    alternatives: [
      { name: "Tree", note: "A graph with no cycles and a single root. Simpler — use it when your data is a clean hierarchy, not a web." },
      { name: "Adjacency list vs matrix", note: "List for sparse graphs (few edges), matrix for small/dense ones. The storage choice changes performance." },
      { name: "Graph database", note: "Neo4j and friends store relationships as first-class data — when connections, not rows, are the whole point." },
    ],
    whoUses: "Social networks (Facebook's friend graph, LinkedIn's ‘degrees of connection'), maps and logistics (Google Maps, Uber routing, delivery planning), search engines (PageRank ranks web pages by the link graph), and build tools (a dependency graph decides what to compile first). Graph questions are a staple of senior interviews because so many hard real problems are secretly graphs.",
    bigPicture: "Graphs connect to almost everything else: a dependency graph is how a build system or package manager decides order; the ‘blast radius' of a failing service is a graph traversal; even a neural network is a weighted graph of connections. Once you can model a problem as nodes-and-edges and pick BFS or DFS, a whole class of ‘how would I even start?' problems opens up.",
    prereqs: ["trees-and-bsts", "stacks-and-queues", "hash-tables"],
    projects: [
      "Model a tiny social network as an adjacency list and answer ‘are these two people connected?' with BFS.",
      "Find the shortest number of hops between two nodes (unweighted) with BFS — then sketch how you'd add weights for Dijkstra's.",
    ],
    breaks: "Forget the ‘visited' set and a traversal walks in circles forever on a cycle — the program hangs, never finishing. Choose the wrong storage (a matrix for a huge, sparse social graph) and you blow up memory. And reaching for a heavy graph algorithm when the data was really a simple tree or list just buries a simple problem under needless complexity.",
    scale: "Small graphs: traverse freely in memory. Large (millions of nodes): the algorithm and storage choice decide whether it finishes in milliseconds or never — adjacency lists and good pruning matter. Planet-scale graphs (a global social network): they're partitioned across thousands of machines, traversed with distributed and approximate algorithms, and often kept in dedicated graph databases. The nodes-and-edges idea is the same; the engineering to traverse billions of them is immense.",
    related: ["trees-and-bsts", "stacks-and-queues", "heaps-priority-queues", "hash-tables", "data-structures-overview"],
  },

  "heaps-priority-queues": {
    slug: "heaps-priority-queues",
    title: "Heaps & priority queues",
    category: "Computer Science",
    color: "amber",
    tagline: "A line where the most urgent item always jumps to the front — and getting it is instant.",
    oneLiner: "A heap is a tree that always keeps its smallest (or largest) item at the top, giving you instant access to the most extreme element.",
    what: [
      "A **priority queue** is like an ordinary queue, but instead of serving items by arrival order, it always serves the **most important** one next — the ambulance jumps the traffic. You put items in (each with a priority), and every time you take one out, you get the current highest priority. The structure that makes this efficient is the **heap**.",
      "A **heap** is a special tree with one simple promise, the **heap property**: every parent is smaller than its children (a **min-heap**) — or larger (a **max-heap**). That promise means the smallest (or largest) item is *always sitting at the root*, so peeking at the most extreme element is instant, **O(1)**. Adding an item or removing the top costs only **O(log n)** — the height of the tree.",
      "Cleverly, a heap doesn't need real tree nodes and pointers. Because it's always a neat, filled-in shape (a *complete* tree), it's stored as a plain **array**, with simple arithmetic to find a node's children and parent. So you get tree-like behaviour with array-like efficiency and no pointer bookkeeping.",
    ],
    analogy: {
      title: "A hospital emergency room",
      body: "Patients don't get seen first-come-first-served — they're triaged by urgency, so the most critical case is always next, no matter who walked in when. A new arrival is slotted into the right place in the priority order; when a doctor frees up, the most urgent patient is taken instantly. That's a priority queue, and the heap is the efficient triage system underneath that keeps ‘who's most urgent' always ready at the top.",
    },
    insideTitle: "The pieces",
    inside: [
      { name: "Heap property", desc: "Every parent beats its children (smaller for min-heap, larger for max-heap). Keeps the extreme at the root." },
      { name: "Peek — O(1)", desc: "The min (or max) is always the root, so reading it is instant." },
      { name: "Insert & pop — O(log n)", desc: "Add or remove the top, then ‘bubble' the heap back into shape — only as far as the tree is tall." },
      { name: "Array-backed", desc: "Stored as a flat array (no pointers); children of index i sit at 2i+1 and 2i+2." },
    ],
    how: [
      "To **insert**, you drop the new item at the end of the array and let it *bubble up*: keep swapping it with its parent while it's smaller (in a min-heap) than that parent. It rises only until the heap property holds — at most the height of the tree, so O(log n). To **remove the top**, you take the root (your answer), move the last item into the root's spot, and let it *sink down*, swapping with its smaller child until order is restored — again O(log n).",
      "Those two operations are all a heap really is. A built-in priority queue in your language wraps exactly this. And it gives a neat sorting algorithm for free — **heapsort**: push everything into a heap, then pop the top repeatedly and you get the items out in sorted order.",
    ],
    why: [
      "Heaps exist for the surprisingly common need: *‘give me the most extreme item right now, and keep that true as items come and go.'* A plain sorted list could answer ‘what's the smallest?' but every insert would cost O(n) to keep it sorted; a heap keeps inserts at O(log n) while still surfacing the extreme instantly. That balance is why it's the standard tool for ‘top-K', schedulers, and shortest-path search.",
      "The trade-off: a heap only ever tells you about the *one* extreme. It is **not** fully sorted — the items below the root are in a loose, partial order, so you can't ask ‘what's the 5th smallest?' or list everything in order without popping. If you need full ordering or range queries, you want a sorted structure or a tree instead.",
    ],
    alternatives: [
      { name: "Sorted array/list", note: "Always fully ordered and O(1) to read the min — but O(n) to insert. Good when inserts are rare." },
      { name: "Balanced BST", note: "Gives the min/max *and* full ordering and ranges, at O(log n) — more power, slightly more overhead." },
      { name: "Plain queue", note: "When ‘next' really is just oldest-first and priority doesn't matter, skip the heap entirely." },
    ],
    whoUses: "Operating-system schedulers (run the highest-priority process next), network routers, and any system doing **Dijkstra's shortest path** (a graph search powered by a priority queue) — so every maps and routing team. ‘Find the top K' problems (top 10 trending, K closest points) are heap problems, and they're an interview favourite for exactly that reason.",
    bigPicture: "The heap is the engine inside two things you've already met: it powers **Dijkstra's algorithm** for shortest paths on a weighted **graph**, and it's how a priority **queue** serves urgent work first in a backend job system. It's a small structure with outsized reach — wherever ‘most important next' matters, a heap is usually doing the work.",
    prereqs: ["trees-and-bsts", "arrays-and-strings", "stacks-and-queues"],
    projects: [
      "Use your language's priority queue to find the K largest numbers in a big list without sorting the whole thing.",
      "Implement a min-heap on an array: write `insert` (bubble up) and `popMin` (sink down), then build heapsort on top.",
    ],
    breaks: "Treat a heap as if it were fully sorted and you'll get nonsense — only the root is guaranteed; the rest is partially ordered, so iterating the array is *not* iterating in order. Mix up a min-heap and a max-heap and your ‘most urgent' becomes your least urgent. And forgetting that the heap only exposes the top leads people to rebuild or re-sort it constantly, throwing away the very efficiency they came for.",
    scale: "In memory: excellent into the millions for ‘top-K' and scheduling. Bigger than memory or across machines: the *idea* persists in distributed schedulers and priority job queues, though keeping a single global priority order across many servers gets genuinely hard (and is often relaxed to ‘roughly prioritised'). The core bubble-up/sink-down logic, though, is exactly what you learn here.",
    related: ["stacks-and-queues", "trees-and-bsts", "graphs", "sorting-and-searching", "message-queues"],
  },

  "recursion-and-backtracking": {
    slug: "recursion-and-backtracking",
    title: "Recursion & backtracking",
    category: "Computer Science",
    color: "purple",
    tagline: "A function that calls itself to solve a smaller version of its own problem — until the problem is trivial.",
    oneLiner: "Recursion solves a problem by calling itself on a smaller piece and combining the results; backtracking adds ‘try a choice, and undo it if it fails'.",
    what: [
      "**Recursion** is a function that calls **itself**. It sounds circular, but it works because each call tackles a *smaller* version of the same problem, and there's a **base case** — a smallest version simple enough to answer directly, with no further calls. Reach the base case and the chain of calls unwinds, combining results back up to the original question.",
      "Every correct recursion has two parts. The **base case**: ‘if the problem is trivial, here's the answer outright' (an empty list sums to 0; a folder with no subfolders has only its own files). The **recursive case**: ‘otherwise, solve a smaller piece by calling myself, and build my answer from that' (the sum of a list is its first item plus *the sum of the rest*). Get the base case wrong and the function never stops.",
      "**Backtracking** is recursion with choices and an eraser. At each step you *try* an option, recurse to see if it leads to a solution, and if it hits a dead end you **undo** that choice and try the next. It's how you explore every possibility methodically — solving a maze, a Sudoku, or arranging items — without getting lost: go forward while you can, step back the moment you're stuck.",
    ],
    analogy: {
      title: "Russian nesting dolls",
      body: "To ‘open' a nesting doll, you open it and then do the exact same thing to the smaller doll inside — the same action on a smaller version — until you reach the tiniest solid doll that doesn't open (the base case). Then you're done. Backtracking is like exploring a hedge maze: at each junction you pick a path; if it dead-ends, you walk back to the last junction (undo) and take a different one. Try, recurse, and step back when stuck.",
    },
    insideTitle: "The pieces",
    inside: [
      { name: "Base case", desc: "The smallest problem you answer directly, with no further recursion. Without it, infinite calls." },
      { name: "Recursive case", desc: "Solve a smaller sub-problem by calling yourself, then build your answer from it." },
      { name: "The call stack", desc: "Each call is a frame pushed on the stack; reaching the base case pops back up. This *is* the mechanism." },
      { name: "Backtracking", desc: "Make a choice, recurse, and undo it if it leads to a dead end — exploring all options safely." },
    ],
    how: [
      "Recursion runs on the **call stack** (the same stack from stacks & queues). Each time the function calls itself, the computer *pushes* a new frame — that call's own variables and where to return — onto the stack. The calls pile up until one hits the base case and returns; then frames *pop* off one by one, each using the result from the call below it. The stack is the program's memory of ‘where was I, and what's left to combine'.",
      "Backtracking layers a pattern on top: at each node of the search, loop over the available choices — for each, *apply* it, recurse, and then *un-apply* it (restore the previous state) before trying the next. That undo step is what keeps the exploration clean, so by the time the recursion finishes it has effectively tried every valid combination without ever getting tangled.",
    ],
    why: [
      "Recursion is the natural language for anything **self-similar** — a structure made of smaller copies of itself. Trees, nested folders, parsing nested brackets, divide-and-conquer algorithms like merge sort: writing these recursively is often *dramatically* shorter and clearer than the loop-based equivalent, because the code mirrors the shape of the data.",
      "The trade-off is real, though. Every call costs a stack frame, so recursion uses more memory than a loop and can **overflow the stack** if it goes too deep. Anything recursive can be rewritten with a loop and an explicit stack — sometimes you should, for speed or depth. Recursion is a tool for clarity on self-similar problems, not a hammer for everything.",
    ],
    alternatives: [
      { name: "Iteration (loops)", note: "Often faster and won't overflow the stack. Preferred for simple repetition; clunky for deeply nested structures." },
      { name: "Explicit stack", note: "Rewrite a recursion as a loop that manages its own stack — the depth safety of iteration with recursion's reach." },
      { name: "Memoised recursion", note: "Cache results of repeated sub-calls — the doorway to **dynamic programming**, turning exponential into fast." },
    ],
    whoUses: "Compiler and interpreter authors (parsing nested code is inherently recursive), anyone working with trees or file systems, and graphics programmers (fractals, scene graphs). It's a staple of technical interviews because a clean recursive solution signals you can spot self-similar structure — and backtracking questions (permutations, N-Queens, Sudoku) test whether you can explore a space without getting lost.",
    bigPicture: "Recursion is the engine under several things you've learned: **DFS** on a graph is recursion, traversing a **tree** is recursion, and **divide-and-conquer** sorts split-recurse-combine. Add caching to recursion and you get **dynamic programming**. So this isn't one technique — it's a way of thinking that unlocks trees, graphs, and a whole class of optimisation problems.",
    prereqs: ["stacks-and-queues", "what-is-a-program", "trees-and-bsts"],
    projects: [
      "Compute a factorial and the Fibonacci numbers recursively — then watch Fibonacci get slow, and see why memoisation fixes it.",
      "Solve a small maze (or generate all permutations of a word) with backtracking: choose, recurse, undo.",
    ],
    breaks: "Forget or botch the base case and the function calls itself forever, piling frames onto the call stack until it runs out of room — the dreaded **stack overflow**, and your program dies. Recurse too deep on big input (a 100,000-level structure) and you overflow even *with* a correct base case. And naive recursion that re-solves the same sub-problem millions of times (plain Fibonacci) can be astronomically slow — the cue to add memoisation.",
    scale: "Fine for modest depth. Deep recursion needs care: convert to iteration with an explicit stack, or use ‘tail-call' tricks where the language supports them, to avoid blowing the stack. At large scale the recursive *idea* — divide a problem into smaller identical pieces — is exactly how big distributed jobs split work (map-reduce is divide-and-conquer across machines), even when no single function literally calls itself.",
    related: ["stacks-and-queues", "trees-and-bsts", "graphs", "dynamic-programming", "sorting-and-searching"],
  },

  "dynamic-programming": {
    slug: "dynamic-programming",
    title: "Dynamic programming",
    category: "Computer Science",
    color: "pink",
    tagline: "Solve each little sub-problem once, write the answer down, and never compute it twice.",
    oneLiner: "Dynamic programming speeds up problems that re-solve the same sub-problems by storing each answer the first time and reusing it.",
    what: [
      "**Dynamic programming** (DP) has an intimidating name and a simple core: *don't solve the same thing twice*. It applies to problems that, when you break them down, keep bumping into the **same smaller sub-problems** over and over. DP solves each sub-problem once, stores the answer, and looks it up instead of recomputing — turning work that explodes exponentially into something fast.",
      "Two ingredients tell you DP fits. **Overlapping sub-problems**: the naive (usually recursive) solution computes the same sub-answers again and again — classic Fibonacci recomputes `fib(5)` a staggering number of times. **Optimal substructure**: the best answer to the whole is built from the best answers to its parts (the cheapest route through a grid is built from the cheapest routes to the cells before it). When both hold, DP is the tool.",
      "There are two styles. **Memoisation** (top-down): write the natural recursion, but cache each result in a table the first time you compute it, and return the cache on repeat calls. **Tabulation** (bottom-up): fill a table starting from the smallest sub-problems and build up to the answer with a loop. Same idea — compute each cell once — from opposite directions.",
    ],
    analogy: {
      title: "Doing a jigsaw with a photo of finished corners",
      body: "Imagine a giant jigsaw where the same little clusters of pieces appear in many places. The slow way: reassemble each cluster from scratch every time you meet it. The DP way: the first time you solve a cluster, you photograph it and pin the photo to the board — next time you see that cluster, you just copy the photo instead of redoing the work. You solve each unique cluster exactly once. That ‘solve once, reuse forever' is the whole trick.",
    },
    insideTitle: "The pieces",
    inside: [
      { name: "Overlapping sub-problems", desc: "The same smaller problems recur many times — the signal that caching will pay off hugely." },
      { name: "Optimal substructure", desc: "The best whole-answer is built from best sub-answers. Lets you combine pieces correctly." },
      { name: "Memoisation (top-down)", desc: "Keep the recursion, but store each result in a table and reuse it on repeat calls." },
      { name: "Tabulation (bottom-up)", desc: "Fill a table from smallest sub-problem upward with a loop — no recursion, no stack risk." },
    ],
    how: [
      "Start from the slow recursion. Notice it re-asks the same sub-questions, then add a **table** (an array or map) keyed by the sub-problem. Before computing, check the table; if the answer's there, return it; otherwise compute, *store it*, and return. That one change collapses the work from exponential (re-deriving everything) to linear-ish (each distinct sub-problem solved once). It's caching, applied inside an algorithm.",
      "Tabulation flips the direction: instead of recursing down and caching on the way back, you figure out the order of sub-problems from smallest to largest and fill the table forward with loops. It avoids recursion's stack-depth risk and is often a touch faster, at the cost of having to reason out the right fill order yourself.",
    ],
    why: [
      "DP exists to rescue problems that are *correct* but hopelessly *slow* when solved naively. Many optimisation questions — shortest paths, ‘fewest coins to make this amount', ‘longest common subsequence' between two texts, knapsack-style ‘best value under a limit' — have a clean recursive definition that, run literally, would take longer than the age of the universe because it redoes the same work astronomically often. DP makes them run in milliseconds.",
      "The trade-off is **memory** and **insight**. You spend extra space on the table of stored answers (sometimes reducible with cleverness), and — the real cost — DP is *hard to see*. Recognising that a problem has overlapping sub-problems, and defining the sub-problem and its combining rule correctly, is a genuine skill that takes practice. It is famously the most feared topic in coding interviews for exactly this reason.",
    ],
    alternatives: [
      { name: "Plain recursion", note: "Simpler to write, but recomputes everything — fine only when sub-problems *don't* overlap." },
      { name: "Greedy algorithm", note: "Make the locally best choice each step. Faster and simpler when it works — but it doesn't always give the true optimum; DP does." },
      { name: "Memoisation vs tabulation", note: "Two ways to do DP itself: top-down caching (easier to write) vs bottom-up table (no stack risk, often faster)." },
    ],
    whoUses: "It powers things you use daily: ‘diff' tools and version control compute the longest common subsequence; spell-checkers and DNA alignment use edit distance; routing and scheduling optimisers lean on it. In hiring, DP is the high-difficulty tier at companies like Google and Meta — clearing a hard DP question is often the signal that separates strong candidates.",
    bigPicture: "DP is recursion plus the caching idea you met in systems, fused into one technique — it's literally ‘memoise the recursion'. It connects to graphs (shortest-path algorithms are DP over a graph) and to the broader engineering instinct of ‘compute expensive things once and reuse'. Seeing DP is largely about seeing repeated work and refusing to do it twice.",
    prereqs: ["recursion-and-backtracking", "arrays-and-strings", "big-o-notation"],
    projects: [
      "Make Fibonacci fast: write it recursively, add a memo table, and watch it go from sluggish to instant on large inputs.",
      "Solve the ‘fewest coins to make N' problem with a bottom-up table, then trace which coins the table chose.",
    ],
    breaks: "Apply DP where sub-problems *don't* actually overlap and you've added a useless table — extra memory for nothing. Define the sub-problem wrong and the table gives confidently incorrect answers that are painful to debug. And forgetting the cache (writing the recursion but never storing results) leaves you with the original exponential blow-up — the slow version wearing DP's clothes.",
    scale: "Single machine: a well-built DP solves inputs that would otherwise be impossible. As inputs grow, the table itself can get huge, so engineers shrink it (keeping only the last row, say) or switch to streaming. At very large scale the principle — *don't recompute; remember* — reappears as caching layers and precomputed results across a whole system, the same instinct you learned here applied to infrastructure.",
    related: ["recursion-and-backtracking", "caching", "sorting-and-searching", "graphs", "big-o-notation"],
  },

  "sorting-and-searching": {
    slug: "sorting-and-searching",
    title: "Sorting & searching",
    category: "Computer Science",
    color: "blue",
    tagline: "Put things in order, then find any of them in a handful of steps — the two oldest tricks in the book, still everywhere.",
    oneLiner: "Sorting arranges data in order (usually O(n log n)); once sorted, binary search finds any item by repeatedly halving the data (O(log n)).",
    what: [
      "**Sorting** is arranging items into order — numbers ascending, names alphabetical, orders by date. It's one of the most common operations in all of software, and how you do it matters enormously at scale. **Searching** is finding a particular item, and the two are deeply linked: sorting is often worth doing *because* it makes searching dramatically faster.",
      "The headline searching trick is **binary search**. On a **sorted** array, you check the middle item: too big? the answer's in the left half. Too small? the right half. Either way you discard *half* the remaining items in one comparison, so even a million items take about 20 checks. That's **O(log n)** — logarithmic time. The catch is non-negotiable: the data **must be sorted** first, or binary search gives wrong answers.",
      "Good sorting algorithms — **merge sort**, **quicksort**, **heapsort** — run in **O(n log n)** time, which is provably about the best any comparison-based sort can do. They beat the naive ‘compare every pair' sorts (bubble, insertion, selection) that run in **O(n²)** and become unusable on large data. The ones in your language's standard library are tuned hybrids of these fast algorithms.",
    ],
    analogy: {
      title: "A phone book, then guessing a number",
      body: "A phone book is sorted by name — that's what makes it usable; an unsorted one would be hopeless. To find ‘Patel', you open near the middle, see you're too far, and halve again and again — that's binary search, and it's why a thick book takes only a few flips. The party game ‘guess my number between 1 and 100' is the same: always guess the middle and you corner any number in about seven guesses. Sorting first is what buys you the shortcut.",
    },
    insideTitle: "The pieces",
    inside: [
      { name: "Binary search — O(log n)", desc: "Halve a *sorted* array each comparison. Wildly fast — but only on sorted data." },
      { name: "Merge sort — O(n log n)", desc: "Split in half, sort each half, merge them. Steady and predictable; great for huge/external data." },
      { name: "Quicksort — O(n log n) avg", desc: "Pick a pivot, partition around it, recurse. Usually fastest in practice; rare bad cases hit O(n²)." },
      { name: "O(n²) sorts", desc: "Bubble/insertion/selection — simple and fine for tiny lists, disastrous on large ones." },
    ],
    how: [
      "**Merge sort** is divide-and-conquer: recursively split the array until each piece is a single item (already sorted), then **merge** sorted pieces back together by repeatedly taking the smaller front element. Its O(n log n) is rock-steady regardless of input, and because it can merge streams, it's how you sort data too big to fit in memory. **Quicksort** picks a **pivot**, rearranges items so smaller ones go left and larger go right, then recurses on each side — typically the fastest in practice, though a poorly chosen pivot can degrade it to O(n²).",
      "**Binary search** needs the array sorted, then it tracks a low and high boundary, checks the middle, and moves whichever boundary discards the wrong half. A handful of comparisons later, it's pinned the item or proven it's absent. The deep lesson: *sorting is an investment* — you pay O(n log n) once, then enjoy O(log n) searches forever after, which is why sorted structures and indexes are everywhere.",
    ],
    why: [
      "Sorting and searching are foundational because *ordered data is fast data*. A sorted array supports binary search, finding ranges (‘all orders between two dates'), de-duplication, and merging — none of which are practical on a jumbled pile. The reason databases build sorted **indexes** is precisely to convert slow full scans into fast log-time lookups.",
      "The trade-offs are about *which* algorithm. Merge sort is predictable and stable but uses extra memory; quicksort is faster on average but has rare bad cases and isn't stable; the O(n²) sorts are dead simple and genuinely fine for tiny inputs but ruinous at scale. And binary search's blistering speed always comes with the precondition that someone paid to sort the data first.",
    ],
    alternatives: [
      { name: "Linear search — O(n)", note: "Just scan every item. No sorting needed, works on anything — but slow on big data. Fine for small or one-off lookups." },
      { name: "Hash table — O(1)", note: "If you only need ‘is this exact key present?', a hash beats binary search — but gives no order or ranges." },
      { name: "Tree / database index", note: "Keeps data sorted *as it changes*, so you get fast search without re-sorting after every insert." },
    ],
    whoUses: "Everyone, indirectly, every day — `.sort()` is one of the most-called functions in existence, and every database query that uses an index is doing a binary-search-like lookup over a sorted structure. Search engines, e-commerce ‘sort by price', leaderboards, and data pipelines all live on it. ‘Could you sort this and binary-search it?' is among the most common interview warm-ups.",
    bigPicture: "This ties the whole map together: merge sort and quicksort *are* divide-and-conquer **recursion**; **heaps** give heapsort; a database **index** is a sorted **tree** that exists to make binary-search-style lookups fast; **Big-O** is the language we use to say *why* O(n log n) beats O(n²). Sorting and searching are where the abstract ideas become the everyday tools.",
    prereqs: ["arrays-and-strings", "big-o-notation", "recursion-and-backtracking"],
    projects: [
      "Implement binary search on a sorted array — then deliberately run it on an *unsorted* one and watch it fail, to feel why the precondition matters.",
      "Write merge sort, then race it against bubble sort on 100,000 random numbers and watch the O(n²) sort fall hopelessly behind.",
    ],
    breaks: "Run binary search on data that *isn't* actually sorted and it returns confidently wrong answers — no crash, just silently incorrect, which is the worst kind of bug. Ship an O(n²) sort that sailed through testing on 50 rows and watch it freeze the server on 50,000. And the off-by-one boundary errors in a hand-written binary search are so notorious that ‘I wrote a bug-free binary search first try' is a small badge of honour.",
    scale: "Tiny lists: any sort works; even O(n²) is fine, and libraries often use a simple sort below a threshold. Large in-memory data: O(n log n) sorts and binary search are the difference between instant and frozen. Data bigger than memory: **external merge sort** streams it in sorted chunks from disk. Planet-scale: sorting is distributed across many machines (the ‘shuffle and sort' phase of big-data jobs), but the O(n log n) limit and the halving trick you learn here still set the rules.",
    related: ["arrays-and-strings", "big-o-notation", "recursion-and-backtracking", "trees-and-bsts", "heaps-priority-queues"],
  },

  "big-o-notation": {
    slug: "big-o-notation",
    title: "Big-O notation",
    category: "Computer Science",
    color: "pink",
    tagline: "The language for ‘how much slower does this get as the data gets bigger?' — the single most useful idea in the whole subject.",
    oneLiner: "Big-O describes how an algorithm's running time (or memory) grows as the input grows, ignoring constants — so you can compare approaches before you ever run them.",
    what: [
      "**Big-O notation** answers one question: *as the input gets bigger, how fast does the work grow?* It's not a stopwatch time in seconds — those depend on your machine, the language, the weather. It's the **shape of the growth**, which is what actually decides whether something survives at scale. Big-O is the shared language engineers use to argue about efficiency, and it's arguably the most important single concept in computer science.",
      "It works by ignoring the noise and keeping the trend. We drop constant factors and small terms, because for large inputs they don't matter — `2n + 5` and `100n` are both just **O(n)** (grows in step with the input), since doubling the input roughly doubles the work either way. What matters is the *category* of growth, not the exact coefficient.",
      "The categories you'll meet, from blissful to disastrous as data grows: **O(1)** constant (same cost no matter the size — a hash lookup); **O(log n)** logarithmic (barely grows — binary search); **O(n)** linear (grows in step — one scan); **O(n log n)** (a good sort); **O(n²)** quadratic (grows with the *square* — nested loops, painful fast); and **O(2ⁿ)** exponential (effectively hopeless beyond tiny inputs — naive recursion that tries everything).",
    ],
    analogy: {
      title: "Planning a trip by distance, not by car",
      body: "If a friend asks how long a journey takes, the deep answer isn't ‘three hours in my car' — it's ‘it grows with distance'. Walking, the time grows steeply with distance; flying, it barely grows at all. Big-O is that ‘how does it grow with distance' answer for algorithms. It tells you which approach stays sane when the trip — the data — gets a thousand times longer, regardless of whose computer is doing the driving.",
    },
    insideTitle: "The growth ladder (best to worst)",
    inside: [
      { name: "O(1) — constant", desc: "Cost doesn't change with size. The dream: hash-table lookup, array index." },
      { name: "O(log n) — logarithmic", desc: "Grows a tiny bit as data multiplies. Binary search, balanced-tree lookup." },
      { name: "O(n) / O(n log n)", desc: "Linear: one pass. n log n: a good sort. Both scale gracefully to large data." },
      { name: "O(n²) and O(2ⁿ)", desc: "Quadratic (nested loops) hurts fast; exponential is unusable beyond tiny inputs. Red flags." },
    ],
    how: [
      "You read Big-O straight off the structure of the code. A single loop over n items is **O(n)**. A loop *inside* a loop, each over n, is **O(n²)** — the warning sign to watch for. Halving the data each step (like binary search) is **O(log n)**. A direct jump with no loop — an array index, a hash lookup — is **O(1)**. Sorting then scanning is **O(n log n)** (you take the dominant term). With practice you spot the growth class at a glance.",
      "Two refinements matter. Big-O usually means the **worst case** (the slowest the algorithm can be), which is what you plan for. And there's **space complexity** too — the same notation applied to *memory* instead of time, because an algorithm that's fast but eats O(n²) memory can be just as unusable. Often you trade one for the other: caching (dynamic programming) spends memory to buy speed.",
    ],
    why: [
      "Big-O exists so you can judge an algorithm **before** writing or running it, and so two engineers can compare approaches without arguing about hardware. It's the tool that lets you predict, on paper, that one solution will sail through a million records while another will choke at ten thousand — turning ‘it feels slow' into a precise, decidable engineering question.",
      "Its deliberate blind spot is also its power: by ignoring constants, it tells you about *scaling*, not absolute speed. So a caveat — for **small** inputs, a ‘worse' Big-O can actually win (a simple O(n²) sort beats a fancy O(n log n) one on ten items, because the constants and simplicity dominate). Big-O is about what happens as things *grow*; it's the right lens for scale, not always for the tiny case in front of you today.",
    ],
    alternatives: [
      { name: "Actual benchmarking", note: "Measure real milliseconds on real hardware. Catches constants and cache effects Big-O ignores — but only for the sizes you test." },
      { name: "Big-Θ and Big-Ω", note: "Tighter relatives: Θ pins the exact growth, Ω the best case. Big-O (the upper bound) is the one used in everyday practice." },
      { name: "Profiling", note: "Find *where* real time goes in a running program. Complements Big-O: theory tells you the shape, profiling tells you the hotspot." },
    ],
    whoUses: "Every engineer who has sat a technical interview (‘what's the time complexity?' is the most-asked follow-up in the industry) and every team designing for scale. It's the common tongue in code reviews, system-design discussions, and any conversation that starts ‘will this hold up when we have a million users?'. Knowing it is table stakes for being taken seriously as a programmer.",
    bigPicture: "Big-O is the measuring stick for the entire rest of this subject — it's *why* we say a hash table (O(1)) beats a list scan (O(n)), why a balanced tree (O(log n)) beats a lopsided one (O(n)), why a good sort (O(n log n)) beats a bad one (O(n²)), and why dynamic programming's whole point is escaping O(2ⁿ). Learn Big-O and every other data-structure and algorithm choice suddenly has a number attached, and the trade-offs stop being vibes and become arithmetic.",
    prereqs: ["what-is-a-program", "arrays-and-strings"],
    projects: [
      "Take three functions you've written and label each one's Big-O by inspecting its loops — then test whether your guess matches a real timing run as input grows.",
      "Write the same ‘find duplicates' task two ways — a nested-loop O(n²) version and a hash-set O(n) version — and plot how their times diverge as the list grows.",
    ],
    breaks: "Misjudging Big-O is how ‘worked in the demo, died in production' happens: a hidden nested loop (O(n²)) is invisible on test data and lethal at scale. But over-applying it bites too — obsessing over Big-O on a list that will never exceed 20 items wastes effort and can make code needlessly complex (and even slower for that tiny size). The skill is knowing *when* growth matters, then refusing to ship the quadratic surprise.",
    scale: "Big-O *is* the language of scale — it's the lens that tells you, before you build, whether an approach reaches from ten users to a million. At small sizes constants dominate and Big-O can mislead; as data grows it becomes the decisive factor; at planet-scale it governs not just single algorithms but whole architectures (why we shard, cache, and index — each one is an effort to beat a bad growth curve). It is the through-line from a first ‘hello world' to designing systems for billions.",
    related: ["data-structures-overview", "arrays-and-strings", "hash-tables", "sorting-and-searching", "dynamic-programming"],
  },
};
