// The roles in software, what each actually does, and what to learn for each.
// `learn` arrays point at tech-reference slugs (live or planned) that matter most
// for the role — the spine of a "where do I start?" guide per career path.
export const ROLES = [
  {
    id: "frontend",
    title: "Frontend Engineer",
    blurb: "Builds the part of the app people actually see and touch — the screens, the buttons, the feel.",
    does: [
      "Turns designs into working, interactive interfaces in the browser (or app), pixel by pixel.",
      "Wires the UI up to the backend's APIs and shows the data that comes back.",
      "Makes it fast, responsive across screen sizes, and accessible to people using keyboards or screen readers.",
      "Manages what the screen remembers right now — form inputs, the cart, who's logged in (client-side state).",
    ],
    skills: ["HTML, CSS & JavaScript", "A framework (React/Next.js or Flutter)", "TypeScript for safer code", "Talking to REST/GraphQL APIs", "Accessibility & responsive layout", "State management"],
    learn: ["typescript", "nextjs", "css-accessibility", "http-rest", "json", "rendering", "api-styles", "oop-vs-functional", "version-control-git", "testing-strategies"],
    projects: [
      "A responsive, accessible product page that fetches and displays live data.",
      "A multi-step form (with validation and client-side state) like a checkout flow.",
      "A small design-system of reusable, tested UI components.",
    ],
  },
  {
    id: "backend",
    title: "Backend Engineer",
    blurb: "Builds the brain behind the screen — the servers, APIs, and logic the app talks to.",
    does: [
      "Designs and builds APIs that the frontend (and other services) call to get things done.",
      "Implements the real business logic — placing orders, processing payments, awarding loyalty points.",
      "Models and queries the database, and keeps writes correct and safe under load.",
      "Handles authentication, authorisation, and the security guards on every request.",
    ],
    skills: ["A server language (Node.js, Python, Java, Go)", "Designing REST/GraphQL APIs", "Databases & SQL", "Auth & web security", "Transactions, idempotency, caching", "Testing"],
    learn: ["nodejs", "express", "http-rest", "api-styles", "postgresql", "sql", "prisma", "transactions", "idempotency", "auth", "web-security", "caching", "testing-strategies", "design-patterns", "solid-principles"],
    projects: [
      "A REST API for a small store: products, carts, orders — with auth and validation.",
      "An order+payment flow wrapped in a transaction and protected by an idempotency key.",
      "A rate-limited, cached public API endpoint that survives a traffic spike.",
    ],
  },
  {
    id: "fullstack",
    title: "Full-stack Engineer",
    blurb: "Works across the whole stack — frontend, backend, and database — and ships a feature end to end.",
    does: [
      "Builds a feature through every layer: the screen, the API behind it, and the database it touches.",
      "Moves fluidly between frontend and backend instead of handing work over a wall.",
      "Owns small features or whole small products solo — common in startups and small teams.",
      "Makes pragmatic trade-offs about where logic should live (client vs server vs database).",
    ],
    skills: ["Frontend (a UI framework)", "Backend (a server language + APIs)", "Databases & SQL", "Auth & the full request cycle", "Git & deployment basics", "Knowing enough of everything to be dangerous"],
    learn: ["typescript", "nextjs", "nodejs", "express", "http-rest", "json", "postgresql", "prisma", "sql", "auth", "transactions", "version-control-git", "ci-cd", "testing-strategies", "clean-code-refactoring"],
    projects: [
      "A complete small app — say a to-do or mini-store — frontend, backend, and database, deployed live.",
      "Add a real feature end-to-end: a new screen, the API behind it, and the schema change it needs.",
      "Wire authentication through every layer: login UI, token handling, protected API routes.",
    ],
  },
  {
    id: "mobile",
    title: "Mobile Engineer",
    blurb: "Builds the app that lives on a phone — native-feeling, offline-tolerant, and smooth.",
    does: [
      "Builds the screens and interactions of an iOS/Android (or cross-platform) app.",
      "Handles phone realities: flaky networks, working offline, battery, and limited memory.",
      "Manages app state and navigation, and crafts the smooth motion and gestures users expect.",
      "Ships through the app stores and deals with their review and update cycles.",
    ],
    skills: ["Flutter/Dart or native (Swift / Kotlin)", "Mobile state management (e.g. Riverpod)", "A network client + caching", "Offline-first & sync", "Animations & gestures", "App-store release process"],
    learn: ["dart", "flutter", "riverpod", "dio", "offline-first", "http-rest", "json", "caching", "oop-vs-functional", "version-control-git", "testing-strategies"],
    projects: [
      "A cross-platform app that works offline and syncs when the network returns.",
      "A screen with rich, smooth animations and gesture-driven interactions.",
      "A polished list-detail app talking to a real API, with caching and loading states.",
    ],
  },
  {
    id: "devops",
    title: "DevOps / Platform Engineer",
    blurb: "Builds the roads the code travels on — how it gets tested, packaged, and shipped to production.",
    does: [
      "Builds and maintains CI/CD pipelines that test and deploy every change automatically.",
      "Packages apps into containers and runs them reliably (often with Kubernetes).",
      "Provisions and manages cloud infrastructure, usually as code (Terraform and friends).",
      "Builds the internal tools and ‘paved roads' that let product teams ship safely on their own.",
    ],
    skills: ["Linux & scripting", "Docker & Kubernetes", "CI/CD pipelines", "Cloud (AWS/GCP/Azure) & infra-as-code", "Networking basics", "Observability & secrets management"],
    learn: ["ci-cd", "docker", "kubernetes", "cloud", "cloud-compute", "observability", "secrets-management", "version-control-git", "agile-and-scrum", "cloud-cost-regions"],
    projects: [
      "A CI/CD pipeline that runs tests and deploys an app on every push to main.",
      "Containerise an app with Docker and run it on Kubernetes with health checks.",
      "Define a piece of cloud infrastructure as code so it can be recreated from scratch.",
    ],
  },
  {
    id: "sre",
    title: "Site Reliability Engineer (SRE)",
    blurb: "Keeps systems up, fast, and recoverable — engineering reliability as a first-class product.",
    does: [
      "Defines and defends reliability targets (SLOs) and watches error budgets.",
      "Builds monitoring, alerting, and dashboards so problems are seen before users feel them.",
      "Leads incident response when things break, then runs blameless post-mortems to stop repeats.",
      "Hunts and removes bottlenecks and single points of failure before they cause an outage.",
    ],
    skills: ["Deep systems & networking knowledge", "Observability (logs, metrics, traces)", "Incident response & on-call", "Scaling, load balancing, failover", "Automation & scripting", "Capacity planning"],
    learn: ["observability", "kubernetes", "caching", "sharding", "rate-limiting", "concurrency", "message-queues", "cloud-cost-regions", "system-design-interview", "ci-cd"],
    projects: [
      "Add metrics, logs, and traces to a service and build a dashboard that shows its health at a glance.",
      "Run a game-day: deliberately break a dependency and practise detecting and recovering from it.",
      "Load-test a service to find its breaking point, then remove the bottleneck you find.",
    ],
  },
  {
    id: "data-engineer",
    title: "Data Engineer",
    blurb: "Builds the pipelines that move and shape data so analysts and models can actually use it.",
    does: [
      "Builds ETL/ELT pipelines that pull data from many sources, clean it, and load it for analysis.",
      "Designs and maintains data warehouses and lakes, and keeps them queryable and trustworthy.",
      "Chooses batch vs streaming per need, and orchestrates pipelines to run, retry, and alert.",
      "Guards data quality so the dashboards and models built on top can be trusted.",
    ],
    skills: ["Strong SQL", "Python (or Scala) for pipelines", "Warehouses & lakes", "Batch & streaming tools (Spark, Kafka)", "Orchestration (Airflow)", "Data modelling & quality"],
    learn: ["data-engineering-basics", "sql", "postgresql", "message-queues", "object-storage-cdn", "sharding", "cloud", "caching", "version-control-git"],
    projects: [
      "A scheduled batch pipeline: extract from a database, transform, load into an analytics table.",
      "A streaming pipeline that updates a running aggregate as events arrive off a queue.",
      "Add automated data-quality checks that fail the pipeline when numbers look wrong.",
    ],
  },
  {
    id: "ml-engineer",
    title: "Machine Learning Engineer",
    blurb: "Takes models from notebook to production — trained, served, and reliable at scale.",
    does: [
      "Builds the pipelines that train models on real data and evaluate how good they are.",
      "Serves models behind APIs so the rest of the product can use their predictions.",
      "Optimises inference for speed and cost, since every prediction is paid for, forever.",
      "Monitors models in production for drift and degradation, and retrains when needed.",
    ],
    skills: ["Python & ML libraries", "How neural networks & training work", "Training vs inference & cost", "Embeddings, RAG & vector search", "Serving & MLOps", "Data pipelines & SQL"],
    learn: ["neural-networks", "training-vs-inference", "embeddings", "rag", "data-engineering-basics", "cloud-compute", "caching", "managed-services", "system-design-interview", "testing-strategies"],
    projects: [
      "Train a small model, evaluate it honestly, and serve it behind a simple prediction API.",
      "Build a RAG feature: embed a set of documents and answer questions grounded in them.",
      "Optimise an inference endpoint (batching, caching) and measure the cost-per-request drop.",
    ],
  },
  {
    id: "security-engineer",
    title: "Security Engineer",
    blurb: "Thinks like an attacker so the real ones can't — finding and closing holes before they're exploited.",
    does: [
      "Threat-models systems to find where they could be attacked, before attackers do.",
      "Reviews code and architecture for vulnerabilities (injection, broken auth, data leaks).",
      "Hardens authentication, manages secrets, and enforces least-privilege access everywhere.",
      "Responds to security incidents and builds defences so the same hole can't reopen.",
    ],
    skills: ["Web security (XSS, SQLi, SSRF & more)", "Auth, sessions & cryptography basics", "Threat modelling", "Secrets management & least privilege", "Reading code for vulnerabilities", "Incident response"],
    learn: ["web-security", "auth", "threat-modelling", "secrets-management", "http-rest", "rate-limiting", "code-review", "cloud", "observability", "system-design-interview"],
    projects: [
      "Threat-model a small app: map its assets, entry points, and the worst things that could go wrong.",
      "Find and fix a deliberate vulnerability (SQL injection or XSS) in a practice codebase.",
      "Lock down a service: scope its permissions, move secrets out of code, and add an audit log.",
    ],
  },
  {
    id: "qa-engineer",
    title: "QA / Test Engineer",
    blurb: "Makes sure it actually works before users find out it doesn't — through tests and a quality eye.",
    does: [
      "Designs test plans and writes automated tests across the pyramid (unit, integration, e2e).",
      "Builds and maintains end-to-end suites that drive the app like a real user.",
      "Hunts for edge cases and breaks things on purpose to find bugs early.",
      "Works the quality into the pipeline so every change is checked before it ships.",
    ],
    skills: ["Testing strategies & the pyramid", "A test framework + e2e tools (Playwright/Cypress)", "Reading & writing code", "API testing", "Bug-hunting & edge-case thinking", "CI integration"],
    learn: ["testing-strategies", "test-driven-development", "http-rest", "api-styles", "ci-cd", "version-control-git", "clean-code-refactoring", "code-review", "web-security"],
    projects: [
      "Build a small test pyramid for an app: unit, integration, and a few e2e journeys.",
      "Automate an end-to-end test of a critical flow (sign up → order → pay) that runs in CI.",
      "Write tests that reproduce real bugs first, then confirm the fixes — so they can't return.",
    ],
  },
  {
    id: "data-scientist",
    title: "Data Scientist",
    blurb: "Turns data into insight and predictions — finding the patterns that drive decisions.",
    does: [
      "Explores and analyses data to answer business questions and surface patterns.",
      "Builds statistical and machine-learning models to predict and explain.",
      "Designs experiments (A/B tests) and judges what the results actually mean.",
      "Communicates findings clearly to people who'll act on them — the insight is the product.",
    ],
    skills: ["Statistics & probability", "Python/R & data libraries", "SQL", "Machine learning fundamentals", "Data visualisation & storytelling", "Experiment design"],
    learn: ["data-engineering-basics", "sql", "neural-networks", "embeddings", "training-vs-inference", "postgresql", "version-control-git"],
    projects: [
      "Analyse a real dataset end-to-end: clean it, find a pattern, and present the finding clearly.",
      "Build and evaluate a predictive model, and explain honestly how much to trust it.",
      "Design an A/B test, then analyse whether the difference it shows is real or noise.",
    ],
  },
  {
    id: "engineering-manager",
    title: "Engineering Manager",
    blurb: "Grows the people and steers the team — trading writing code for multiplying others' impact.",
    does: [
      "Leads, mentors, and grows a team of engineers — careers, feedback, and hiring.",
      "Shapes priorities and process so the team ships the right things, sustainably.",
      "Removes blockers, manages stakeholders, and shields the team from churn.",
      "Owns technical direction and big trade-offs with the team, even while coding far less.",
    ],
    skills: ["People leadership & mentoring", "Strong technical judgement", "Agile/Scrum & delivery", "Communication & stakeholder management", "System & architecture literacy", "Hiring & team building"],
    learn: ["agile-and-scrum", "code-review", "version-control-git", "system-design-interview", "testing-strategies", "clean-code-refactoring", "ci-cd"],
    projects: [
      "Run a team's delivery rhythm: a healthy backlog, sprints, and retrospectives that actually improve things.",
      "Establish quality practice — review standards and a definition of ‘done' the team owns.",
      "Lead a project end-to-end through people: scope it, unblock it, and ship it without writing most of the code.",
    ],
  },
];
