// Web & frontend, in depth — the browser, the runtime, and the patterns that make pages fast and alive.
export const WEB_DEEP = {
  "browser-rendering-pipeline": {
    slug: "browser-rendering-pipeline",
    title: "The browser rendering pipeline",
    category: "Web & Frontend",
    color: "blue",
    tagline: "What actually happens between 'here's some HTML' and a pixel lighting up on screen.",
    oneLiner: "To show a page, the browser turns your HTML and CSS into trees, works out the size and position of every element, fills in the pixels, and stitches the layers together — and knowing those stages explains why some changes are cheap and some are expensive.",
    what: [
      "When a browser receives your HTML, it can't just paint it — text and tags aren't pixels. It runs a fixed sequence of stages, the **rendering pipeline**, that converts markup and styles into the coloured dots you see. Each stage feeds the next, and each costs time.",
      "First the browser parses your HTML into the **DOM** (Document Object Model) — a tree of objects, one per tag, that code and styles can attach to. It parses your CSS into a parallel tree, the **CSSOM** (CSS Object Model), which knows every rule. It combines the two into a **render tree**: only the things that will actually be drawn (a `display: none` element is in the DOM but not the render tree).",
      "Then comes **layout** (also called *reflow*): the browser walks the render tree and computes the exact size and position of every box — how wide this paragraph is, where that button sits. **Paint** turns each box into actual pixels (colours, text, shadows, borders) on layers. Finally **composite** stacks those layers in the right order and hands the result to the screen.",
      "The two words worth burning into memory are **reflow** and **repaint**. A **reflow** re-runs layout because a geometry changed (an element got wider, text was added) — expensive, because moving one box can shove everything after it. A **repaint** redraws pixels without moving anything (you changed a colour) — cheaper. Some changes (like `transform` and `opacity`) can skip both and happen purely at the **composite** stage on the GPU — cheapest of all.",
    ],
    analogy: {
      title: "Laying out a newspaper page",
      body: "Think of an editor assembling a newspaper. First they list every article and photo (the DOM) and the house style rules (the CSSOM). They decide which items actually go on this page (the render tree). Then they measure and arrange every column and image so it all fits (layout). Then the printer inks each region (paint). Finally the printed sheets are stacked in order (composite). Now: nudging one headline's font size forces re-measuring the whole page (a reflow); just recolouring a box that's already placed only needs re-inking (a repaint); sliding a finished sticker across the page touches nothing underneath (a composite-only change).",
    },
    insideTitle: "The stages of the pipeline",
    inside: [
      { name: "DOM", desc: "A tree of objects built from your HTML — one node per tag. Everything else attaches to it." },
      { name: "CSSOM", desc: "A tree of all your CSS rules, so the browser knows how each element should look." },
      { name: "Render tree", desc: "DOM + CSSOM merged, keeping only what will be drawn — hidden elements are excluded." },
      { name: "Layout (reflow)", desc: "Computing the exact size and position of every box. Re-run whenever geometry changes." },
      { name: "Paint (repaint)", desc: "Filling in the actual pixels — colours, text, borders, shadows — onto layers." },
      { name: "Composite", desc: "Stacking the painted layers in the correct order, often on the GPU, into the final frame." },
    ],
    how: [
      "Parsing is **incremental and blockable**. The browser builds the DOM as bytes arrive, but a `<script>` tag (without `async`/`defer`) stops parsing because the script might rewrite the page — this is why script placement matters. CSS is **render-blocking**: the browser won't paint until it has the CSSOM, because it doesn't want to flash unstyled text. That's the whole reason critical CSS lives in the `<head>`.",
      "Layout and paint don't run on every tiny change individually — the browser **batches** them. It collects your DOM/style changes and flushes them once per frame (ideally every ~16ms to hit 60 frames per second). The trap is **layout thrashing**: if your JavaScript writes a style and then immediately reads a geometric value (like `offsetHeight`), the browser is forced to reflow *right now* to give you an honest answer. Do that in a loop and you trigger dozens of synchronous reflows, and the page janks.",
      "The composite stage is special because it runs on the **GPU** and on a separate thread. Animating `transform` (move/scale/rotate) or `opacity` only changes how existing layers are composited — no layout, no paint — so it stays smooth even while the main JavaScript thread is busy. Animating `width`, `top`, or `left` forces reflow + repaint every frame, which is why guides say 'animate transform and opacity, not layout properties.'",
    ],
    why: [
      "Understanding the pipeline turns vague advice ('don't cause reflows') into something you can reason about. If you know that changing `height` triggers layout but changing `transform` doesn't, you can pick the cheap path deliberately instead of guessing. Performance work on the front end is largely the art of doing as little of the expensive stages as possible.",
      "The trade-off is that the cheapest tricks aren't always the right tool. Compositor-only animations are buttery, but you can't composite your way out of genuinely needing to reflow content. And pushing everything onto GPU layers has its own cost — too many layers eats memory and can make things slower. The pipeline gives you the levers; judgment decides when to pull each one.",
    ],
    alternatives: [
      { name: "Virtual DOM (React)", note: "A library keeps an in-memory copy of the tree, diffs it, and makes the minimum real DOM changes — so you write declaratively and it tries to minimise reflows for you." },
      { name: "Direct DOM manipulation", note: "You touch the real DOM yourself (vanilla JS, jQuery). Maximum control, but easy to cause layout thrashing if you interleave reads and writes." },
      { name: "Canvas / WebGL rendering", note: "Skip the DOM pipeline entirely and draw pixels yourself on a canvas — used by maps, games, and data-viz where thousands of elements would overwhelm layout." },
    ],
    whoUses: "Every web developer touches this, whether they know it or not. It matters most to front-end engineers chasing 60fps animations, anyone debugging a janky scroll or a slow page in browser DevTools (the Performance tab literally labels these stages), and library authors building UI frameworks who must minimise reflows on your behalf. Game and data-visualisation developers care enough to leave the DOM behind for canvas.",
    bigPicture: "This is the last mile of the whole web journey: HTTP delivers the bytes, the browser's pipeline turns them into a picture. It sits directly downstream of rendering strategy (CSR/SSR decide who produces the HTML and when) and directly upstream of perceived performance and the Core Web Vitals users actually feel. The event loop (next door) is what schedules these stages between your JavaScript runs.",
    prereqs: ["how-the-internet-works", "css-accessibility"],
    projects: [
      "Open any site's DevTools Performance panel, record a scroll, and find the green 'Layout' and 'Paint' bars — then make a change that causes a reflow and watch it appear.",
      "Build a box that animates with `left: 200px` then rebuild it with `transform: translateX(200px)`, and compare the frame rates in DevTools.",
      "Write a loop that reads `el.offsetWidth` and writes `el.style.width` alternately, watch it thrash, then batch all reads before all writes and watch the jank disappear.",
    ],
    breaks: "A scroll handler reads each element's position and then nudges its style — read, write, read, write — and every read forces a synchronous reflow because the browser must settle the layout to answer honestly. The page stutters horribly on a mid-range phone while looking fine on your fast laptop. The fix is to batch: read all the geometry first, then do all the writes, so the browser reflows once instead of hundreds of times.",
    scale: "On a learning project with a few dozen elements, the pipeline is invisible — everything is instant and you never think about reflow. In a production app with thousands of DOM nodes, layout cost becomes real: long lists need virtualisation (render only the visible rows) and animations get moved onto `transform`/`opacity` to stay on the compositor. At enterprise scale you set a performance budget and track Core Web Vitals from real users' devices, because a slow pipeline directly costs conversions. At planet scale (a Google or a Facebook), teams build custom rendering layers, ship framework-level scheduling (concurrent rendering, partial hydration), and treat a single extra reflow per frame as a regression worth a whole investigation — because it plays out across billions of low-end devices on slow networks.",
    related: ["rendering", "css-accessibility", "the-event-loop", "web-performance", "nextjs"],
  },

  "the-event-loop": {
    slug: "the-event-loop",
    title: "The JavaScript event loop",
    category: "Web & Frontend",
    color: "purple",
    tagline: "How a single-threaded language juggles timers, clicks, and network replies without ever blocking — and the subtle ordering rules that trip everyone up.",
    oneLiner: "JavaScript runs your code on one thread using a loop that pulls waiting tasks off queues one at a time, always finishing the current task (plus all its microtasks) before painting or starting the next — which is why nothing interrupts your code midway, and why `await` resumes before the next `setTimeout`.",
    what: [
      "JavaScript is **single-threaded**: there is exactly one thread running your code, so only one line executes at any instant. That sounds like it should make the browser freeze whenever anything slow happens — yet pages stay responsive while waiting on the network, timers, and clicks. The **event loop** is the mechanism that makes that possible.",
      "Here's the model. There's a **call stack** — the pile of functions currently running. When the stack is empty, the event loop looks for work to do in two places: the **task queue** (also called the *macrotask* queue) holds things like a timer firing, a click event, or a network response arriving; the **microtask queue** holds the callbacks from resolved Promises (and `await` continuations). The loop's job is to keep the stack fed.",
      "The crucial rule: the loop runs **one macrotask**, then **drains the entire microtask queue** (every microtask, including ones that schedule more microtasks), and only then considers rendering and the next macrotask. This is why a Promise callback (`.then`) always runs before a `setTimeout(0)` that was scheduled earlier — microtasks jump the queue.",
      "Slow operations (a network request, reading a file, a timer) don't run *on* this thread. The browser or Node hands them to background machinery (Web APIs / the OS), and when they finish, their callback is dropped into a queue. Your single thread never waits — it just gets notified later. That's **non-blocking** I/O, and it's the whole reason one thread can serve thousands of things at once.",
    ],
    analogy: {
      title: "A solo chef with a ticket rail and a sticky-note pad",
      body: "Imagine one chef (the single thread) cooking from a rail of order tickets (the macrotask queue). The chef never stands idle waiting for the oven — they put the dish in, grab the next ticket, and the oven's timer (a Web API) drops a new ticket on the rail when it dings. But there's also a sticky-note pad (the microtask queue) for urgent follow-ups to the dish they *just* finished. The rule of the kitchen: after finishing any one ticket, the chef clears every sticky note before touching the next ticket. So 'urgent follow-up' notes always get done before the next order — even an order that arrived earlier.",
    },
    insideTitle: "The moving parts",
    inside: [
      { name: "Call stack", desc: "The pile of function calls running right now. One stack, one thread — last in, first out." },
      { name: "Web APIs / host", desc: "Background machinery (timers, fetch, DOM events) that does slow work off-thread and queues a callback when done." },
      { name: "Task (macrotask) queue", desc: "Where timers, events, and I/O callbacks wait. The loop takes one per turn." },
      { name: "Microtask queue", desc: "Promise/`await` continuations. Fully drained after each macrotask, before rendering or the next task." },
      { name: "Render step", desc: "The browser's chance to run the pipeline (layout/paint) — squeezed in between tasks, only when microtasks are empty." },
    ],
    how: [
      "One loop turn ('tick') looks like this: take one macrotask off the queue and run it to completion on the stack; then run microtasks until that queue is empty (a microtask can enqueue another, and they all run before moving on); then, if it's time for a frame, let the browser render. Repeat forever. Note what's missing: there is no preemption — your function is never paused midway by the loop. It runs until it returns. That's why JavaScript code is free of the data races that plague true multithreading.",
      "`await` is just sugar over this. When you `await` a Promise, the function pauses and the rest of it is registered as a **microtask** to run when the Promise resolves. The thread is freed immediately to do other work. When the Promise settles, the continuation goes on the microtask queue — so `await` resumes *before* any pending `setTimeout`, which surprises people who expect timers to be 'instant'.",
      "Node's loop is the same idea with extra phases (timers, I/O callbacks, `setImmediate`, close callbacks) and one extra-urgent microtask source, `process.nextTick`, which runs even before Promise microtasks. The headline rule transfers everywhere: **never block the loop**. A long synchronous computation (a giant `for` loop, parsing a huge JSON string) keeps the stack busy, so no macrotasks run, no microtasks run, and the page freezes — clicks pile up unanswered. Heavy work belongs in a **Web Worker** (a real second thread) or chunked across ticks.",
    ],
    why: [
      "The event loop is the reason a single-threaded language can power highly interactive UIs and high-throughput servers. Because the thread never blocks on I/O, one Node process can handle thousands of simultaneous connections — it's just juggling callbacks, not parking a thread per request. And because nothing preempts your running function, you get a simple mental model with no locks and no data races for your own logic.",
      "The trade-offs are real. CPU-bound work has no good home on the loop — one heavy computation stalls everything, so you must offload it. And the ordering rules (macrotask vs microtask, the render slot in between) are subtle enough that timing bugs ('why did this run before that?') are common. The model trades the dangers of shared-memory threading for the discipline of never blocking and understanding the queues.",
    ],
    alternatives: [
      { name: "OS threads (one per request)", note: "The classic server model (Java, traditional Apache): a thread blocks while waiting on I/O. Simple to reason about, but heavy — thousands of threads cost memory and context-switching." },
      { name: "Web Workers", note: "Spin up a genuinely separate thread for CPU-heavy work, communicating by passing messages. The escape hatch when something would block the loop." },
      { name: "Goroutines / green threads", note: "Languages like Go give you cheap lightweight 'threads' the runtime schedules, hiding the loop entirely while still not blocking real OS threads." },
    ],
    whoUses: "Every JavaScript and TypeScript developer relies on it, but it bites hardest for front-end engineers debugging a frozen UI or a baffling callback-ordering bug, Node.js backend engineers who must keep the loop unblocked to serve traffic, and anyone wiring up Promises, `async/await`, timers, or animation frames. Interviewers love asking people to predict the output order of mixed `setTimeout` and `Promise.then` code — it's a direct test of this model.",
    bigPicture: "The event loop is the scheduler sitting underneath all asynchronous web code — it decides when your callbacks run, and it shares the main thread with the rendering pipeline, which is why blocking it freezes the page. It's the front-end cousin of the server-side concurrency models (threads vs event loop) and the reason Node can be so I/O-efficient. Understanding it is the foundation for reasoning about performance, animations, and why 'just add `await`' sometimes changes behaviour.",
    prereqs: ["what-is-a-program", "how-code-runs"],
    projects: [
      "Write a snippet mixing `console.log` calls, a `setTimeout(…, 0)`, and a `Promise.resolve().then(…)`, predict the print order on paper, then run it and explain any surprise.",
      "Build a page with a button that runs a 3-second `while` loop and watch the whole UI freeze — then move that work into a Web Worker and watch the UI stay responsive.",
      "Implement a tiny `sleep(ms)` using a Promise + `setTimeout`, and use it to animate a counter, observing how `await` yields the thread between steps.",
    ],
    breaks: "A developer adds a feature that parses a 20MB JSON file synchronously in a click handler. On their fast laptop it's fine; in production, on a phone, the parse takes two seconds — during which the call stack never empties, so no clicks register, no animations advance, and the browser may even show a 'page unresponsive' dialog. Everything *looks* like a hang, but it's just one task hogging the single thread. The fix is to move the parse to a Web Worker or stream it in chunks so the loop can breathe between bites.",
    scale: "When you're learning, the loop is invisible — your scripts are short and finish in milliseconds. In a production single-page app, you start caring: you debounce expensive handlers, chunk big computations across ticks with `requestIdleCallback`, and move heavy work to Web Workers so animations stay at 60fps. On a busy Node backend, the discipline becomes operational — one accidental synchronous call (a sync file read, a blocking crypto operation) can tank the throughput of the entire process, so teams monitor 'event loop lag' as a first-class metric. At planet scale you run many processes across many machines (because one loop is still one core), add worker pools for CPU work, and treat any loop-blocking code path as a production incident waiting to happen — the model doesn't change, but the cost of ignoring it multiplies by your traffic.",
    related: ["concurrency", "nodejs", "browser-rendering-pipeline", "web-performance", "how-code-runs"],
  },

  "web-performance": {
    slug: "web-performance",
    title: "Web performance",
    category: "Web & Frontend",
    color: "teal",
    tagline: "Making a page feel instant — measured by what the user actually experiences, not by your fast laptop.",
    oneLiner: "Web performance is the practice of getting a page to load, become interactive, and stay smooth as fast as possible — measured by user-centred metrics (the Core Web Vitals) and improved by sending less, sending it closer, and doing less work on the device.",
    what: [
      "A page can be 'correct' and still feel broken if it's slow — a blank screen for three seconds, a button that ignores taps, content that jumps as images load. **Web performance** is the discipline of making the experience feel fast, and the first insight is that 'fast' must be measured *from the user's perspective*, not from your developer machine on office wifi.",
      "The industry's shared yardstick is the **Core Web Vitals**: **LCP** (Largest Contentful Paint — how long until the main content appears), **INP** (Interaction to Next Paint — how quickly the page responds to a tap or click), and **CLS** (Cumulative Layout Shift — how much the page jumps around while loading). Good scores correlate with users staying; bad ones with them leaving.",
      "Most of the speed-ups come from a few big ideas. **Send less**: ship smaller images, fewer fonts, and less JavaScript. **Send it closer**: serve assets from a **CDN** near the user instead of one distant origin. **Send it later**: **lazy-load** images and components that aren't visible yet, and **code-split** so the browser downloads only the JavaScript a page actually needs. **Send it once**: cache aggressively so repeat visits are nearly free.",
      "The single heaviest lever on modern sites is usually **JavaScript**. Every kilobyte must be downloaded, parsed, and executed on the main thread — and on a cheap phone that's far slower than on your laptop. Shipping less JS, splitting it by route, and deferring non-critical scripts is the highest-impact work on most pages.",
    ],
    analogy: {
      title: "Getting a meal to the table",
      body: "Imagine how fast a restaurant feels. You can plate the first visible course quickly (LCP — get the main thing on screen fast). You can make sure that when a guest signals the waiter, someone responds right away instead of after a long delay (INP — stay responsive). And you can stop rearranging the table after the food arrives, so the guest's water glass doesn't get knocked as a late dish slides in (CLS — no surprise shifts). The tricks: prep dishes ahead (caching), keep a kitchen near the diners (a CDN), and don't carry out the whole menu when only the starter was ordered (lazy-loading and code-splitting).",
    },
    insideTitle: "The toolkit",
    inside: [
      { name: "Core Web Vitals", desc: "LCP (content appears), INP (responds to input), CLS (visual stability) — Google's user-centred metrics." },
      { name: "Lazy-loading", desc: "Defer loading images/components until they're about to be needed, so the first screen is light." },
      { name: "Code-splitting", desc: "Break the JS bundle into per-route chunks so a page downloads only the code it uses." },
      { name: "Caching", desc: "Reuse already-fetched assets (browser cache, service worker) so repeat visits skip the download." },
      { name: "CDN", desc: "Serve static assets from edge servers physically near the user, cutting round-trip latency." },
      { name: "Compression & formats", desc: "Gzip/Brotli for text; modern image formats (WebP/AVIF) and right-sized images for pictures." },
    ],
    how: [
      "Performance work follows a loop: **measure, fix the biggest thing, measure again.** You measure two ways — **lab** data (a controlled run in DevTools or Lighthouse, reproducible, good for debugging) and **field** data (real users' devices and networks, the truth that actually matters). The gap between them is usually 'it's fast on my laptop' — field data is what catches the slow-phone reality.",
      "Under the hood, the wins map to the page's lifecycle. The **critical rendering path** is everything needed for first paint: minimise render-blocking CSS and JS in the `<head>`, inline critical CSS, and `defer` scripts. For images, set explicit `width`/`height` (so the browser reserves space and avoids layout shift — that's the CLS fix) and lazy-load below-the-fold ones. For JavaScript, split per route and load interactive widgets on demand, so the main thread isn't busy parsing code the user can't see yet.",
      "Caching and delivery do the rest. A **CDN** keeps copies of your assets at edge locations worldwide, so a user in Sydney isn't waiting on a server in Virginia. Cache headers tell the browser to reuse files on repeat visits. And rendering strategy ties in directly: a statically generated page served from a CDN gives the fastest possible LCP, while a heavy client-rendered app pays for a big JS download before anything appears — which is why framework choices are performance choices.",
    ],
    why: [
      "Performance is a business metric, not a vanity one. Slow pages measurably lose users and revenue, hurt search ranking (Core Web Vitals feed Google's ranking), and disproportionately hurt people on cheap phones and slow networks — which is most of the world. Investing here widens your audience and lifts conversions, often more cheaply than any feature.",
      "The trade-off is complexity and discipline. Aggressive caching risks serving stale content (you must wire up invalidation); code-splitting adds build configuration and can cause loading flickers if done carelessly; chasing a perfect Lighthouse score can lead to micro-optimising things users never notice. The skill is measuring what users feel, fixing the biggest real bottleneck, and stopping there — not optimising for a number in isolation.",
    ],
    alternatives: [
      { name: "Server-side rendering / static generation", note: "Produce HTML ahead of time or on the server so content paints before JS loads — often the biggest LCP win for content-heavy pages." },
      { name: "Edge rendering", note: "Run the rendering itself at CDN edge locations near users, combining freshness with low latency." },
      { name: "Do nothing (premature)", note: "For a tiny low-traffic site, perfect performance may not be worth the effort — but measure before assuming you're in that bucket." },
    ],
    whoUses: "Front-end and full-stack engineers own most of this day to day; performance specialists and SREs at larger companies make it a full-time job. It's a priority for any business where speed maps to money — e-commerce, media, search — and for any product targeting emerging markets where mid-range phones and slow networks dominate. Anyone who's watched a Lighthouse score, debugged a layout shift, or argued about bundle size is doing web performance.",
    bigPicture: "Web performance is where the whole stack's choices show up as a felt experience: the rendering strategy, the rendering pipeline's reflow costs, the event loop staying unblocked, the CDN and caching layers, and the size of the JavaScript bundle all converge here. It's the front-end face of caching and CDNs, and it closes the loop from 'the system is correct' to 'the system feels good to use.'",
    prereqs: ["how-the-internet-works", "browser-rendering-pipeline"],
    projects: [
      "Run Lighthouse on a page you built, find your worst Core Web Vital, fix exactly that one thing (e.g. add image dimensions to kill CLS), and re-run to confirm the number moved.",
      "Take a route that imports a heavy chart library eagerly and convert it to a dynamically-imported, lazy-loaded component — then compare the initial JS bundle size before and after.",
      "Serve a folder of images twice — once from your origin, once through a CDN — and measure the load time difference from a device far from your server.",
    ],
    breaks: "A team ships a marketing site that scores great on their office network. In the field, users on 4G phones stare at a blank screen for four seconds while a 2MB JavaScript bundle downloads and runs before anything paints, and the hero image — with no reserved dimensions — slams the text downward just as they go to tap a link, so they tap the wrong thing. Bounce rate spikes. The fixes are exactly the Core Web Vitals: server-render or statically generate the first paint, code-split the bundle, and set image dimensions to stop the shift.",
    scale: "On a personal project, performance is a quick Lighthouse pass before you ship. In production it becomes a routine: a performance budget in CI that fails the build if the bundle grows too large, lazy-loading and code-splitting wired into the framework, and a CDN in front of all static assets. At enterprise scale you collect field Core Web Vitals from real users (Real User Monitoring), set per-team budgets, and treat regressions as bugs with owners. At planet scale (a Google, an Amazon) tens of milliseconds are measured in revenue, edge rendering puts compute next to every user, images are auto-transcoded per device, and an entire org exists to defend the metrics across billions of low-end-device sessions worldwide.",
    related: ["caching", "object-storage-cdn", "rendering", "browser-rendering-pipeline", "the-event-loop"],
  },

  "state-management-patterns": {
    slug: "state-management-patterns",
    title: "State management patterns",
    category: "Web & Frontend",
    color: "amber",
    tagline: "Where a UI keeps its truth — and the ladder from a single component's variable up to one global store the whole app shares.",
    oneLiner: "State management is deciding where each piece of changing data lives and who's allowed to change it — climbing from local state inside one component, to state lifted into a shared parent, to a global store, choosing the smallest scope that still works.",
    what: [
      "A user interface is mostly a function of its **state**: the current data that decides what's on screen — which tab is open, what's in the form, whether you're logged in, the items in the cart. **State management** is the question of *where each piece of that data lives* and *how changes to it flow to the screen*. Get it wrong and you get the classic bugs: two parts of the UI disagreeing, a value that won't update, a tangle nobody can follow.",
      "There's a natural ladder. **Local state** lives inside one component (a `useState` in React) — perfect for a thing only that component cares about, like whether a dropdown is open. When two sibling components need the *same* value, you **lift state up** to their nearest shared parent and pass it down — now there's one source of truth they share. When data is needed all over the app (the logged-in user, the theme, the cart), threading it through every level gets painful ('prop drilling'), so you reach for **global state**: a store any component can read from directly.",
      "Global state itself comes in flavours. The **Flux / Redux** pattern enforces a strict one-way flow: components dispatch **actions** (plain descriptions of what happened), pure functions called **reducers** compute the new state, and components read from the single **store** — making every change traceable. Newer approaches like **signals** (and libraries like Zustand, Jotai, Riverpod) make state reactive and fine-grained: a value 'knows' who depends on it and updates only those parts, often with far less ceremony.",
      "The golden rule cuts across all of it: **keep state as local as possible, and lift it only when sharing forces you to.** Reaching for a global store on day one is the most common over-engineering mistake; so is keeping shared data local and then duplicating it until copies drift apart.",
    ],
    analogy: {
      title: "Where the office keeps a fact",
      body: "Think of a fact like 'today's lunch order.' If only you need it, you keep it on your own desk (local state) — fast, private, nobody else involved. If you and your deskmate both need it, you put it on the shared table between you (lift it up). But if the whole company needs the lunch count — kitchen, accounting, reception — you don't photocopy it onto everyone's desk (copies drift, someone updates one and not the others); you post it on the one notice board everyone reads and only the office manager updates (a global store with controlled writes). Flux is that notice board with a strict rule: changes go through a written request slip (an action) so there's always a paper trail.",
    },
    insideTitle: "The ladder and its rungs",
    inside: [
      { name: "Local state", desc: "Data inside one component. The default — use it until something forces you higher." },
      { name: "Lifted state", desc: "Moved up to the nearest shared parent so siblings read one source of truth, passed down as props." },
      { name: "Global store", desc: "App-wide state any component can read directly, avoiding prop-drilling for truly shared data." },
      { name: "Flux / Redux flow", desc: "Strict one-way data flow: dispatch an action → a reducer computes new state → the store updates → UI reads. Traceable." },
      { name: "Signals / reactive state", desc: "Fine-grained reactive values that auto-update only the parts that depend on them — less boilerplate." },
      { name: "Server-state cache", desc: "Data fetched from an API (React Query, SWR) treated specially — with caching, refetching, and staleness — not as plain UI state." },
    ],
    how: [
      "All of these implement the same core idea: **when state changes, the UI re-derives from it.** In React-style frameworks, changing state triggers a re-render of the components that read it; the virtual DOM diff then makes the minimal real changes. The patterns differ in *who holds the state* and *how a change is announced* — local state notifies just its component, a store notifies every subscriber, signals notify only the exact expressions that read them.",
      "The Flux/Redux flow is strict on purpose. By forcing every change through a dispatched action and a pure reducer, you get a single, replayable history of *what happened* — which makes debugging (time-travel, logging every action), testing (reducers are pure functions), and reasoning about a large app tractable. The cost is boilerplate: actions, reducers, and wiring for every slice of state, which is why many teams have moved to lighter stores or signals where the ceremony isn't worth it.",
      "A subtle but vital split: **client state** vs **server state**. Client state is UI truth you own (is the modal open, what's typed). Server state is a *copy* of data that actually lives in a database — and copies go stale. Treating server data as plain global state leads to manual, error-prone refetching; libraries like React Query model it honestly, with caching, background refetching, and staleness built in. Knowing which kind you have is half of choosing the right tool.",
    ],
    why: [
      "Good state management is what keeps a growing UI coherent: one source of truth means parts of the screen can't disagree, and a clear data flow means you can predict what a change will do. The whole reason these patterns exist is that shared, mutable UI state is where front-end complexity concentrates — tame it and the app stays understandable; lose it and every feature risks a 'why didn't this update?' bug.",
      "The trade-off is ceremony versus clarity at scale. Local state is effortless but doesn't share. A global store shares everything but adds indirection, and Redux specifically adds real boilerplate in exchange for traceability. Over-globalising makes a small app needlessly complex; under-sharing makes a large app a web of duplicated, drifting copies. The art is matching the rung of the ladder to the actual sharing the feature needs — and revisiting it as the app grows.",
    ],
    alternatives: [
      { name: "URL as state", note: "Store sharable, navigable state (filters, current page, search query) in the URL itself — free deep-linking and back-button support, no library needed." },
      { name: "Context (no library)", note: "React's built-in Context shares a value down a subtree without prop-drilling — great for low-frequency global data like theme or user; can cause extra re-renders if overused for fast-changing state." },
      { name: "State machines (XState)", note: "Model state as explicit named states and allowed transitions, making impossible states impossible — excellent for complex flows like checkout or a multi-step form." },
    ],
    whoUses: "Every front-end and mobile developer makes these decisions constantly — React, Vue, Svelte, and Flutter (Riverpod) all have their own answers to the same ladder. It's a defining skill for UI engineers, a frequent source of architecture debate on teams, and a common interview topic. Anyone who's debugged 'the cart count is wrong in the header but right on the page' has lived a state-management bug.",
    bigPicture: "State management is the front-end half of the broader 'one source of truth' principle that runs through the whole system — the same instinct that says a database row, not three caches, owns a fact. It sits on top of the rendering model (state changes drive re-renders through the pipeline) and connects to server-state and live-sync: keeping the client's copy of server data fresh is itself a state-management problem.",
    prereqs: ["state-management", "nextjs"],
    projects: [
      "Build a counter with local `useState`, then add a second component that must show the same count — refactor by lifting state up to the shared parent.",
      "Take an app that prop-drills the logged-in user through five levels and replace it with a Context or a small global store, deleting all the pass-through props.",
      "Wire a filter and search box to store their values in the URL query string, then reload the page and confirm the filters survive — state living outside the component tree.",
    ],
    breaks: "An app keeps the shopping cart as local state in three different components — the header badge, the cart page, and the checkout summary. A user adds an item; only the page that handled the click updates, and the header still shows the old count. Worse, checkout reads its own stale copy and undercharges. The bug is three sources of truth for one fact. The fix is to lift the cart to one shared store everyone reads, so there's a single number that can't disagree with itself.",
    scale: "In a tiny app, local `useState` and a little prop-passing is all you need — adding Redux here is pure overhead. As features grow, a handful of values go global (user, theme, cart) and you adopt a lightweight store plus a server-state library for API data. At enterprise scale, teams standardise patterns across many feature areas, codify which state is client vs server vs URL, and lean on state machines for the gnarliest flows so 'impossible states' can't occur. At planet scale, state management blurs into data-sync architecture: offline-first stores, optimistic updates with rollback, conflict resolution, and real-time sync across millions of clients — the same ladder, now load-bearing for collaboration and correctness across the globe.",
    related: ["state-management", "realtime-sync", "nextjs", "riverpod", "browser-rendering-pipeline"],
  },

  "web-storage": {
    slug: "web-storage",
    title: "Web storage: cookies, localStorage, sessionStorage & IndexedDB",
    category: "Web & Frontend",
    color: "blue",
    tagline: "The four places a browser can keep data on the user's device — what each is for, how big it gets, and which ones an attacker can read.",
    oneLiner: "Browsers offer four ways to store data on the device — cookies (small, sent to the server automatically), localStorage and sessionStorage (simple key-value strings, JS-only), and IndexedDB (a real in-browser database) — and choosing wrong is usually a security or capacity mistake.",
    what: [
      "Web pages are stateless by default — close the tab and everything's gone. **Web storage** is the set of mechanisms a browser provides to *persist* data on the user's own device, so a site can remember you, work offline, or cache data. There are four main options, and they differ on three axes that matter a lot: **size**, **lifetime**, and **who can read them**.",
      "**Cookies** are small (about 4KB each) key-value strings that the browser attaches to every request to the matching site, automatically. That auto-send behaviour is their whole point — it's how a server recognises a logged-in user across requests — and also their main risk. The security flags matter: **HttpOnly** hides a cookie from JavaScript (so a script can't steal it), **Secure** sends it only over HTTPS, and **SameSite** limits when it's sent cross-site (the front-line defence against CSRF).",
      "**localStorage** and **sessionStorage** are the simple twins: a string-only key-value store accessed purely from JavaScript and *never* sent to the server. The difference is lifetime — **localStorage** persists until explicitly cleared (survives restarts); **sessionStorage** lasts only as long as that tab is open. Both hold roughly 5–10MB and are easy to use (`localStorage.setItem`), but synchronous and string-only.",
      "**IndexedDB** is the heavyweight: a real transactional, object-based database inside the browser. It stores structured data (not just strings), handles large amounts (often hundreds of MB or more), and is asynchronous so it doesn't block the page. It's the backbone of serious offline apps — but its API is verbose, so most people use it through a wrapper library.",
    ],
    analogy: {
      title: "What you carry, your desk, and a filing cabinet",
      body: "A cookie is the lanyard badge you wear — small, and you flash it automatically at every door (it's sent on every request), which is convenient but means anyone watching the door knows who you are. localStorage is a sticky-note board at your desk that stays up between visits; sessionStorage is the same board but the cleaners wipe it when you leave for the day (close the tab). IndexedDB is a proper filing cabinet at your desk: it holds folders of structured records, lots of them, and you file and retrieve without ever walking to the front door (the server). You pick based on how much you're storing and whether the doorman needs to see it.",
    },
    insideTitle: "The four stores compared",
    inside: [
      { name: "Cookies", desc: "~4KB strings auto-sent to the server on every request. For auth/sessions. Secure with HttpOnly + Secure + SameSite." },
      { name: "localStorage", desc: "~5–10MB string key-value, JS-only, persists across restarts. Simple, synchronous; never sent to the server." },
      { name: "sessionStorage", desc: "Like localStorage but scoped to one tab and cleared when that tab closes. For transient per-session data." },
      { name: "IndexedDB", desc: "A full async object database in the browser — large, structured, transactional. For offline apps and big caches." },
      { name: "Security flags (cookies)", desc: "HttpOnly (hide from JS), Secure (HTTPS only), SameSite (limit cross-site sending) — the difference between safe and exploitable." },
      { name: "The origin boundary", desc: "All storage is partitioned by origin (scheme + host + port); one site can't read another's storage." },
    ],
    how: [
      "Everything here is scoped to an **origin** — the combination of scheme, host, and port. A script on `app.example.com` can only see storage for that origin, never `evil.com`'s. This same-origin isolation is the bedrock that makes client storage safe enough to use at all; without it, any page could rifle through every other site's data.",
      "Cookies are unique in being **server-aware**: the server sets them with a `Set-Cookie` header and the browser echoes them back on matching requests automatically. That's why they're the natural home for a session token — the server gets it on every request without the front-end doing anything. The flip side is the cookie travels constantly (overhead) and, if not flagged correctly, is exposed to theft (no HttpOnly → readable by injected scripts) or abuse (no SameSite → sent on cross-site requests, enabling CSRF).",
      "localStorage, sessionStorage, and IndexedDB are **JS-only and local** — the server never sees them unless your code explicitly sends the data. localStorage's synchronous API is convenient but blocks the main thread on large reads/writes, so it's wrong for big data; IndexedDB's asynchronous, transactional design exists precisely for that case. The crucial security point: any data reachable by JavaScript is reachable by *malicious* JavaScript injected via XSS. So storing a session token in localStorage means an XSS bug hands the attacker the token outright — which is exactly why auth tokens belong in HttpOnly cookies, not localStorage.",
    ],
    why: [
      "These mechanisms let a site feel stateful and personal: stay logged in, remember preferences, work offline, cache expensive data for instant repeat loads. Without them every visit would start from zero. The variety exists because the needs genuinely differ — a 20-byte session id and a 200MB offline cache shouldn't use the same tool.",
      "The trade-offs are about security and capacity, and they're easy to get wrong. Cookies are powerful but their auto-send behaviour is a liability without the right flags. localStorage is tempting for tokens because it's easy — and it's a textbook XSS-amplification mistake. IndexedDB is capable but heavy to use directly. The right call is matching the store to the data's size and sensitivity: small + server-needed + secret → an HttpOnly cookie; modest + client-only + non-secret → localStorage/sessionStorage; large + structured + offline → IndexedDB.",
    ],
    alternatives: [
      { name: "Server-side sessions", note: "Store almost nothing on the client (just an opaque session id in a cookie) and keep the real state in the server's database/Redis — central control, easy revocation, no client tampering." },
      { name: "Cache Storage API", note: "Part of service workers; stores whole HTTP responses for offline use — the right tool for caching assets and API responses, distinct from IndexedDB's structured data." },
      { name: "In-memory only", note: "Keep sensitive data (like a short-lived access token) only in a JS variable that dies on refresh — smallest attack surface, but nothing survives a reload." },
    ],
    whoUses: "Every web developer chooses among these — for auth (cookies), preferences (localStorage), or offline data (IndexedDB). It's central to security engineers reviewing where tokens live, front-end engineers building offline-capable or PWA experiences, and anyone debugging 'why am I logged out on refresh' or a privacy/consent flow. The cookie flags specifically are a staple of web-security reviews and interviews.",
    bigPicture: "Web storage is where the client keeps its slice of state, sitting directly underneath auth (where the session token lives decides your whole CSRF/XSS posture), state management (persisting UI state across reloads), and PWAs (IndexedDB + Cache Storage are what make offline possible). It's the local-device counterpart to the server's database — and the same 'one source of truth' and security instincts apply.",
    prereqs: ["http-rest", "auth"],
    projects: [
      "Build a 'remember my theme' toggle backed by localStorage, then a 'draft autosave' backed by sessionStorage, and observe the difference when you close vs reload the tab.",
      "Inspect a real site's cookies in DevTools, identify which have HttpOnly/Secure/SameSite set, and explain what each flag is protecting against.",
      "Store and query a few hundred records (e.g. a notes app) in IndexedDB through a small wrapper library, then turn off the network and confirm the data is still there.",
    ],
    breaks: "A team stores the user's JWT in localStorage because it's the easiest place to read it from. Months later a third-party script (or a reflected-input bug) introduces an XSS hole. Because anything in localStorage is plain JavaScript-reachable, a one-line injected script reads every visitor's token and POSTs it to the attacker — full account takeover, no password needed. The same token in an HttpOnly cookie would have been invisible to that script. The storage choice *was* the vulnerability.",
    scale: "On a learning project you might just drop a value in localStorage and move on — fine for a theme toggle. In production you get deliberate: HttpOnly+Secure+SameSite cookies for sessions, localStorage only for non-sensitive UI preferences, IndexedDB for any real offline data. At enterprise scale, storage choices are governed — security reviews enforce 'no secrets in localStorage,' privacy/consent rules gate what you may persist, and storage is partitioned and audited. At planet scale, client storage becomes part of a sync architecture: IndexedDB as a local replica, conflict resolution against the server, storage-quota management across billions of devices, and browser-level partitioning changes (third-party cookie deprecation) that force whole industries to re-architect how they identify and remember users.",
    related: ["auth", "web-security", "http-rest", "progressive-web-apps", "offline-first"],
  },

  "progressive-web-apps": {
    slug: "progressive-web-apps",
    title: "Progressive Web Apps (PWAs)",
    category: "Web & Frontend",
    color: "purple",
    tagline: "Turning a website into something that installs to the home screen, works offline, and pushes notifications — using a background script the browser keeps even when the tab is closed.",
    oneLiner: "A PWA is an ordinary website upgraded with a service worker (a background script that intercepts network requests) and a manifest (install metadata) so it can work offline, be installed like an app, and receive push notifications — without an app store.",
    what: [
      "A normal website needs the network for everything and disappears when you close the tab. A **Progressive Web App** is a regular site that *progressively* adds app-like superpowers when the browser supports them: it can be **installed** to the home screen, **work offline**, and receive **push notifications** — closing much of the gap with native mobile apps, while still being just a URL you can open in any browser.",
      "The engine that makes it possible is the **service worker**: a JavaScript file the browser runs in the background, separate from any page, that *stays alive even when no tab is open*. Its key power is **intercepting network requests** — it sits between your page and the network like a programmable proxy, so it can answer requests from a local cache (offline), update caches in the background, and receive push messages from a server.",
      "Two more pieces complete the picture. The **web app manifest** is a small JSON file declaring the app's name, icons, colours, and how it should launch (e.g. full-screen, no browser chrome) — this is what lets the browser offer 'Add to Home Screen' and open it like a standalone app. And **HTTPS is mandatory**: because a service worker can intercept and rewrite all traffic, browsers only allow it on secure origins, so a hijacked connection can't install a malicious one.",
      "The 'progressive' in the name is a philosophy: the site works for everyone as a plain web page, and *layers on* the enhancements where they're available. A browser without service-worker support just gets the normal site — nothing breaks.",
    ],
    analogy: {
      title: "A pop-up shop that earns a permanent storefront",
      body: "An ordinary website is a pop-up stall — it only exists while you're standing in front of it (the tab is open) and needs a constant supply run to the warehouse (the network) for everything. A service worker is like hiring a stockroom clerk who stays on-site after hours: they keep a shelf of your most-needed goods (the cache) so customers get served instantly even when the warehouse road is closed (offline), restock quietly in the background, and accept deliveries (push notifications) when you're not even there. The manifest is the signage and keys that let you put your logo on the door and open as a real, installable shop — no mall (app store) approval required.",
    },
    insideTitle: "The building blocks",
    inside: [
      { name: "Service worker", desc: "A background script that intercepts network requests, serves from cache, updates in the background, and handles push — alive even with no tab open." },
      { name: "Web app manifest", desc: "A JSON file declaring name, icons, theme colour, and launch mode — enables install and standalone launching." },
      { name: "Cache Storage API", desc: "Where the service worker stores whole HTTP responses (HTML, JS, images) to serve offline or instantly." },
      { name: "Caching strategy", desc: "The rule the worker follows: cache-first (offline-first speed), network-first (freshness), or stale-while-revalidate (instant + background update)." },
      { name: "Push & notifications", desc: "Subscribe to a push service so the server can wake the worker and show a notification even when the app is closed." },
      { name: "HTTPS requirement", desc: "Service workers run only on secure origins, because they can intercept all traffic — a hard safety gate." },
    ],
    how: [
      "A service worker has a lifecycle: it's **registered** by a page, then **installed** (a good time to pre-cache the app's shell — its core HTML/CSS/JS), then **activated** (clean up old caches). Once active, it runs an event-driven loop: it wakes on a `fetch` event (a page made a request) and you decide how to answer it; it wakes on a `push` event to show a notification; it sleeps otherwise to save battery. It cannot touch the DOM directly — it talks to pages by messaging — because it isn't tied to any one page.",
      "The heart of offline support is the **fetch handler** and a chosen **caching strategy**. **Cache-first** serves from cache and only hits the network on a miss — fastest and works offline, but can serve stale content. **Network-first** tries the network and falls back to cache — fresh when online, resilient when not. **Stale-while-revalidate** serves the cached copy instantly *and* fetches a fresh one in the background for next time — a popular balance. Pre-caching the **app shell** (the static skeleton) plus caching API responses is what makes a PWA load instantly and survive going offline.",
      "Updates are the famous gotcha. When you redeploy, the browser fetches the new service worker but, by default, the new version **waits** until all tabs using the old one are closed before taking over — so users can keep running stale code longer than you expect. Handling this gracefully (prompting 'a new version is available, reload') is a core part of building a reliable PWA. Push works by the page subscribing to a push service and sending the resulting subscription to your server; the server later sends a message that wakes the worker to display a notification.",
    ],
    why: [
      "PWAs give you a single codebase that reaches everyone via a URL yet behaves like an installed app — no app-store gatekeeping, fees, or review delays, and instant updates (just deploy). For content and commerce, offline support and instant repeat loads improve engagement and reach, especially on flaky networks and budget devices. It's often the cheapest way to get an 'app-like' presence without building separate iOS and Android apps.",
      "The trade-offs are reach and capability. iOS historically lags on PWA features (limited push, install quirks), so coverage isn't uniform. Service workers add real complexity — caching bugs and the update lifecycle are notorious sources of 'why are users seeing old code?' incidents. And a PWA still can't match a native app's deepest device integration. The decision is usually PWA when broad reach, instant updates, and offline-ish behaviour matter more than the last 10% of native power.",
    ],
    alternatives: [
      { name: "Native apps", note: "Built per platform (Swift, Kotlin); deepest device access and best performance, but two codebases, store review, and slow update cycles." },
      { name: "Cross-platform frameworks (Flutter, React Native)", note: "One codebase compiled to real native apps — more device power than a PWA, still distributed through app stores." },
      { name: "Plain website + Cache headers", note: "If you don't need offline, install, or push, ordinary HTTP caching gives you speed with none of the service-worker complexity." },
    ],
    whoUses: "Front-end and full-stack engineers building installable, offline-capable web experiences; product teams who want app-like reach without native development; and companies targeting markets with intermittent connectivity. Big examples include Twitter Lite, Starbucks, Spotify's web player, and many news and commerce sites. Anyone who's seen an 'Install app' prompt in their browser address bar has met a PWA.",
    bigPicture: "A PWA is the convergence point of several web ideas: the service worker is a programmable layer over the network, Cache Storage and IndexedDB provide its offline data, the manifest plugs into the OS, and HTTPS underpins the whole thing. It builds directly on web storage and offline-first thinking, and it's how a web app climbs toward the territory the native Flutter app occupies — same goals (offline, installable, push), reached from the browser side.",
    prereqs: ["how-the-internet-works", "web-storage"],
    projects: [
      "Add a manifest and a minimal service worker to a static site, then use DevTools to install it to your desktop and launch it as a standalone window.",
      "Implement a cache-first service worker that pre-caches the app shell, then switch the network off in DevTools and confirm the page still loads.",
      "Wire up the update flow: deploy a change, detect the waiting service worker, and show the user a 'new version available — reload' prompt.",
    ],
    breaks: "A team ships a PWA with an aggressive cache-first service worker and no update strategy. They deploy a critical bug fix — but because the old service worker keeps serving the cached app shell and only steps aside once every tab closes, a chunk of users keep running the broken version for days, with no way to force the refresh. Support tickets pour in for a bug that 'was already fixed.' The lesson: caching strategy and the update lifecycle are the hard, dangerous part of PWAs, and must be designed deliberately, not left on defaults.",
    scale: "When learning, a PWA is a manifest plus a tiny service worker that caches a few files — enough to earn the install prompt. In production you adopt a proven caching library (Workbox), pick strategies per resource type, handle updates gracefully, and test offline behaviour as a real feature. At enterprise scale, the service worker becomes load-bearing infrastructure: versioned caches, careful cache invalidation tied to deploys, push-notification campaigns, and monitoring for stale-version incidents. At planet scale, PWAs serve as the low-bandwidth front door for emerging markets (think 'Lite' apps) — engineered to install small, run offline by default, sync opportunistically, and degrade gracefully across an enormous range of devices and network conditions worldwide.",
    related: ["web-storage", "offline-first", "caching", "how-the-internet-works", "flutter"],
  },
};
