// The curriculum grid — the spine of Software Universe.
//   Horizontal axis = DOMAINS (breadth: every field a software engineer touches)
//   Vertical axis   = DEPTH   (each topic climbs local → production → enterprise → MNC)
//
// `status: "live"` topics link to existing content; `"soon"` are planned cells
// on the map (honest about what's built vs coming). This single source feeds the
// /learn map, cross-links, and the AI assistant's topic context.

export const DEPTH_LADDER = [
  { id: "local", label: "Local", blurb: "One machine, one user — make it work." },
  { id: "prod", label: "Production", blurb: "Real users, real money — make it correct & safe." },
  { id: "enterprise", label: "Enterprise", blurb: "Many teams, many services — make it maintainable." },
  { id: "mnc", label: "Planet-scale", blurb: "Millions of users — make it survive anything." },
];

export const DOMAINS = [
  {
    id: "foundations",
    title: "Foundations",
    tint: "brand",
    tagline: "How any software system fits together — and the journey of a single request through it.",
    topics: [
      { t: "What a program is", href: "/codex/tech/what-is-a-program", status: "live" },
      { t: "Variables & memory", href: "/codex/tech/variables-and-memory", status: "live" },
      { t: "How code runs (compilers & interpreters)", href: "/codex/tech/how-code-runs", status: "live" },
      { t: "How a CPU works", href: "/codex/tech/how-a-cpu-works", status: "live" },
      { t: "Binary & how numbers are stored", href: "/codex/tech/binary-and-number-representation", status: "live" },
      { t: "Character encoding (ASCII, Unicode, UTF-8)", href: "/codex/tech/character-encoding", status: "live" },
      { t: "Type systems", href: "/codex/tech/type-systems", status: "live" },
      { t: "Garbage collection", href: "/codex/tech/garbage-collection", status: "live" },
      { t: "How it all fits together", href: "/codex/foundations", status: "live" },
      { t: "Layers & separation of concerns", href: "/codex/layers-and-separation", status: "live" },
      { t: "State — one source of truth", href: "/codex/state-management", status: "live" },
      { t: "The journey of a request (visual)", href: "/simulator/order-journey", status: "live" },
      { t: "The whole-system roadmap", href: "/roadmap", status: "live" },
    ],
  },
  {
    id: "mobile",
    title: "Mobile",
    tint: "purple",
    tagline: "Building the app the user actually taps — Flutter, Dart, state, and premium motion.",
    topics: [
      { t: "Your Flutter app, layer by layer", href: "/codex/flutter-app", status: "live" },
      { t: "Dart — the language", href: "/codex/tech/dart", status: "live" },
      { t: "Flutter — drawing every pixel", href: "/codex/tech/flutter", status: "live" },
      { t: "Riverpod — shared state", href: "/codex/tech/riverpod", status: "live" },
      { t: "Dio — the network client", href: "/codex/tech/dio", status: "live" },
      { t: "The burger builder & motion engine", href: "/codex/burger-builder", status: "live" },
      { t: "Offline-first & sync", href: "/codex/tech/offline-first", status: "live" },
      { t: "Navigation — stacks, tabs & deep links", href: "/codex/tech/mobile-navigation", status: "live" },
      { t: "Animations — native 60fps motion", href: "/codex/tech/mobile-animations", status: "live" },
      { t: "App performance on real devices", href: "/codex/tech/app-performance", status: "live" },
      { t: "Shipping to the app stores", href: "/codex/tech/app-release-process", status: "live" },
    ],
  },
  {
    id: "web",
    title: "Web & Frontend",
    tint: "blue",
    tagline: "How the browser talks to servers, and how modern web apps are built and rendered.",
    topics: [
      { t: "HTTP & REST — the grammar of the web", href: "/codex/tech/http-rest", status: "live" },
      { t: "JSON — the shape data travels in", href: "/codex/tech/json", status: "live" },
      { t: "Next.js & React", href: "/codex/tech/nextjs", status: "live" },
      { t: "Refine — admin scaffolding", href: "/codex/tech/refine", status: "live" },
      { t: "The admin panel — the control room", href: "/codex/admin-panel", status: "live" },
      { t: "Rendering: CSR vs SSR vs SSG", href: "/codex/tech/rendering", status: "live" },
      { t: "CSS, layout & accessibility", href: "/codex/tech/css-accessibility", status: "live" },
      { t: "The browser rendering pipeline", href: "/codex/tech/browser-rendering-pipeline", status: "live" },
      { t: "The JavaScript event loop", href: "/codex/tech/the-event-loop", status: "live" },
      { t: "Web performance (Core Web Vitals)", href: "/codex/tech/web-performance", status: "live" },
      { t: "State management patterns", href: "/codex/tech/state-management-patterns", status: "live" },
      { t: "Web storage — cookies, localStorage, IndexedDB", href: "/codex/tech/web-storage", status: "live" },
      { t: "Progressive Web Apps", href: "/codex/tech/progressive-web-apps", status: "live" },
    ],
  },
  {
    id: "backend",
    title: "Backend & APIs",
    tint: "amber",
    tagline: "The brain: catching requests, running guards, doing the real work, and proving identity.",
    topics: [
      { t: "The backend — the brain", href: "/codex/backend", status: "live" },
      { t: "Node.js — JS on the server", href: "/codex/tech/nodejs", status: "live" },
      { t: "Express — routes & middleware", href: "/codex/tech/express", status: "live" },
      { t: "Auth — JWT, cookies & CSRF", href: "/codex/tech/auth", status: "live" },
      { t: "Live sync (SSE)", href: "/codex/tech/realtime-sync", status: "live" },
      { t: "Rate limiting & API gateways", href: "/codex/tech/rate-limiting", status: "live" },
      { t: "gRPC, GraphQL & WebSockets", href: "/codex/tech/api-styles", status: "live" },
      { t: "API gateways", href: "/codex/tech/api-gateways", status: "live" },
      { t: "Caching strategies", href: "/codex/tech/caching-strategies", status: "live" },
      { t: "Connection pooling", href: "/codex/tech/connection-pooling", status: "live" },
      { t: "Webhooks", href: "/codex/tech/webhooks", status: "live" },
    ],
  },
  {
    id: "databases",
    title: "Databases",
    tint: "teal",
    tagline: "The permanent memory: linked tables, exact money, all-or-nothing writes, and fast lookups.",
    topics: [
      { t: "The database — the memory", href: "/codex/database", status: "live" },
      { t: "PostgreSQL", href: "/codex/tech/postgresql", status: "live" },
      { t: "Prisma — the ORM", href: "/codex/tech/prisma", status: "live" },
      { t: "SQL & indexes", href: "/codex/tech/sql", status: "live" },
      { t: "Transactions & ACID", href: "/codex/tech/transactions", status: "live" },
      { t: "B-Tree indexing (visual)", href: "/simulator/visualgo", status: "live" },
      { t: "Sharding, replicas & NoSQL", href: "/codex/tech/sharding", status: "live" },
      { t: "Data modelling", href: "/codex/tech/data-modeling", status: "live" },
      { t: "OLTP vs OLAP", href: "/codex/tech/oltp-vs-olap", status: "live" },
      { t: "Database isolation levels", href: "/codex/tech/database-isolation-levels", status: "live" },
    ],
  },
  {
    id: "system-design",
    title: "System Design & Scale",
    tint: "pink",
    tagline: "From 10 users to a million: caching, queues, consensus, and staying correct when networks fail.",
    topics: [
      { t: "Scale — 10 to a million users", href: "/codex/scale", status: "live" },
      { t: "Big systems — payments, orders, loyalty", href: "/codex/big-systems", status: "live" },
      { t: "Idempotency", href: "/codex/tech/idempotency", status: "live" },
      { t: "State machines", href: "/codex/tech/state-machines", status: "live" },
      { t: "Ledgers", href: "/codex/tech/ledgers", status: "live" },
      { t: "Caching", href: "/codex/tech/caching", status: "live" },
      { t: "Concurrency & races", href: "/codex/tech/concurrency", status: "live" },
      { t: "Scaling sandbox (visual)", href: "/simulator/scaling", status: "live" },
      { t: "Dependency & blast-radius (visual)", href: "/simulator/dependency-explorer", status: "live" },
      { t: "Raft consensus (visual)", href: "/simulator/raft", status: "live" },
      { t: "Queues, backpressure & sagas", href: "/codex/tech/message-queues", status: "live" },
    ],
  },
  {
    id: "dsa",
    title: "DSA & Problem Solving",
    tint: "brand",
    tagline: "The NeetCode-style lab: recognize the pattern, reach the optimal approach, handle every twist.",
    topics: [
      { t: "Enter the DSA Lab", href: "/dsa", status: "live" },
      { t: "Two Pointers", href: "/dsa", status: "live" },
      { t: "Sliding Window", href: "/dsa", status: "live" },
      { t: "Binary Search", href: "/dsa", status: "live" },
      { t: "Trees, BFS & DFS", href: "/dsa", status: "live" },
      { t: "Dynamic Programming", href: "/dsa", status: "live" },
      { t: "Graphs", href: "/dsa", status: "live" },
      { t: "Heaps · Priority Queue", href: "/dsa", status: "live" },
    ],
  },
  {
    id: "devops",
    title: "DevOps & Deployment",
    tint: "teal",
    tagline: "Shipping safely and operating in production: pipelines, containers, environments, rollbacks.",
    topics: [
      { t: "Deployment & ops — going live", href: "/codex/deployment", status: "live" },
      { t: "CI/CD pipelines", href: "/codex/tech/ci-cd", status: "live" },
      { t: "Docker & containers", href: "/codex/tech/docker", status: "live" },
      { t: "Observability — logs, metrics, traces", href: "/codex/tech/observability", status: "live" },
      { t: "Kubernetes & orchestration", href: "/codex/tech/kubernetes", status: "live" },
      { t: "Incident response (War Room)", href: "/universe", status: "live" },
      { t: "Deployment strategies — blue-green, canary, rolling", href: "/codex/tech/deployment-strategies", status: "live" },
      { t: "Infrastructure as code", href: "/codex/tech/infrastructure-as-code", status: "live" },
      { t: "Feature flags", href: "/codex/tech/feature-flags", status: "live" },
    ],
  },
  {
    id: "cloud",
    title: "Cloud",
    tint: "blue",
    tagline: "Renting the world's computers: compute, storage, networking, and managed services.",
    topics: [
      { t: "What 'the cloud' actually is", href: "/codex/tech/cloud", status: "live" },
      { t: "Compute: VMs, containers, serverless", href: "/codex/tech/cloud-compute", status: "live" },
      { t: "Object storage & CDNs", href: "/codex/tech/object-storage-cdn", status: "live" },
      { t: "Managed databases & queues", href: "/codex/tech/managed-services", status: "live" },
      { t: "Cost, regions & availability zones", href: "/codex/tech/cloud-cost-regions", status: "live" },
      { t: "Cloud networking — VPCs, subnets, security groups", href: "/codex/tech/cloud-networking", status: "live" },
      { t: "Edge computing — code near the user", href: "/codex/tech/edge-computing", status: "live" },
    ],
  },
  {
    id: "ai-ml",
    title: "AI / ML",
    tint: "purple",
    tagline: "How modern AI works under the hood — from tensors to transformers to RAG.",
    topics: [
      { t: "LLM transformer internals (visual)", href: "/simulator/llm", status: "live" },
      { t: "What a neural network really computes", href: "/codex/tech/neural-networks", status: "live" },
      { t: "Embeddings & vector search", href: "/codex/tech/embeddings", status: "live" },
      { t: "RAG — grounding an LLM", href: "/codex/tech/rag", status: "live" },
      { t: "Training vs inference & cost", href: "/codex/tech/training-vs-inference", status: "live" },
      { t: "Prompt engineering", href: "/codex/tech/prompt-engineering", status: "live" },
      { t: "Vector databases & ANN search", href: "/codex/tech/vector-databases", status: "live" },
      { t: "AI agents — LLMs that use tools", href: "/codex/tech/ai-agents", status: "live" },
      { t: "RAG vs fine-tuning", href: "/codex/tech/rag-vs-fine-tuning", status: "live" },
    ],
  },
  {
    id: "security",
    title: "Security",
    tint: "pink",
    tagline: "Proving identity, guarding requests, and the failure modes attackers exploit.",
    topics: [
      { t: "Auth — JWT, cookies & CSRF", href: "/codex/tech/auth", status: "live" },
      { t: "Security world (Burger Farm)", href: "/worlds/security", status: "live" },
      { t: "Common attacks: XSS, SQLi, SSRF", href: "/codex/tech/web-security", status: "live" },
      { t: "Secrets, rotation & least privilege", href: "/codex/tech/secrets-management", status: "live" },
      { t: "Threat modelling", href: "/codex/tech/threat-modelling", status: "live" },
      { t: "The OWASP Top 10", href: "/codex/tech/owasp-top-10", status: "live" },
      { t: "Cryptography basics", href: "/codex/tech/cryptography-basics", status: "live" },
      { t: "OAuth & OpenID Connect", href: "/codex/tech/oauth-and-openid", status: "live" },
    ],
  },
  {
    id: "cs",
    title: "Computer Science",
    tint: "purple",
    tagline: "Data structures & algorithms from the ground up — the arrangements and recipes behind every fast program.",
    topics: [
      { t: "Data structures, mapped", href: "/codex/tech/data-structures-overview", status: "live" },
      { t: "Arrays & strings", href: "/codex/tech/arrays-and-strings", status: "live" },
      { t: "Linked lists", href: "/codex/tech/linked-lists", status: "live" },
      { t: "Stacks & queues", href: "/codex/tech/stacks-and-queues", status: "live" },
      { t: "Hash tables & maps", href: "/codex/tech/hash-tables", status: "live" },
      { t: "Trees & binary search trees", href: "/codex/tech/trees-and-bsts", status: "live" },
      { t: "Graphs — BFS & DFS", href: "/codex/tech/graphs", status: "live" },
      { t: "Heaps & priority queues", href: "/codex/tech/heaps-priority-queues", status: "live" },
      { t: "Recursion & backtracking", href: "/codex/tech/recursion-and-backtracking", status: "live" },
      { t: "Dynamic programming", href: "/codex/tech/dynamic-programming", status: "live" },
      { t: "Sorting & searching", href: "/codex/tech/sorting-and-searching", status: "live" },
      { t: "Big-O notation", href: "/codex/tech/big-o-notation", status: "live" },
      { t: "Discrete math for programmers", href: "/codex/tech/discrete-math-for-programmers", status: "live" },
      { t: "Probability for programmers", href: "/codex/tech/probability-for-programmers", status: "live" },
    ],
  },
  {
    id: "systems",
    title: "Systems & the Machine",
    tint: "blue",
    tagline: "What it really means to run a program: processes, threads, memory, and the OS sharing one machine safely.",
    topics: [
      { t: "Processes & threads", href: "/codex/tech/processes-and-threads", status: "live" },
      { t: "Memory: the stack & the heap", href: "/codex/tech/memory-stack-heap", status: "live" },
      { t: "Locks, mutexes & semaphores", href: "/codex/tech/concurrency-primitives", status: "live" },
      { t: "What an operating system does", href: "/codex/tech/how-an-os-works", status: "live" },
      { t: "Concurrency & races", href: "/codex/tech/concurrency", status: "live" },
    ],
  },
  {
    id: "networking",
    title: "Networking & Distributed Systems",
    tint: "teal",
    tagline: "How data crosses the planet and how unreliable machines agree: packets, TLS, DNS, replication, and consensus.",
    topics: [
      { t: "How the internet works", href: "/codex/tech/how-the-internet-works", status: "live" },
      { t: "TCP vs UDP", href: "/codex/tech/tcp-vs-udp", status: "live" },
      { t: "How HTTPS / TLS works", href: "/codex/tech/tls-https", status: "live" },
      { t: "DNS, in depth", href: "/codex/tech/dns-deep", status: "live" },
      { t: "Load balancing", href: "/codex/tech/load-balancing", status: "live" },
      { t: "Consistency models", href: "/codex/tech/consistency-models", status: "live" },
      { t: "Replication & partitioning", href: "/codex/tech/replication-and-partitioning", status: "live" },
      { t: "Distributed consensus (Raft/Paxos)", href: "/codex/tech/distributed-consensus", status: "live" },
    ],
  },
  {
    id: "craft",
    title: "Software Craft",
    tint: "amber",
    tagline: "The habits that separate code that works from code a team can live with — patterns, principles, testing, and how teams ship.",
    topics: [
      { t: "Design patterns", href: "/codex/tech/design-patterns", status: "live" },
      { t: "The SOLID principles", href: "/codex/tech/solid-principles", status: "live" },
      { t: "Clean code & refactoring", href: "/codex/tech/clean-code-refactoring", status: "live" },
      { t: "OOP vs functional", href: "/codex/tech/oop-vs-functional", status: "live" },
      { t: "Testing strategies", href: "/codex/tech/testing-strategies", status: "live" },
      { t: "Test-driven development", href: "/codex/tech/test-driven-development", status: "live" },
      { t: "Version control with Git", href: "/codex/tech/version-control-git", status: "live" },
      { t: "Code review", href: "/codex/tech/code-review", status: "live" },
      { t: "Agile & Scrum", href: "/codex/tech/agile-and-scrum", status: "live" },
    ],
  },
  {
    id: "sysdesign",
    title: "System Design Interviews",
    tint: "pink",
    tagline: "Turning ‘design Twitter' from a panic into a framework — and the data pipelines feeding it all.",
    topics: [
      { t: "The system-design interview", href: "/codex/tech/system-design-interview", status: "live" },
      { t: "Design a URL shortener", href: "/codex/tech/design-a-url-shortener", status: "live" },
      { t: "Design a news feed", href: "/codex/tech/design-a-news-feed", status: "live" },
      { t: "Design a chat app", href: "/codex/tech/design-a-chat-app", status: "live" },
      { t: "Data engineering basics", href: "/codex/tech/data-engineering-basics", status: "live" },
    ],
  },
  {
    id: "data-eng",
    title: "Data Engineering",
    tint: "teal",
    tagline: "Moving, transforming, and storing data at scale: pipelines, streams, and the warehouses analytics lives in.",
    topics: [
      { t: "Data engineering basics", href: "/codex/tech/data-engineering-basics", status: "live" },
      { t: "OLTP vs OLAP", href: "/codex/tech/oltp-vs-olap", status: "live" },
      { t: "ETL & data pipelines", href: "/codex/tech/etl-pipelines", status: "live" },
      { t: "Stream processing — batch vs stream", href: "/codex/tech/stream-processing", status: "live" },
      { t: "Kafka & event streaming", href: "/codex/tech/kafka-and-event-streaming", status: "live" },
      { t: "Data lakes, warehouses & lakehouses", href: "/codex/tech/data-lakes-and-warehouses", status: "live" },
    ],
  },
];

// How far each domain currently climbs the four-tier ladder (local →
// production → enterprise → planet-scale), as a % per tier. Drives the
// Editorial Learn Map's depth bars — an honest read of how deep each domain
// goes today, not just how many topics exist.
export const DOMAIN_LADDER = {
  foundations: [100, 80, 55, 30],
  mobile: [100, 70, 40, 15],
  web: [100, 90, 70, 45],
  backend: [100, 95, 75, 50],
  databases: [100, 85, 60, 35],
  "system-design": [85, 75, 60, 45],
  dsa: [100, 70, 40, 10],
  devops: [100, 75, 50, 25],
  cloud: [65, 40, 20, 8],
  "ai-ml": [80, 55, 30, 12],
  security: [85, 60, 35, 15],
  cs: [100, 70, 40, 20],
  systems: [100, 75, 45, 20],
  networking: [90, 80, 65, 45],
  craft: [100, 85, 60, 30],
  sysdesign: [90, 75, 55, 35],
  "data-eng": [90, 75, 50, 25],
};

// Quick stats for the map header.
export const CURRICULUM_STATS = (() => {
  let live = 0, soon = 0;
  for (const d of DOMAINS) for (const t of d.topics) (t.status === "live" ? live++ : soon++);
  return { domains: DOMAINS.length, live, soon, total: live + soon };
})();
