// Plain-language definitions for every piece of jargon, so a doubt can be
// cleared inline (see components/Term.jsx). Keep each `def` to 1–2 sentences a
// total beginner can understand. `more` is an optional second layer.
// Usage in content:  <Term id="api">API</Term>   or   <Term def="...">x</Term>

export const GLOSSARY = {
  // ── the big picture ──
  api: { term: "API", def: "A fixed menu of requests one program offers to another. The app uses the backend's API to ask for the menu, place orders, and so on — it can only ask for things on the menu." },
  backend: { term: "Backend", def: "The program running on a server that does the real work and enforces the rules — the 'brain'. The app can't be trusted; the backend can." },
  frontend: { term: "Frontend", def: "The part a person actually sees and touches — here, the mobile app. Its job is to show things and ask for things." },
  server: { term: "Server", def: "A computer in a data centre that runs all the time and answers requests over the internet. Your backend runs on one." },
  client: { term: "Client", def: "Whoever is making the request — usually the app on a customer's phone. 'Never trust the client' means the phone can be tampered with, so the backend re-checks everything." },
  database: { term: "Database", def: "The part that remembers things permanently — through restarts and crashes. Every order and customer lives here." },

  // ── database ──
  table: { term: "Table", def: "One kind of thing in the database, like a strict spreadsheet. The Order table holds all orders, one per row." },
  row: { term: "Row", def: "One single item in a table — one order, one user." },
  column: { term: "Column", def: "One fact about each row — an order's total, its status." },
  "foreign-key": { term: "Foreign key", def: "A column that points at a row in another table. An order's user_id points at the User who placed it — that's how tables link together." },
  "primary-key": { term: "Primary key", def: "The unique id that identifies one row, so you can always find exactly it." },
  index: { term: "Index", def: "A pre-sorted lookup, like the index at the back of a book. It lets the database jump straight to matching rows instead of reading every one." },
  query: { term: "Query", def: "A question you ask the database — 'give me this store's pending orders'." },
  sql: { term: "SQL", def: "The language for asking a relational database questions. You describe what you want; the database figures out how to get it." },
  transaction: { term: "Transaction", def: "A group of writes that all succeed together or all undo together. There's no half-finished state — the bedrock of handling money safely." },
  acid: { term: "ACID", def: "Four guarantees a serious database makes: writes are all-or-nothing, rules are never left broken, simultaneous work doesn't collide, and once saved it survives a crash." },
  migration: { term: "Migration", def: "A versioned, repeatable change to the database's shape (a new column or table), so the structure evolves safely instead of by hand." },
  orm: { term: "ORM", def: "A translator between your code's objects and the database's rows, so you read/write data without hand-writing SQL. Prisma is the one here." },
  decimal: { term: "Decimal", def: "An exact number type used for money, so amounts like ₹0.10 are stored precisely — unlike ordinary computer 'floats', which can't." },
  schema: { term: "Schema", def: "The blueprint that describes every table, column, and link in the database. Here it's one file: schema.prisma." },
  "referential-integrity": { term: "Referential integrity", def: "The database's promise that a link always points at something real — you can't have an order item for a product that doesn't exist." },

  // ── the web in between ──
  http: { term: "HTTP", def: "The request-and-reply language of the web. The app sends a request; the backend sends back a response. The app always asks first." },
  rest: { term: "REST", def: "A tidy convention for organising a web API around 'resources' (orders, products) addressed by clean URLs and standard verbs (GET to read, POST to create)." },
  endpoint: { term: "Endpoint", def: "One specific address + action in an API, like 'GET /api/v1/menu' — a single thing you can ask for." },
  request: { term: "Request", def: "A message the app sends to the backend asking for something or sending something." },
  response: { term: "Response", def: "The backend's reply to a request — the data, plus a status code saying how it went." },
  json: { term: "JSON", def: "A simple text way to write down structured data (objects and lists), understood by every language. It's the shape data travels in." },
  jwt: { term: "JWT", def: "A 'JSON Web Token' — a tamper-proof badge the backend issues at login that says 'this is who I am', signed with a secret only the server knows." },
  cookie: { term: "Cookie", def: "A small piece of data the browser stores and sends back automatically on each request — here it carries your signed login token." },
  httponly: { term: "httpOnly", def: "A cookie setting meaning JavaScript on the page cannot read it. So even a malicious injected script can't steal your login." },
  csrf: { term: "CSRF", def: "Cross-Site Request Forgery — an attack where another website quietly fires a request to your backend riding your cookie. A CSRF token blocks it." },
  token: { term: "Token", def: "A small string that stands in for something — proof of who you are, or a one-time key. Tokens here include the login JWT and the CSRF token." },
  header: { term: "Header", def: "Extra info attached to a request or response — the auth cookie, the content type, a request id — sitting alongside the main data." },
  "status-code": { term: "Status code", def: "A number in the reply saying how it went: 200 OK, 401 not logged in, 404 not found, 500 the server broke." },
  stateless: { term: "Stateless", def: "The backend keeps no memory of you between requests — your identity rides in your token each time. That's what lets many copies of it run at once." },
  session: { term: "Session", def: "The idea of 'you, currently logged in'. Here it's carried in a signed cookie rather than stored on the server." },
  sse: { term: "SSE", def: "Server-Sent Events — one long-lived connection the server uses to push small 'something changed' nudges to the app, so the screen can update live." },
  webhook: { term: "Webhook", def: "When an outside service (like a payment gateway) calls your backend to tell it something happened, instead of you having to keep asking." },

  // ── the app ──
  flutter: { term: "Flutter", def: "The toolkit the app is built with. It draws every pixel itself, so the app looks identical on iPhone and Android from one codebase." },
  widget: { term: "Widget", def: "Flutter's building block. Everything on screen is a widget, and screens are just bigger widgets made of smaller ones — like Lego." },
  dart: { term: "Dart", def: "The programming language the app is written in — typed and 'null-safe', designed to pair with Flutter." },
  state: { term: "State", def: "Anything that can change while the app is open — what's in your cart, which filter is on. Managing it well is what keeps the screen consistent." },
  provider: { term: "Provider", def: "In Riverpod, a named place that holds a piece of shared state (like the cart) so any part of the screen can read the same truth." },
  riverpod: { term: "Riverpod", def: "The library the app uses to hold and share state, so different parts of the screen never disagree about the cart or the filters." },
  reactive: { term: "Reactive", def: "When something recomputes itself automatically the moment its inputs change — change one value and the screen redraws, with no manual syncing." },
  repository: { term: "Repository", def: "The one place that knows how to fetch a kind of data (the menu). Screens ask it for 'the menu' without knowing any URLs." },
  "dependency-injection": { term: "Dependency injection", def: "Instead of a piece of code creating its own tools, it's handed them. That makes it easy to swap a real tool for a fake one in tests." },
  interceptor: { term: "Interceptor", def: "Code that runs automatically on every network request/response — attaching the login cookie, adding a trace id, retrying a blip — so no screen has to." },
  dio: { term: "Dio", def: "The app's single network client. Every request to the backend goes through it, which is where interceptors do their work." },
  "null-safety": { term: "Null safety", def: "A language feature that forces you to say whether a value can be 'nothing'. It kills the classic 'it was empty and the app crashed' bug." },

  // ── the backend ──
  nodejs: { term: "Node.js", def: "The thing that lets JavaScript run on a server. Your backend is a Node program. It's great at handling many requests that are mostly waiting." },
  express: { term: "Express", def: "A small framework for Node that maps each URL to the right code and runs 'middleware' guards along the way." },
  middleware: { term: "Middleware", def: "Code that runs before the main handler, on every matching request — checking auth, verifying a CSRF token — and can stop a bad request cold." },
  route: { term: "Route", def: "The rule that says 'a request to this URL with this method runs this function'. The front desk of the backend." },
  service: { term: "Service", def: "Where the real logic lives (fetch the catalogue, apply prices). Routes stay thin and call services, so the logic is testable on its own." },
  "event-loop": { term: "Event loop", def: "Node's single line of work that never sits idle waiting. It hands off slow jobs and serves other requests meanwhile — like one waiter juggling many tables." },

  // ── cross-cutting logic ──
  idempotency: { term: "Idempotency", def: "Doing something twice has the same effect as doing it once. A retried 'place order' is recognised as a repeat and charges you only once." },
  ledger: { term: "Ledger", def: "Tracking points or money as an append-only list of every movement (like a bank statement), so the balance is the running total and nothing can be lost." },
  "append-only": { term: "Append-only", def: "You only ever add new rows, never edit or delete old ones. That's what makes a history trustworthy — it can't be quietly rewritten." },
  "state-machine": { term: "State machine", def: "A thing that's always in exactly one of a fixed set of states, where only certain moves are allowed — so impossible situations can't happen." },
  "optimistic-concurrency": { term: "Optimistic concurrency", def: "A version number on a row so two requests changing it at once can't both win — the second notices it changed and backs off." },
  "race-condition": { term: "Race condition", def: "A bug where two things happen at the same instant and collide on the same data, producing a wrong result (like spending the same points twice)." },
  cache: { term: "Cache", def: "A ready-made copy of an expensive answer (like the menu), kept close by so most requests are served instantly instead of recomputed." },
  "cache-invalidation": { term: "Cache invalidation", def: "Throwing away a cached copy when the real data changes, so you don't keep serving a stale price. Famously the hard part of caching." },
  queue: { term: "Queue", def: "A line of messages for slow or external work. The backend drops a job on it and replies instantly; a separate worker handles the job later." },
  worker: { term: "Worker", def: "A separate process that picks jobs off a queue and does the slow work (sending emails, notifying the kitchen) in the background." },
  "load-balancer": { term: "Load balancer", def: "One public 'door' that spreads incoming requests across many identical copies of the backend, so traffic can grow by adding copies." },
  "horizontal-scaling": { term: "Horizontal scaling", def: "Handling more load by running more copies of the same thing, rather than one ever-bigger machine. Statelessness is what makes it possible." },
  cdn: { term: "CDN", def: "A network of servers around the world that keep copies of images/files close to users, so they load fast everywhere." },
  redis: { term: "Redis", def: "A very fast in-memory store often used as a shared cache that all backend copies read from." },
  observability: { term: "Observability", def: "Being able to see what your running system is doing — logs, metrics, and traces — so you can find a problem before customers tell you." },
  "request-id": { term: "Request id", def: "A unique tag attached to each request so you can follow one order's whole journey across every part of the system." },

  // ── admin & ops ──
  refine: { term: "Refine", def: "A framework that generates the admin panel's repetitive screens (list, create, edit, view) so they don't have to be hand-built." },
  crud: { term: "CRUD", def: "Create, Read, Update, Delete — the four basic things you do to data, and the four screens an admin panel mostly needs." },
  nextjs: { term: "Next.js", def: "The framework behind the admin panel (and this site). It adds routing, server rendering, and a build system on top of React." },
  react: { term: "React", def: "A library for building web interfaces out of reusable 'components' — the web equivalent of Flutter's widgets." },
  component: { term: "Component", def: "A reusable piece of UI that renders itself from data — a button, a table, a card. You build pages by composing them." },
  ssr: { term: "Server rendering", def: "Building a page's HTML on the server so it arrives ready-to-show and fast, instead of a blank page that fills in later." },
  docker: { term: "Docker", def: "A way to pack an app together with everything it needs into one sealed 'container' that runs identically on any machine." },
  kubernetes: { term: "Kubernetes", def: "A manager for many containers — it runs them, restarts crashed ones, and adds or removes copies as load changes." },
  "ci-cd": { term: "CI/CD", def: "Automatically testing every change and then deploying it — so broken code is caught before it ships, and shipping is routine." },
  "environment-variable": { term: "Environment variable", def: "A setting (like the database address or a secret key) supplied to the app from outside the code, so secrets never live in the codebase." },
  deploy: { term: "Deploy", def: "To put a new version of the code live on the server where real customers use it." },
  infrastructure: { term: "Infrastructure as code", def: "Describing your servers and database in a file in your repo, so a deploy is reproducible and reviewable instead of clicking around a dashboard." },

  // ── system design & scale ──
  latency: { term: "Latency", def: "How long you wait for a response, usually in milliseconds. Low latency feels instant; high latency feels laggy." },
  throughput: { term: "Throughput", def: "How much work a system gets done per second — requests served, orders processed. More throughput, more load handled." },
  bottleneck: { term: "Bottleneck", def: "The one slowest part that caps the whole system's speed, like the narrow neck of a bottle. Fix it and everything speeds up." },
  replica: { term: "Replica", def: "A copy of your database kept in sync with the original, so reads can be spread across many copies and one failure isn't fatal." },
  sharding: { term: "Sharding", def: "Splitting one huge database into pieces ('shards') by some key, so no single machine has to hold all of the data." },
  "eventual-consistency": { term: "Eventual consistency", def: "Copies of data may briefly disagree after a change, but given a moment they all settle on the same value. The trade for staying fast and available." },
  "cap-theorem": { term: "CAP theorem", def: "When the network splits, a distributed store can stay consistent or stay available — not both. You must choose which to sacrifice." },
  backpressure: { term: "Backpressure", def: "When a system is overwhelmed it pushes back — slowing or rejecting new work — instead of collapsing. A queue filling up is backpressure." },
  "rate-limiting": { term: "Rate limiting", def: "Capping how many requests one client may make in a window, so nobody (or no runaway bug) can flood the system." },
  "circuit-breaker": { term: "Circuit breaker", def: "A guard that stops calling a failing service for a while, so one sick dependency doesn't drag everything down — like an electrical breaker tripping." },
  retry: { term: "Retry", def: "Trying a failed request again, because many failures are temporary blips. Pair it with backoff and idempotency so retries stay safe." },
  "exponential-backoff": { term: "Exponential backoff", def: "Waiting longer and longer between retries (1s, 2s, 4s…) so a struggling service gets room to recover instead of being hammered." },
  saga: { term: "Saga", def: "A long job split into steps across services, each with an 'undo'. If a later step fails, earlier ones are reversed — consistency without one giant transaction." },
  "pub-sub": { term: "Pub/Sub", def: "Publishers post messages to a topic; any number of subscribers receive them. Sender and receiver never have to know about each other." },
  "message-broker": { term: "Message broker", def: "The middleman (like RabbitMQ or Kafka) that reliably carries messages between services, holding them until a worker is ready." },
  "vertical-scaling": { term: "Vertical scaling", def: "Handling more load by making one machine bigger (more CPU/RAM). Simple, but there's a ceiling — eventually you must scale out instead." },
  ttl: { term: "TTL", def: "Time To Live — how long a cached copy may be reused before it's considered stale and refetched." },
  eviction: { term: "Eviction", def: "Dropping items from a full cache to make room. The policy (often LRU) decides which ones go." },
  lru: { term: "LRU", def: "Least Recently Used — an eviction rule that throws out whatever hasn't been touched for the longest when space runs out." },
  "thundering-herd": { term: "Thundering herd", def: "A popular cached item expires and thousands of requests miss at once, all stampeding the slow source together." },
  "blast-radius": { term: "Blast radius", def: "How much of the system one failure takes down with it. Good design keeps the blast radius small." },
  consensus: { term: "Consensus", def: "How a group of machines agree on a single value or order of events, even when some are slow or fail. Raft is one such algorithm." },
  quorum: { term: "Quorum", def: "The minimum number of machines that must agree before a decision counts — usually more than half, so two conflicting majorities can't exist." },
  p99: { term: "p99 latency", def: "The latency that 99% of requests beat. It catches the slow tail that averages hide — the 1-in-100 users having a bad time." },
  slo: { term: "SLO / SLA", def: "An SLO is a target you hold yourself to ('99.9% of requests succeed'); an SLA is the promise you make to customers, often with penalties." },
  mttr: { term: "MTTR", def: "Mean Time To Recovery — how long, on average, to get back to healthy after an incident. Lower is more resilient." },

  // ── security ──
  encryption: { term: "Encryption", def: "Scrambling data with a key so only someone with the key can read it. Protects data in transit (TLS) and at rest." },
  hashing: { term: "Hashing", def: "A one-way scramble of data into a fixed fingerprint. Passwords are stored hashed, so a leak doesn't reveal them." },
  salt: { term: "Salt", def: "Random data added to each password before hashing, so identical passwords don't share a hash and precomputed-attack tables fail." },
  tls: { term: "TLS", def: "The lock on HTTPS. It encrypts traffic between app and server so nobody in between can read or tamper with it." },
  oauth: { term: "OAuth", def: "A standard for granting one app limited access to your account on another ('Sign in with Google') without sharing your password." },
  rbac: { term: "RBAC", def: "Role-Based Access Control — permissions attached to roles (admin, staff, customer) rather than individuals, so access is easy to reason about." },
  "least-privilege": { term: "Least privilege", def: "Give every part of the system only the access it truly needs — so a breach in one place can't reach everything." },
  xss: { term: "XSS", def: "Cross-Site Scripting — sneaking malicious JavaScript into a page so it runs in other users' browsers. Escaping output and a strict CSP stop it." },
  "sql-injection": { term: "SQL injection", def: "Tricking the database by smuggling SQL into an input field. Parameterised queries (never gluing strings together) shut it down." },
  ssrf: { term: "SSRF", def: "Server-Side Request Forgery — tricking your server into making requests to places it shouldn't, like internal-only systems." },
  "zero-trust": { term: "Zero trust", def: "Assume no request is safe just because it's 'inside' the network — verify identity and permission on every single call." },

  // ── the network ──
  dns: { term: "DNS", def: "The internet's phone book. It turns a name like burgerfarm.com into the numeric IP address of the server to talk to." },
  "ip-address": { term: "IP address", def: "The numeric address of a machine on a network — a postal address for packets of data." },
  port: { term: "Port", def: "A numbered door on a machine for a particular service — web traffic uses 80/443, a dev server maybe 3000." },
  "reverse-proxy": { term: "Reverse proxy", def: "A server that sits in front of your backends, taking all incoming requests and forwarding them — handy for TLS, caching and load balancing." },
  cors: { term: "CORS", def: "Browser rules deciding whether a page on one site may call an API on another. The server must explicitly allow it." },
  websocket: { term: "WebSocket", def: "A two-way, always-open connection between app and server, so either side can send messages any time — used for live chat and updates." },
  graphql: { term: "GraphQL", def: "An API style where the client asks for exactly the fields it wants in one request, instead of hitting many fixed REST endpoints." },
  grpc: { term: "gRPC", def: "A fast, typed way for services to call each other using compact binary messages — popular between backend services." },

  // ── cloud ──
  "virtual-machine": { term: "Virtual machine", def: "A whole simulated computer running on shared physical hardware, so one big server can safely host many isolated tenants." },
  serverless: { term: "Serverless", def: "You upload a function; the cloud runs it on demand and bills per call. No servers to manage — it scales to zero when idle." },
  "object-storage": { term: "Object storage", def: "Cheap, near-infinite storage for files (images, backups) addressed by a key, like Amazon S3. Not a filesystem, not a database." },
  region: { term: "Region", def: "A geographic cluster of a cloud's data centres. Running near your users cuts latency; spreading across regions survives disasters." },
  autoscaling: { term: "Autoscaling", def: "The cloud automatically adding copies of your app when traffic rises and removing them when it falls, so you pay for what you use." },

  // ── databases (more) ──
  nosql: { term: "NoSQL", def: "Databases that drop strict tables for flexible shapes (documents, key-values, graphs), trading some guarantees for scale and flexibility." },
  "b-tree": { term: "B-tree", def: "The balanced, multi-way tree most database indexes use, so lookups stay fast (few disk reads) even with millions of rows." },
  normalization: { term: "Normalization", def: "Organising data so each fact lives in exactly one place, avoiding duplicates that can drift out of sync." },
  deadlock: { term: "Deadlock", def: "Two transactions each holding what the other needs, both stuck forever. The database detects it and kills one to break the tie." },
  "connection-pool": { term: "Connection pool", def: "A reusable set of open database connections, so requests borrow one instead of paying to open a fresh connection each time." },

  // ── AI & ML ──
  llm: { term: "LLM", def: "A Large Language Model — an AI trained on huge amounts of text to predict the next word, which lets it write, summarise and answer." },
  embedding: { term: "Embedding", def: "Turning text into a list of numbers that captures its meaning, so similar ideas sit close together — the basis of semantic search." },
  "vector-search": { term: "Vector search", def: "Finding the items whose embeddings are nearest to your query's — closest in meaning, rather than by exact keyword." },
  rag: { term: "RAG", def: "Retrieval-Augmented Generation — fetch relevant documents first, then ask the model to answer using them, so it stays grounded and cites sources." },
  transformer: { term: "Transformer", def: "The neural-network design behind modern LLMs. Its 'attention' lets it weigh how much each word relates to every other." },
  hallucination: { term: "Hallucination", def: "When an AI states something false but confident. Grounding it in real sources (RAG) is the main defence." },
  inference: { term: "Inference", def: "Actually running a trained model to get an answer (as opposed to training it). It's what costs you per request in production." },

  // ── foundations & craft ──
  "big-o": { term: "Big-O", def: "Shorthand for how an algorithm's cost grows as the input grows — O(n) doubles when the data doubles; O(1) doesn't care about size." },
  recursion: { term: "Recursion", def: "A function that solves a problem by calling itself on a smaller piece, until it hits a simple base case." },
  concurrency: { term: "Concurrency", def: "Juggling many tasks so they all make progress together (not necessarily at the same instant) — like one cook starting several dishes." },
  abstraction: { term: "Abstraction", def: "Hiding messy detail behind a simple interface, so you can use a thing without knowing how it works inside." },
  coupling: { term: "Coupling", def: "How tightly two pieces of code depend on each other. Loose coupling means you can change one without breaking the other." },
  "separation-of-concerns": { term: "Separation of concerns", def: "Giving each part of the system one clear job — who-asks kept separate from who-does — so each can change independently." },
  "single-source-of-truth": { term: "Single source of truth", def: "Keeping each fact in exactly one authoritative place, so different parts of the app can never disagree about it." },
};
